export interface GeographyFact {
  country: string;
  statType: "population" | "area" | "capital";
  question: string;
  correctAnswer: string;
  distractors: [string, string, string];
}

// ─── Extended Geography Facts (292 entries) ──────────────────────────────────

export const GEOGRAPHY_FACTS_EXT: GeographyFact[] = [
  // ── Capitals of Lesser-Known Countries (1-100) ────────────────────────────
  {
    country: "Nauru",
    statType: "capital",
    question: "What is the capital (or government seat) of Nauru?",
    correctAnswer: "Yaren (de facto)",
    distractors: ["Aiwo", "Buada", "Meneng"],
  },
  {
    country: "Palau",
    statType: "capital",
    question: "What is the capital of Palau?",
    correctAnswer: "Ngerulmud",
    distractors: ["Koror", "Melekeok", "Airai"],
  },
  {
    country: "Tuvalu",
    statType: "capital",
    question: "What is the capital of Tuvalu?",
    correctAnswer: "Funafuti",
    distractors: ["Nanumea", "Vaitupu", "Nukufetau"],
  },
  {
    country: "Kiribati",
    statType: "capital",
    question: "What is the capital of Kiribati?",
    correctAnswer: "South Tarawa",
    distractors: ["Betio", "Kiritimati", "Butaritari"],
  },
  {
    country: "Vanuatu",
    statType: "capital",
    question: "What is the capital of Vanuatu?",
    correctAnswer: "Port Vila",
    distractors: ["Luganville", "Lakatoro", "Isangel"],
  },
  {
    country: "Comoros",
    statType: "capital",
    question: "What is the capital of the Comoros?",
    correctAnswer: "Moroni",
    distractors: ["Mutsamudu", "Fomboni", "Domoni"],
  },
  {
    country: "São Tomé and Príncipe",
    statType: "capital",
    question: "What is the capital of São Tomé and Príncipe?",
    correctAnswer: "São Tomé",
    distractors: ["Santo Amaro", "Neves", "Trindade"],
  },
  {
    country: "Djibouti",
    statType: "capital",
    question: "What is the capital of Djibouti?",
    correctAnswer: "Djibouti (city)",
    distractors: ["Ali Sabieh", "Tadjoura", "Obock"],
  },
  {
    country: "Eswatini",
    statType: "capital",
    question: "What are the two capitals of Eswatini (administrative and legislative)?",
    correctAnswer: "Mbabane (administrative) and Lobamba (legislative)",
    distractors: ["Manzini and Mbabane", "Lobamba and Manzini", "Siteki and Mbabane"],
  },
  {
    country: "Lesotho",
    statType: "capital",
    question: "What is the capital of Lesotho?",
    correctAnswer: "Maseru",
    distractors: ["Teyateyaneng", "Mafeteng", "Leribe"],
  },
  {
    country: "Bhutan",
    statType: "capital",
    question: "What is the capital of Bhutan?",
    correctAnswer: "Thimphu",
    distractors: ["Paro", "Punakha", "Phuntsholing"],
  },
  {
    country: "Brunei",
    statType: "capital",
    question: "What is the capital of Brunei?",
    correctAnswer: "Bandar Seri Begawan",
    distractors: ["Seria", "Tutong", "Temburong"],
  },
  {
    country: "Timor-Leste",
    statType: "capital",
    question: "What is the capital of Timor-Leste (East Timor)?",
    correctAnswer: "Dili",
    distractors: ["Baucau", "Maliana", "Suai"],
  },
  {
    country: "Suriname",
    statType: "capital",
    question: "What is the capital of Suriname?",
    correctAnswer: "Paramaribo",
    distractors: ["Nieuw Nickerie", "Lelydorp", "Brokopondo"],
  },
  {
    country: "Guyana",
    statType: "capital",
    question: "What is the capital of Guyana?",
    correctAnswer: "Georgetown",
    distractors: ["Linden", "New Amsterdam", "Bartica"],
  },
  {
    country: "Mauritania",
    statType: "capital",
    question: "What is the capital of Mauritania?",
    correctAnswer: "Nouakchott",
    distractors: ["Nouadhibou", "Atar", "Kaédi"],
  },
  {
    country: "Eritrea",
    statType: "capital",
    question: "What is the capital of Eritrea?",
    correctAnswer: "Asmara",
    distractors: ["Massawa", "Keren", "Assab"],
  },
  {
    country: "Burkina Faso",
    statType: "capital",
    question: "What is the capital of Burkina Faso?",
    correctAnswer: "Ouagadougou",
    distractors: ["Bobo-Dioulasso", "Koudougou", "Banfora"],
  },
  {
    country: "Cabo Verde",
    statType: "capital",
    question: "What is the capital of Cabo Verde (Cape Verde)?",
    correctAnswer: "Praia",
    distractors: ["Mindelo", "Espargos", "Santa Maria"],
  },
  {
    country: "Guinea-Bissau",
    statType: "capital",
    question: "What is the capital of Guinea-Bissau?",
    correctAnswer: "Bissau",
    distractors: ["Bafatá", "Gabú", "Cacheu"],
  },
  {
    country: "Equatorial Guinea",
    statType: "capital",
    question: "What is the capital of Equatorial Guinea?",
    correctAnswer: "Malabo",
    distractors: ["Bata", "Oyala (Ciudad de la Paz)", "Ebebiyín"],
  },
  {
    country: "Gabon",
    statType: "capital",
    question: "What is the capital of Gabon?",
    correctAnswer: "Libreville",
    distractors: ["Port-Gentil", "Franceville", "Oyem"],
  },
  {
    country: "Republic of the Congo",
    statType: "capital",
    question: "What is the capital of the Republic of the Congo?",
    correctAnswer: "Brazzaville",
    distractors: ["Pointe-Noire", "Dolisie", "Nkayi"],
  },
  {
    country: "Central African Republic",
    statType: "capital",
    question: "What is the capital of the Central African Republic?",
    correctAnswer: "Bangui",
    distractors: ["Bimbo", "Berbérati", "Carnot"],
  },
  {
    country: "Chad",
    statType: "capital",
    question: "What is the capital of Chad?",
    correctAnswer: "N'Djamena",
    distractors: ["Moundou", "Sarh", "Abéché"],
  },
  {
    country: "Togo",
    statType: "capital",
    question: "What is the capital of Togo?",
    correctAnswer: "Lomé",
    distractors: ["Sokodé", "Kara", "Kpalimé"],
  },
  {
    country: "Benin",
    statType: "capital",
    question: "What is the capital of Benin?",
    correctAnswer: "Porto-Novo",
    distractors: ["Cotonou", "Parakou", "Djougou"],
  },
  {
    country: "Niger",
    statType: "capital",
    question: "What is the capital of Niger?",
    correctAnswer: "Niamey",
    distractors: ["Zinder", "Maradi", "Agadez"],
  },
  {
    country: "Mali",
    statType: "capital",
    question: "What is the capital of Mali?",
    correctAnswer: "Bamako",
    distractors: ["Timbuktu", "Mopti", "Ségou"],
  },
  {
    country: "The Gambia",
    statType: "capital",
    question: "What is the capital of The Gambia?",
    correctAnswer: "Banjul",
    distractors: ["Serekunda", "Brikama", "Bakau"],
  },
  {
    country: "Liechtenstein",
    statType: "capital",
    question: "What is the capital of Liechtenstein?",
    correctAnswer: "Vaduz",
    distractors: ["Schaan", "Balzers", "Triesen"],
  },
  {
    country: "Andorra",
    statType: "capital",
    question: "What is the capital of Andorra?",
    correctAnswer: "Andorra la Vella",
    distractors: ["Escaldes-Engordany", "Encamp", "La Massana"],
  },
  {
    country: "San Marino",
    statType: "capital",
    question: "What is the capital of San Marino?",
    correctAnswer: "City of San Marino",
    distractors: ["Serravalle", "Borgo Maggiore", "Domagnano"],
  },
  {
    country: "Monaco",
    statType: "capital",
    question: "What is the administrative center (and only city) of Monaco?",
    correctAnswer: "Monaco (the city-state itself; the traditional capital quarter is Monaco-Ville)",
    distractors: ["Monte Carlo", "La Condamine", "Fontvieille"],
  },
  {
    country: "Malta",
    statType: "capital",
    question: "What is the capital of Malta?",
    correctAnswer: "Valletta",
    distractors: ["Mdina", "Sliema", "Birkirkara"],
  },
  {
    country: "Moldova",
    statType: "capital",
    question: "What is the capital of Moldova?",
    correctAnswer: "Chișinău",
    distractors: ["Tiraspol", "Bălți", "Cahul"],
  },
  {
    country: "North Macedonia",
    statType: "capital",
    question: "What is the capital of North Macedonia?",
    correctAnswer: "Skopje",
    distractors: ["Bitola", "Ohrid", "Kumanovo"],
  },
  {
    country: "Kosovo",
    statType: "capital",
    question: "What is the capital of Kosovo?",
    correctAnswer: "Pristina",
    distractors: ["Prizren", "Mitrovica", "Peja"],
  },
  {
    country: "Montenegro",
    statType: "capital",
    question: "What is the capital of Montenegro?",
    correctAnswer: "Podgorica",
    distractors: ["Cetinje", "Nikšić", "Budva"],
  },
  {
    country: "Tajikistan",
    statType: "capital",
    question: "What is the capital of Tajikistan?",
    correctAnswer: "Dushanbe",
    distractors: ["Khujand", "Kulob", "Istaravshan"],
  },
  {
    country: "Turkmenistan",
    statType: "capital",
    question: "What is the capital of Turkmenistan?",
    correctAnswer: "Ashgabat",
    distractors: ["Türkmenabat", "Daşoguz", "Mary"],
  },
  {
    country: "Kyrgyzstan",
    statType: "capital",
    question: "What is the capital of Kyrgyzstan?",
    correctAnswer: "Bishkek",
    distractors: ["Osh", "Jalal-Abad", "Karakol"],
  },
  {
    country: "Laos",
    statType: "capital",
    question: "What is the capital of Laos?",
    correctAnswer: "Vientiane",
    distractors: ["Luang Prabang", "Savannakhet", "Pakse"],
  },
  {
    country: "Myanmar",
    statType: "capital",
    question: "What is the capital of Myanmar?",
    correctAnswer: "Naypyidaw",
    distractors: ["Yangon", "Mandalay", "Bago"],
  },
  {
    country: "Maldives",
    statType: "capital",
    question: "What is the capital of the Maldives?",
    correctAnswer: "Malé",
    distractors: ["Addu City", "Fuvahmulah", "Kulhudhuffushi"],
  },
  {
    country: "Micronesia",
    statType: "capital",
    question: "What is the capital of the Federated States of Micronesia?",
    correctAnswer: "Palikir",
    distractors: ["Kolonia", "Weno", "Tofol"],
  },
  {
    country: "Marshall Islands",
    statType: "capital",
    question: "What is the capital of the Marshall Islands?",
    correctAnswer: "Majuro",
    distractors: ["Ebeye", "Kwajalein", "Jaluit"],
  },
  {
    country: "Tonga",
    statType: "capital",
    question: "What is the capital of Tonga?",
    correctAnswer: "Nukuʻalofa",
    distractors: ["Neiafu", "Pangai", "Ohonua"],
  },
  {
    country: "Samoa",
    statType: "capital",
    question: "What is the capital of Samoa?",
    correctAnswer: "Apia",
    distractors: ["Salelologa", "Mulifanua", "Faleasiu"],
  },
  {
    country: "Solomon Islands",
    statType: "capital",
    question: "What is the capital of the Solomon Islands?",
    correctAnswer: "Honiara",
    distractors: ["Gizo", "Auki", "Tulagi"],
  },
  {
    country: "Fiji",
    statType: "capital",
    question: "What is the capital of Fiji?",
    correctAnswer: "Suva",
    distractors: ["Nadi", "Lautoka", "Labasa"],
  },
  {
    country: "Papua New Guinea",
    statType: "capital",
    question: "What is the capital of Papua New Guinea?",
    correctAnswer: "Port Moresby",
    distractors: ["Lae", "Mount Hagen", "Madang"],
  },
  {
    country: "Seychelles",
    statType: "capital",
    question: "What is the capital of Seychelles?",
    correctAnswer: "Victoria",
    distractors: ["Anse Royale", "Beau Vallon", "Takamaka"],
  },
  {
    country: "Mauritius",
    statType: "capital",
    question: "What is the capital of Mauritius?",
    correctAnswer: "Port Louis",
    distractors: ["Curepipe", "Vacoas-Phoenix", "Quatre Bornes"],
  },
  {
    country: "Madagascar",
    statType: "capital",
    question: "What is the capital of Madagascar?",
    correctAnswer: "Antananarivo",
    distractors: ["Toamasina", "Antsirabe", "Mahajanga"],
  },
  {
    country: "Burundi",
    statType: "capital",
    question: "What is the capital of Burundi?",
    correctAnswer: "Gitega",
    distractors: ["Bujumbura", "Ngozi", "Muyinga"],
  },
  {
    country: "South Sudan",
    statType: "capital",
    question: "What is the capital of South Sudan?",
    correctAnswer: "Juba",
    distractors: ["Malakal", "Wau", "Bor"],
  },
  {
    country: "Malawi",
    statType: "capital",
    question: "What is the capital of Malawi?",
    correctAnswer: "Lilongwe",
    distractors: ["Blantyre", "Mzuzu", "Zomba"],
  },
  {
    country: "Zambia",
    statType: "capital",
    question: "What is the capital of Zambia?",
    correctAnswer: "Lusaka",
    distractors: ["Kitwe", "Ndola", "Livingstone"],
  },
  {
    country: "Botswana",
    statType: "capital",
    question: "What is the capital of Botswana?",
    correctAnswer: "Gaborone",
    distractors: ["Francistown", "Maun", "Kasane"],
  },
  {
    country: "Namibia",
    statType: "capital",
    question: "What is the capital of Namibia?",
    correctAnswer: "Windhoek",
    distractors: ["Walvis Bay", "Swakopmund", "Rundu"],
  },
  {
    country: "Belize",
    statType: "capital",
    question: "What is the capital of Belize?",
    correctAnswer: "Belmopan",
    distractors: ["Belize City", "San Ignacio", "Orange Walk Town"],
  },
  {
    country: "Honduras",
    statType: "capital",
    question: "What is the capital of Honduras?",
    correctAnswer: "Tegucigalpa",
    distractors: ["San Pedro Sula", "La Ceiba", "Comayagua"],
  },
  {
    country: "El Salvador",
    statType: "capital",
    question: "What is the capital of El Salvador?",
    correctAnswer: "San Salvador",
    distractors: ["Santa Ana", "San Miguel", "Soyapango"],
  },
  {
    country: "Nicaragua",
    statType: "capital",
    question: "What is the capital of Nicaragua?",
    correctAnswer: "Managua",
    distractors: ["León", "Granada", "Masaya"],
  },
  {
    country: "Trinidad and Tobago",
    statType: "capital",
    question: "What is the capital of Trinidad and Tobago?",
    correctAnswer: "Port of Spain",
    distractors: ["San Fernando", "Chaguanas", "Scarborough"],
  },
  {
    country: "Barbados",
    statType: "capital",
    question: "What is the capital of Barbados?",
    correctAnswer: "Bridgetown",
    distractors: ["Speightstown", "Holetown", "Oistins"],
  },
  {
    country: "Saint Lucia",
    statType: "capital",
    question: "What is the capital of Saint Lucia?",
    correctAnswer: "Castries",
    distractors: ["Soufrière", "Vieux Fort", "Gros Islet"],
  },
  {
    country: "Dominica",
    statType: "capital",
    question: "What is the capital of Dominica?",
    correctAnswer: "Roseau",
    distractors: ["Portsmouth", "Marigot", "Mahaut"],
  },
  {
    country: "Grenada",
    statType: "capital",
    question: "What is the capital of Grenada?",
    correctAnswer: "St. George's",
    distractors: ["Gouyave", "Grenville", "Sauteurs"],
  },
  {
    country: "Antigua and Barbuda",
    statType: "capital",
    question: "What is the capital of Antigua and Barbuda?",
    correctAnswer: "St. John's",
    distractors: ["Codrington", "All Saints", "Falmouth"],
  },
  {
    country: "Saint Kitts and Nevis",
    statType: "capital",
    question: "What is the capital of Saint Kitts and Nevis?",
    correctAnswer: "Basseterre",
    distractors: ["Charlestown", "Sandy Point Town", "Old Road"],
  },
  {
    country: "Saint Vincent and the Grenadines",
    statType: "capital",
    question: "What is the capital of Saint Vincent and the Grenadines?",
    correctAnswer: "Kingstown",
    distractors: ["Georgetown", "Barrouallie", "Layou"],
  },
  {
    country: "Bahrain",
    statType: "capital",
    question: "What is the capital of Bahrain?",
    correctAnswer: "Manama",
    distractors: ["Muharraq", "Riffa", "Isa Town"],
  },
  {
    country: "Qatar",
    statType: "capital",
    question: "What is the capital of Qatar?",
    correctAnswer: "Doha",
    distractors: ["Al Wakrah", "Al Khor", "Lusail"],
  },
  {
    country: "Oman",
    statType: "capital",
    question: "What is the capital of Oman?",
    correctAnswer: "Muscat",
    distractors: ["Salalah", "Sohar", "Nizwa"],
  },
  {
    country: "Yemen",
    statType: "capital",
    question: "What is the capital of Yemen?",
    correctAnswer: "Sana'a",
    distractors: ["Aden", "Taiz", "Al Hudaydah"],
  },
  {
    country: "Uzbekistan",
    statType: "capital",
    question: "What is the capital of Uzbekistan?",
    correctAnswer: "Tashkent",
    distractors: ["Samarkand", "Bukhara", "Namangan"],
  },
  {
    country: "Azerbaijan",
    statType: "capital",
    question: "What is the capital of Azerbaijan?",
    correctAnswer: "Baku",
    distractors: ["Ganja", "Sumqayit", "Mingachevir"],
  },
  {
    country: "Georgia",
    statType: "capital",
    question: "What is the capital of Georgia (the country)?",
    correctAnswer: "Tbilisi",
    distractors: ["Batumi", "Kutaisi", "Rustavi"],
  },
  {
    country: "Armenia",
    statType: "capital",
    question: "What is the capital of Armenia?",
    correctAnswer: "Yerevan",
    distractors: ["Gyumri", "Vanadzor", "Vagharshapat"],
  },
  {
    country: "Nepal",
    statType: "capital",
    question: "What is the capital of Nepal?",
    correctAnswer: "Kathmandu",
    distractors: ["Pokhara", "Lalitpur", "Bhaktapur"],
  },
  {
    country: "Sri Lanka",
    statType: "capital",
    question: "What is the legislative capital of Sri Lanka?",
    correctAnswer: "Sri Jayawardenepura Kotte",
    distractors: ["Colombo", "Kandy", "Galle"],
  },
  {
    country: "Mongolia",
    statType: "capital",
    question: "What is the capital of Mongolia?",
    correctAnswer: "Ulaanbaatar",
    distractors: ["Erdenet", "Darkhan", "Choibalsan"],
  },
  {
    country: "Togo",
    statType: "area",
    question: "What is the approximate area of Togo?",
    correctAnswer: "≈ 56,785 km²",
    distractors: ["≈ 112,622 km²", "≈ 28,000 km²", "≈ 75,000 km²"],
  },
  {
    country: "Bolivia",
    statType: "capital",
    question: "What is the constitutional capital of Bolivia?",
    correctAnswer: "Sucre",
    distractors: ["La Paz", "Santa Cruz de la Sierra", "Cochabamba"],
  },
  {
    country: "Paraguay",
    statType: "capital",
    question: "What is the capital of Paraguay?",
    correctAnswer: "Asunción",
    distractors: ["Ciudad del Este", "Encarnación", "San Lorenzo"],
  },
  {
    country: "Uruguay",
    statType: "capital",
    question: "What is the capital of Uruguay?",
    correctAnswer: "Montevideo",
    distractors: ["Salto", "Paysandú", "Rivera"],
  },
  {
    country: "Ivory Coast",
    statType: "capital",
    question: "What is the political capital of Ivory Coast (Côte d'Ivoire)?",
    correctAnswer: "Yamoussoukro",
    distractors: ["Abidjan", "Bouaké", "San-Pédro"],
  },
  {
    country: "Sierra Leone",
    statType: "capital",
    question: "What is the capital of Sierra Leone?",
    correctAnswer: "Freetown",
    distractors: ["Bo", "Kenema", "Makeni"],
  },
  {
    country: "Liberia",
    statType: "capital",
    question: "What is the capital of Liberia?",
    correctAnswer: "Monrovia",
    distractors: ["Buchanan", "Gbarnga", "Kakata"],
  },
  {
    country: "Rwanda",
    statType: "capital",
    question: "What is the capital of Rwanda?",
    correctAnswer: "Kigali",
    distractors: ["Butare", "Gisenyi", "Ruhengeri"],
  },
  {
    country: "Somalia",
    statType: "capital",
    question: "What is the capital of Somalia?",
    correctAnswer: "Mogadishu",
    distractors: ["Hargeisa", "Kismayo", "Berbera"],
  },
  {
    country: "Mozambique",
    statType: "capital",
    question: "What is the capital of Mozambique?",
    correctAnswer: "Maputo",
    distractors: ["Beira", "Nampula", "Quelimane"],
  },
  {
    country: "Zimbabwe",
    statType: "capital",
    question: "What is the capital of Zimbabwe?",
    correctAnswer: "Harare",
    distractors: ["Bulawayo", "Mutare", "Gweru"],
  },
  {
    country: "Angola",
    statType: "capital",
    question: "What is the capital of Angola?",
    correctAnswer: "Luanda",
    distractors: ["Huambo", "Lobito", "Benguela"],
  },
  {
    country: "Democratic Republic of the Congo",
    statType: "capital",
    question: "What is the capital of the Democratic Republic of the Congo?",
    correctAnswer: "Kinshasa",
    distractors: ["Lubumbashi", "Kisangani", "Goma"],
  },
  {
    country: "Cameroon",
    statType: "capital",
    question: "What is the capital of Cameroon?",
    correctAnswer: "Yaoundé",
    distractors: ["Douala", "Garoua", "Bamenda"],
  },
  // ── Population Questions (101-180) ────────────────────────────────────────
  {
    country: "India",
    statType: "population",
    question: "What is the approximate population of India as of 2024?",
    correctAnswer: "≈ 1.44 billion",
    distractors: ["≈ 1.10 billion", "≈ 1.65 billion", "≈ 980 million"],
  },
  {
    country: "China",
    statType: "population",
    question: "What is the approximate population of China as of 2024?",
    correctAnswer: "≈ 1.41 billion",
    distractors: ["≈ 1.60 billion", "≈ 1.20 billion", "≈ 980 million"],
  },
  {
    country: "Indonesia",
    statType: "population",
    question: "What is the approximate population of Indonesia?",
    correctAnswer: "≈ 278 million",
    distractors: ["≈ 200 million", "≈ 350 million", "≈ 155 million"],
  },
  {
    country: "Pakistan",
    statType: "population",
    question: "What is the approximate population of Pakistan?",
    correctAnswer: "≈ 240 million",
    distractors: ["≈ 180 million", "≈ 310 million", "≈ 140 million"],
  },
  {
    country: "Nigeria",
    statType: "population",
    question: "What is the approximate population of Nigeria?",
    correctAnswer: "≈ 230 million",
    distractors: ["≈ 150 million", "≈ 310 million", "≈ 120 million"],
  },
  {
    country: "Brazil",
    statType: "population",
    question: "What is the approximate population of Brazil?",
    correctAnswer: "≈ 216 million",
    distractors: ["≈ 180 million", "≈ 260 million", "≈ 145 million"],
  },
  {
    country: "Bangladesh",
    statType: "population",
    question: "What is the approximate population of Bangladesh?",
    correctAnswer: "≈ 173 million",
    distractors: ["≈ 120 million", "≈ 220 million", "≈ 90 million"],
  },
  {
    country: "Russia",
    statType: "population",
    question: "What is the approximate population of Russia?",
    correctAnswer: "≈ 144 million",
    distractors: ["≈ 190 million", "≈ 110 million", "≈ 220 million"],
  },
  {
    country: "Mexico",
    statType: "population",
    question: "What is the approximate population of Mexico?",
    correctAnswer: "≈ 130 million",
    distractors: ["≈ 95 million", "≈ 165 million", "≈ 80 million"],
  },
  {
    country: "Ethiopia",
    statType: "population",
    question: "What is the approximate population of Ethiopia?",
    correctAnswer: "≈ 126 million",
    distractors: ["≈ 85 million", "≈ 160 million", "≈ 65 million"],
  },
  {
    country: "Japan",
    statType: "population",
    question: "What is the approximate population of Japan?",
    correctAnswer: "≈ 124 million",
    distractors: ["≈ 150 million", "≈ 98 million", "≈ 170 million"],
  },
  {
    country: "Philippines",
    statType: "population",
    question: "What is the approximate population of the Philippines?",
    correctAnswer: "≈ 117 million",
    distractors: ["≈ 85 million", "≈ 145 million", "≈ 65 million"],
  },
  {
    country: "Egypt",
    statType: "population",
    question: "What is the approximate population of Egypt?",
    correctAnswer: "≈ 112 million",
    distractors: ["≈ 85 million", "≈ 140 million", "≈ 65 million"],
  },
  {
    country: "DR Congo",
    statType: "population",
    question: "What is the approximate population of the Democratic Republic of the Congo?",
    correctAnswer: "≈ 102 million",
    distractors: ["≈ 65 million", "≈ 140 million", "≈ 50 million"],
  },
  {
    country: "Vietnam",
    statType: "population",
    question: "What is the approximate population of Vietnam?",
    correctAnswer: "≈ 100 million",
    distractors: ["≈ 70 million", "≈ 130 million", "≈ 55 million"],
  },
  {
    country: "Germany",
    statType: "population",
    question: "What is the approximate population of Germany?",
    correctAnswer: "≈ 84 million",
    distractors: ["≈ 65 million", "≈ 100 million", "≈ 50 million"],
  },
  {
    country: "Turkey",
    statType: "population",
    question: "What is the approximate population of Turkey?",
    correctAnswer: "≈ 85 million",
    distractors: ["≈ 65 million", "≈ 105 million", "≈ 50 million"],
  },
  {
    country: "Thailand",
    statType: "population",
    question: "What is the approximate population of Thailand?",
    correctAnswer: "≈ 72 million",
    distractors: ["≈ 55 million", "≈ 95 million", "≈ 40 million"],
  },
  {
    country: "United Kingdom",
    statType: "population",
    question: "What is the approximate population of the United Kingdom?",
    correctAnswer: "≈ 68 million",
    distractors: ["≈ 55 million", "≈ 82 million", "≈ 45 million"],
  },
  {
    country: "France",
    statType: "population",
    question: "What is the approximate population of France?",
    correctAnswer: "≈ 68 million",
    distractors: ["≈ 55 million", "≈ 82 million", "≈ 45 million"],
  },
  {
    country: "Italy",
    statType: "population",
    question: "What is the approximate population of Italy?",
    correctAnswer: "≈ 59 million",
    distractors: ["≈ 45 million", "≈ 72 million", "≈ 38 million"],
  },
  {
    country: "South Africa",
    statType: "population",
    question: "What is the approximate population of South Africa?",
    correctAnswer: "≈ 62 million",
    distractors: ["≈ 45 million", "≈ 78 million", "≈ 35 million"],
  },
  {
    country: "Kenya",
    statType: "population",
    question: "What is the approximate population of Kenya?",
    correctAnswer: "≈ 55 million",
    distractors: ["≈ 38 million", "≈ 72 million", "≈ 28 million"],
  },
  {
    country: "South Korea",
    statType: "population",
    question: "What is the approximate population of South Korea?",
    correctAnswer: "≈ 52 million",
    distractors: ["≈ 38 million", "≈ 65 million", "≈ 75 million"],
  },
  {
    country: "Colombia",
    statType: "population",
    question: "What is the approximate population of Colombia?",
    correctAnswer: "≈ 52 million",
    distractors: ["≈ 38 million", "≈ 65 million", "≈ 28 million"],
  },
  {
    country: "Spain",
    statType: "population",
    question: "What is the approximate population of Spain?",
    correctAnswer: "≈ 48 million",
    distractors: ["≈ 35 million", "≈ 62 million", "≈ 28 million"],
  },
  {
    country: "Argentina",
    statType: "population",
    question: "What is the approximate population of Argentina?",
    correctAnswer: "≈ 46 million",
    distractors: ["≈ 32 million", "≈ 60 million", "≈ 25 million"],
  },
  {
    country: "Algeria",
    statType: "population",
    question: "What is the approximate population of Algeria?",
    correctAnswer: "≈ 45 million",
    distractors: ["≈ 30 million", "≈ 60 million", "≈ 22 million"],
  },
  {
    country: "Sudan",
    statType: "population",
    question: "What is the approximate population of Sudan?",
    correctAnswer: "≈ 48 million",
    distractors: ["≈ 32 million", "≈ 65 million", "≈ 22 million"],
  },
  {
    country: "Uganda",
    statType: "population",
    question: "What is the approximate population of Uganda?",
    correctAnswer: "≈ 48 million",
    distractors: ["≈ 32 million", "≈ 62 million", "≈ 22 million"],
  },
  {
    country: "Canada",
    statType: "population",
    question: "What is the approximate population of Canada?",
    correctAnswer: "≈ 40 million",
    distractors: ["≈ 28 million", "≈ 55 million", "≈ 22 million"],
  },
  {
    country: "Poland",
    statType: "population",
    question: "What is the approximate population of Poland?",
    correctAnswer: "≈ 38 million",
    distractors: ["≈ 28 million", "≈ 50 million", "≈ 22 million"],
  },
  {
    country: "Morocco",
    statType: "population",
    question: "What is the approximate population of Morocco?",
    correctAnswer: "≈ 37 million",
    distractors: ["≈ 25 million", "≈ 50 million", "≈ 18 million"],
  },
  {
    country: "Australia",
    statType: "population",
    question: "What is the approximate population of Australia?",
    correctAnswer: "≈ 26 million",
    distractors: ["≈ 18 million", "≈ 35 million", "≈ 42 million"],
  },
  {
    country: "Ghana",
    statType: "population",
    question: "What is the approximate population of Ghana?",
    correctAnswer: "≈ 34 million",
    distractors: ["≈ 22 million", "≈ 48 million", "≈ 15 million"],
  },
  {
    country: "Nepal",
    statType: "population",
    question: "What is the approximate population of Nepal?",
    correctAnswer: "≈ 31 million",
    distractors: ["≈ 20 million", "≈ 42 million", "≈ 15 million"],
  },
  {
    country: "Uzbekistan",
    statType: "population",
    question: "What is the approximate population of Uzbekistan?",
    correctAnswer: "≈ 36 million",
    distractors: ["≈ 24 million", "≈ 48 million", "≈ 16 million"],
  },
  {
    country: "Peru",
    statType: "population",
    question: "What is the approximate population of Peru?",
    correctAnswer: "≈ 34 million",
    distractors: ["≈ 22 million", "≈ 46 million", "≈ 16 million"],
  },
  {
    country: "Malaysia",
    statType: "population",
    question: "What is the approximate population of Malaysia?",
    correctAnswer: "≈ 34 million",
    distractors: ["≈ 22 million", "≈ 46 million", "≈ 15 million"],
  },
  {
    country: "Venezuela",
    statType: "population",
    question: "What is the approximate population of Venezuela?",
    correctAnswer: "≈ 28 million",
    distractors: ["≈ 18 million", "≈ 38 million", "≈ 45 million"],
  },
  {
    country: "Nauru",
    statType: "population",
    question: "What is the approximate population of Nauru?",
    correctAnswer: "≈ 12,500",
    distractors: ["≈ 50,000", "≈ 125,000", "≈ 5,000"],
  },
  {
    country: "Tuvalu",
    statType: "population",
    question: "What is the approximate population of Tuvalu?",
    correctAnswer: "≈ 11,300",
    distractors: ["≈ 50,000", "≈ 110,000", "≈ 5,000"],
  },
  {
    country: "Palau",
    statType: "population",
    question: "What is the approximate population of Palau?",
    correctAnswer: "≈ 18,000",
    distractors: ["≈ 55,000", "≈ 180,000", "≈ 8,000"],
  },
  {
    country: "Vatican City",
    statType: "population",
    question: "What is the approximate population of Vatican City?",
    correctAnswer: "≈ 800",
    distractors: ["≈ 5,000", "≈ 50,000", "≈ 200"],
  },
  {
    country: "San Marino",
    statType: "population",
    question: "What is the approximate population of San Marino?",
    correctAnswer: "≈ 33,000",
    distractors: ["≈ 100,000", "≈ 10,000", "≈ 250,000"],
  },
  {
    country: "Liechtenstein",
    statType: "population",
    question: "What is the approximate population of Liechtenstein?",
    correctAnswer: "≈ 39,000",
    distractors: ["≈ 120,000", "≈ 15,000", "≈ 250,000"],
  },
  {
    country: "Monaco",
    statType: "population",
    question: "What is the approximate population of Monaco?",
    correctAnswer: "≈ 39,000",
    distractors: ["≈ 120,000", "≈ 10,000", "≈ 250,000"],
  },
  {
    country: "Iceland",
    statType: "population",
    question: "What is the approximate population of Iceland?",
    correctAnswer: "≈ 390,000",
    distractors: ["≈ 750,000", "≈ 150,000", "≈ 1.2 million"],
  },
  {
    country: "Luxembourg",
    statType: "population",
    question: "What is the approximate population of Luxembourg?",
    correctAnswer: "≈ 660,000",
    distractors: ["≈ 250,000", "≈ 1.2 million", "≈ 2 million"],
  },
  {
    country: "Bhutan",
    statType: "population",
    question: "What is the approximate population of Bhutan?",
    correctAnswer: "≈ 790,000",
    distractors: ["≈ 2 million", "≈ 350,000", "≈ 5 million"],
  },
  {
    country: "Maldives",
    statType: "population",
    question: "What is the approximate population of the Maldives?",
    correctAnswer: "≈ 520,000",
    distractors: ["≈ 1.5 million", "≈ 200,000", "≈ 3 million"],
  },
  {
    country: "Brunei",
    statType: "population",
    question: "What is the approximate population of Brunei?",
    correctAnswer: "≈ 450,000",
    distractors: ["≈ 1.2 million", "≈ 150,000", "≈ 3 million"],
  },
  {
    country: "Comoros",
    statType: "population",
    question: "What is the approximate population of the Comoros?",
    correctAnswer: "≈ 900,000",
    distractors: ["≈ 2.5 million", "≈ 350,000", "≈ 5 million"],
  },
  {
    country: "Seychelles",
    statType: "population",
    question: "What is the approximate population of Seychelles?",
    correctAnswer: "≈ 100,000",
    distractors: ["≈ 350,000", "≈ 30,000", "≈ 750,000"],
  },
  {
    country: "São Tomé and Príncipe",
    statType: "population",
    question: "What is the approximate population of São Tomé and Príncipe?",
    correctAnswer: "≈ 230,000",
    distractors: ["≈ 600,000", "≈ 50,000", "≈ 1.5 million"],
  },
  {
    country: "Cabo Verde",
    statType: "population",
    question: "What is the approximate population of Cabo Verde?",
    correctAnswer: "≈ 600,000",
    distractors: ["≈ 1.5 million", "≈ 200,000", "≈ 3 million"],
  },
  {
    country: "Suriname",
    statType: "population",
    question: "What is the approximate population of Suriname?",
    correctAnswer: "≈ 620,000",
    distractors: ["≈ 1.5 million", "≈ 200,000", "≈ 3 million"],
  },
  {
    country: "Guyana",
    statType: "population",
    question: "What is the approximate population of Guyana?",
    correctAnswer: "≈ 810,000",
    distractors: ["≈ 2 million", "≈ 300,000", "≈ 5 million"],
  },
  {
    country: "Timor-Leste",
    statType: "population",
    question: "What is the approximate population of Timor-Leste?",
    correctAnswer: "≈ 1.4 million",
    distractors: ["≈ 3.5 million", "≈ 500,000", "≈ 6 million"],
  },
  {
    country: "Eswatini",
    statType: "population",
    question: "What is the approximate population of Eswatini?",
    correctAnswer: "≈ 1.2 million",
    distractors: ["≈ 3 million", "≈ 500,000", "≈ 5 million"],
  },
  {
    country: "Fiji",
    statType: "population",
    question: "What is the approximate population of Fiji?",
    correctAnswer: "≈ 930,000",
    distractors: ["≈ 2.5 million", "≈ 350,000", "≈ 5 million"],
  },
  {
    country: "Djibouti",
    statType: "population",
    question: "What is the approximate population of Djibouti?",
    correctAnswer: "≈ 1.1 million",
    distractors: ["≈ 3 million", "≈ 400,000", "≈ 5 million"],
  },
  {
    country: "Lesotho",
    statType: "population",
    question: "What is the approximate population of Lesotho?",
    correctAnswer: "≈ 2.3 million",
    distractors: ["≈ 5 million", "≈ 800,000", "≈ 8 million"],
  },
  // ── Area Questions (181-260) ──────────────────────────────────────────────
  {
    country: "Russia",
    statType: "area",
    question: "What is the approximate area of Russia, the world's largest country?",
    correctAnswer: "≈ 17.1 million km²",
    distractors: ["≈ 12.5 million km²", "≈ 22.0 million km²", "≈ 9.8 million km²"],
  },
  {
    country: "Canada",
    statType: "area",
    question: "What is the approximate area of Canada?",
    correctAnswer: "≈ 10.0 million km²",
    distractors: ["≈ 7.5 million km²", "≈ 13.0 million km²", "≈ 5.5 million km²"],
  },
  {
    country: "United States",
    statType: "area",
    question: "What is the approximate area of the United States?",
    correctAnswer: "≈ 9.8 million km²",
    distractors: ["≈ 7.5 million km²", "≈ 12.5 million km²", "≈ 5.0 million km²"],
  },
  {
    country: "China",
    statType: "area",
    question: "What is the approximate area of China?",
    correctAnswer: "≈ 9.6 million km²",
    distractors: ["≈ 7.0 million km²", "≈ 12.0 million km²", "≈ 5.5 million km²"],
  },
  {
    country: "Brazil",
    statType: "area",
    question: "What is the approximate area of Brazil?",
    correctAnswer: "≈ 8.5 million km²",
    distractors: ["≈ 6.0 million km²", "≈ 11.0 million km²", "≈ 4.5 million km²"],
  },
  {
    country: "Australia",
    statType: "area",
    question: "What is the approximate area of Australia?",
    correctAnswer: "≈ 7.7 million km²",
    distractors: ["≈ 5.5 million km²", "≈ 10.0 million km²", "≈ 3.5 million km²"],
  },
  {
    country: "India",
    statType: "area",
    question: "What is the approximate area of India?",
    correctAnswer: "≈ 3.3 million km²",
    distractors: ["≈ 2.0 million km²", "≈ 5.0 million km²", "≈ 1.5 million km²"],
  },
  {
    country: "Argentina",
    statType: "area",
    question: "What is the approximate area of Argentina?",
    correctAnswer: "≈ 2.8 million km²",
    distractors: ["≈ 1.8 million km²", "≈ 4.0 million km²", "≈ 1.2 million km²"],
  },
  {
    country: "Kazakhstan",
    statType: "area",
    question: "What is the approximate area of Kazakhstan?",
    correctAnswer: "≈ 2.7 million km²",
    distractors: ["≈ 1.5 million km²", "≈ 4.0 million km²", "≈ 1.0 million km²"],
  },
  {
    country: "Algeria",
    statType: "area",
    question: "What is the approximate area of Algeria, Africa's largest country?",
    correctAnswer: "≈ 2.4 million km²",
    distractors: ["≈ 1.5 million km²", "≈ 3.5 million km²", "≈ 800,000 km²"],
  },
  {
    country: "DR Congo",
    statType: "area",
    question: "What is the approximate area of the Democratic Republic of the Congo?",
    correctAnswer: "≈ 2.3 million km²",
    distractors: ["≈ 1.4 million km²", "≈ 3.5 million km²", "≈ 800,000 km²"],
  },
  {
    country: "Saudi Arabia",
    statType: "area",
    question: "What is the approximate area of Saudi Arabia?",
    correctAnswer: "≈ 2.15 million km²",
    distractors: ["≈ 1.2 million km²", "≈ 3.0 million km²", "≈ 800,000 km²"],
  },
  {
    country: "Mexico",
    statType: "area",
    question: "What is the approximate area of Mexico?",
    correctAnswer: "≈ 1.96 million km²",
    distractors: ["≈ 1.2 million km²", "≈ 3.0 million km²", "≈ 750,000 km²"],
  },
  {
    country: "Indonesia",
    statType: "area",
    question: "What is the approximate area of Indonesia?",
    correctAnswer: "≈ 1.9 million km²",
    distractors: ["≈ 1.2 million km²", "≈ 2.8 million km²", "≈ 700,000 km²"],
  },
  {
    country: "Mongolia",
    statType: "area",
    question: "What is the approximate area of Mongolia?",
    correctAnswer: "≈ 1.56 million km²",
    distractors: ["≈ 900,000 km²", "≈ 2.2 million km²", "≈ 500,000 km²"],
  },
  {
    country: "Libya",
    statType: "area",
    question: "What is the approximate area of Libya?",
    correctAnswer: "≈ 1.76 million km²",
    distractors: ["≈ 1.0 million km²", "≈ 2.5 million km²", "≈ 600,000 km²"],
  },
  {
    country: "Iran",
    statType: "area",
    question: "What is the approximate area of Iran?",
    correctAnswer: "≈ 1.65 million km²",
    distractors: ["≈ 1.0 million km²", "≈ 2.3 million km²", "≈ 600,000 km²"],
  },
  {
    country: "Peru",
    statType: "area",
    question: "What is the approximate area of Peru?",
    correctAnswer: "≈ 1.29 million km²",
    distractors: ["≈ 800,000 km²", "≈ 1.8 million km²", "≈ 500,000 km²"],
  },
  {
    country: "Chad",
    statType: "area",
    question: "What is the approximate area of Chad?",
    correctAnswer: "≈ 1.28 million km²",
    distractors: ["≈ 800,000 km²", "≈ 1.8 million km²", "≈ 450,000 km²"],
  },
  {
    country: "Niger",
    statType: "area",
    question: "What is the approximate area of Niger?",
    correctAnswer: "≈ 1.27 million km²",
    distractors: ["≈ 800,000 km²", "≈ 1.8 million km²", "≈ 450,000 km²"],
  },
  {
    country: "Mali",
    statType: "area",
    question: "What is the approximate area of Mali?",
    correctAnswer: "≈ 1.24 million km²",
    distractors: ["≈ 750,000 km²", "≈ 1.8 million km²", "≈ 450,000 km²"],
  },
  {
    country: "South Africa",
    statType: "area",
    question: "What is the approximate area of South Africa?",
    correctAnswer: "≈ 1.22 million km²",
    distractors: ["≈ 750,000 km²", "≈ 1.8 million km²", "≈ 450,000 km²"],
  },
  {
    country: "Ethiopia",
    statType: "area",
    question: "What is the approximate area of Ethiopia?",
    correctAnswer: "≈ 1.1 million km²",
    distractors: ["≈ 650,000 km²", "≈ 1.6 million km²", "≈ 400,000 km²"],
  },
  {
    country: "Colombia",
    statType: "area",
    question: "What is the approximate area of Colombia?",
    correctAnswer: "≈ 1.14 million km²",
    distractors: ["≈ 700,000 km²", "≈ 1.6 million km²", "≈ 400,000 km²"],
  },
  {
    country: "Tanzania",
    statType: "area",
    question: "What is the approximate area of Tanzania?",
    correctAnswer: "≈ 945,000 km²",
    distractors: ["≈ 600,000 km²", "≈ 1.4 million km²", "≈ 350,000 km²"],
  },
  {
    country: "Namibia",
    statType: "area",
    question: "What is the approximate area of Namibia?",
    correctAnswer: "≈ 825,000 km²",
    distractors: ["≈ 500,000 km²", "≈ 1.2 million km²", "≈ 300,000 km²"],
  },
  {
    country: "Mozambique",
    statType: "area",
    question: "What is the approximate area of Mozambique?",
    correctAnswer: "≈ 801,000 km²",
    distractors: ["≈ 500,000 km²", "≈ 1.2 million km²", "≈ 300,000 km²"],
  },
  {
    country: "Turkey",
    statType: "area",
    question: "What is the approximate area of Turkey?",
    correctAnswer: "≈ 783,000 km²",
    distractors: ["≈ 500,000 km²", "≈ 1.1 million km²", "≈ 300,000 km²"],
  },
  {
    country: "Zambia",
    statType: "area",
    question: "What is the approximate area of Zambia?",
    correctAnswer: "≈ 753,000 km²",
    distractors: ["≈ 450,000 km²", "≈ 1.1 million km²", "≈ 250,000 km²"],
  },
  {
    country: "Myanmar",
    statType: "area",
    question: "What is the approximate area of Myanmar?",
    correctAnswer: "≈ 677,000 km²",
    distractors: ["≈ 400,000 km²", "≈ 950,000 km²", "≈ 250,000 km²"],
  },
  {
    country: "France",
    statType: "area",
    question: "What is the approximate area of metropolitan France?",
    correctAnswer: "≈ 551,000 km² (metropolitan)",
    distractors: ["≈ 350,000 km²", "≈ 800,000 km²", "≈ 200,000 km²"],
  },
  {
    country: "Madagascar",
    statType: "area",
    question: "What is the approximate area of Madagascar?",
    correctAnswer: "≈ 587,000 km²",
    distractors: ["≈ 350,000 km²", "≈ 850,000 km²", "≈ 200,000 km²"],
  },
  {
    country: "Japan",
    statType: "area",
    question: "What is the approximate area of Japan?",
    correctAnswer: "≈ 378,000 km²",
    distractors: ["≈ 220,000 km²", "≈ 550,000 km²", "≈ 150,000 km²"],
  },
  {
    country: "Germany",
    statType: "area",
    question: "What is the approximate area of Germany?",
    correctAnswer: "≈ 357,000 km²",
    distractors: ["≈ 220,000 km²", "≈ 500,000 km²", "≈ 150,000 km²"],
  },
  {
    country: "Philippines",
    statType: "area",
    question: "What is the approximate area of the Philippines?",
    correctAnswer: "≈ 300,000 km²",
    distractors: ["≈ 180,000 km²", "≈ 450,000 km²", "≈ 120,000 km²"],
  },
  {
    country: "Italy",
    statType: "area",
    question: "What is the approximate area of Italy?",
    correctAnswer: "≈ 301,000 km²",
    distractors: ["≈ 180,000 km²", "≈ 450,000 km²", "≈ 120,000 km²"],
  },
  {
    country: "United Kingdom",
    statType: "area",
    question: "What is the approximate area of the United Kingdom?",
    correctAnswer: "≈ 243,000 km²",
    distractors: ["≈ 150,000 km²", "≈ 360,000 km²", "≈ 100,000 km²"],
  },
  {
    country: "New Zealand",
    statType: "area",
    question: "What is the approximate area of New Zealand?",
    correctAnswer: "≈ 268,000 km²",
    distractors: ["≈ 160,000 km²", "≈ 400,000 km²", "≈ 100,000 km²"],
  },
  {
    country: "Nepal",
    statType: "area",
    question: "What is the approximate area of Nepal?",
    correctAnswer: "≈ 147,000 km²",
    distractors: ["≈ 90,000 km²", "≈ 220,000 km²", "≈ 60,000 km²"],
  },
  {
    country: "Bangladesh",
    statType: "area",
    question: "What is the approximate area of Bangladesh?",
    correctAnswer: "≈ 148,000 km²",
    distractors: ["≈ 90,000 km²", "≈ 220,000 km²", "≈ 55,000 km²"],
  },
  {
    country: "Greece",
    statType: "area",
    question: "What is the approximate area of Greece?",
    correctAnswer: "≈ 132,000 km²",
    distractors: ["≈ 80,000 km²", "≈ 200,000 km²", "≈ 55,000 km²"],
  },
  {
    country: "Iceland",
    statType: "area",
    question: "What is the approximate area of Iceland?",
    correctAnswer: "≈ 103,000 km²",
    distractors: ["≈ 60,000 km²", "≈ 150,000 km²", "≈ 40,000 km²"],
  },
  {
    country: "South Korea",
    statType: "area",
    question: "What is the approximate area of South Korea?",
    correctAnswer: "≈ 100,000 km²",
    distractors: ["≈ 60,000 km²", "≈ 150,000 km²", "≈ 40,000 km²"],
  },
  {
    country: "Portugal",
    statType: "area",
    question: "What is the approximate area of Portugal?",
    correctAnswer: "≈ 92,000 km²",
    distractors: ["≈ 55,000 km²", "≈ 135,000 km²", "≈ 35,000 km²"],
  },
  {
    country: "Ireland",
    statType: "area",
    question: "What is the approximate area of Ireland (Republic)?",
    correctAnswer: "≈ 70,000 km²",
    distractors: ["≈ 40,000 km²", "≈ 105,000 km²", "≈ 25,000 km²"],
  },
  {
    country: "Sri Lanka",
    statType: "area",
    question: "What is the approximate area of Sri Lanka?",
    correctAnswer: "≈ 65,600 km²",
    distractors: ["≈ 40,000 km²", "≈ 100,000 km²", "≈ 25,000 km²"],
  },
  {
    country: "Switzerland",
    statType: "area",
    question: "What is the approximate area of Switzerland?",
    correctAnswer: "≈ 41,000 km²",
    distractors: ["≈ 25,000 km²", "≈ 60,000 km²", "≈ 15,000 km²"],
  },
  {
    country: "Netherlands",
    statType: "area",
    question: "What is the approximate area of the Netherlands?",
    correctAnswer: "≈ 41,500 km²",
    distractors: ["≈ 25,000 km²", "≈ 62,000 km²", "≈ 15,000 km²"],
  },
  {
    country: "Belgium",
    statType: "area",
    question: "What is the approximate area of Belgium?",
    correctAnswer: "≈ 30,500 km²",
    distractors: ["≈ 18,000 km²", "≈ 45,000 km²", "≈ 12,000 km²"],
  },
  {
    country: "Israel",
    statType: "area",
    question: "What is the approximate area of Israel (excluding occupied territories)?",
    correctAnswer: "≈ 22,000 km²",
    distractors: ["≈ 12,000 km²", "≈ 35,000 km²", "≈ 8,000 km²"],
  },
  {
    country: "Slovenia",
    statType: "area",
    question: "What is the approximate area of Slovenia?",
    correctAnswer: "≈ 20,300 km²",
    distractors: ["≈ 12,000 km²", "≈ 32,000 km²", "≈ 8,000 km²"],
  },
  {
    country: "Kuwait",
    statType: "area",
    question: "What is the approximate area of Kuwait?",
    correctAnswer: "≈ 17,800 km²",
    distractors: ["≈ 10,000 km²", "≈ 28,000 km²", "≈ 5,000 km²"],
  },
  {
    country: "Eswatini",
    statType: "area",
    question: "What is the approximate area of Eswatini?",
    correctAnswer: "≈ 17,400 km²",
    distractors: ["≈ 10,000 km²", "≈ 28,000 km²", "≈ 5,000 km²"],
  },
  {
    country: "Timor-Leste",
    statType: "area",
    question: "What is the approximate area of Timor-Leste?",
    correctAnswer: "≈ 14,900 km²",
    distractors: ["≈ 8,000 km²", "≈ 25,000 km²", "≈ 4,000 km²"],
  },
  {
    country: "Montenegro",
    statType: "area",
    question: "What is the approximate area of Montenegro?",
    correctAnswer: "≈ 13,800 km²",
    distractors: ["≈ 8,000 km²", "≈ 22,000 km²", "≈ 4,000 km²"],
  },
  {
    country: "Bahamas",
    statType: "area",
    question: "What is the approximate land area of the Bahamas?",
    correctAnswer: "≈ 13,900 km²",
    distractors: ["≈ 7,000 km²", "≈ 25,000 km²", "≈ 3,000 km²"],
  },
  {
    country: "Qatar",
    statType: "area",
    question: "What is the approximate area of Qatar?",
    correctAnswer: "≈ 11,600 km²",
    distractors: ["≈ 6,000 km²", "≈ 20,000 km²", "≈ 3,000 km²"],
  },
  {
    country: "The Gambia",
    statType: "area",
    question: "What is the approximate area of The Gambia?",
    correctAnswer: "≈ 11,300 km²",
    distractors: ["≈ 6,000 km²", "≈ 20,000 km²", "≈ 3,000 km²"],
  },
  {
    country: "Jamaica",
    statType: "area",
    question: "What is the approximate area of Jamaica?",
    correctAnswer: "≈ 10,990 km²",
    distractors: ["≈ 6,000 km²", "≈ 18,000 km²", "≈ 3,000 km²"],
  },
  {
    country: "Lebanon",
    statType: "area",
    question: "What is the approximate area of Lebanon?",
    correctAnswer: "≈ 10,450 km²",
    distractors: ["≈ 6,000 km²", "≈ 18,000 km²", "≈ 3,000 km²"],
  },
  {
    country: "Cyprus",
    statType: "area",
    question: "What is the approximate area of Cyprus?",
    correctAnswer: "≈ 9,250 km²",
    distractors: ["≈ 5,000 km²", "≈ 15,000 km²", "≈ 2,500 km²"],
  },
  {
    country: "Brunei",
    statType: "area",
    question: "What is the approximate area of Brunei?",
    correctAnswer: "≈ 5,770 km²",
    distractors: ["≈ 2,500 km²", "≈ 10,000 km²", "≈ 1,000 km²"],
  },
  {
    country: "Luxembourg",
    statType: "area",
    question: "What is the approximate area of Luxembourg?",
    correctAnswer: "≈ 2,590 km²",
    distractors: ["≈ 1,200 km²", "≈ 5,000 km²", "≈ 600 km²"],
  },
  {
    country: "Mauritius",
    statType: "area",
    question: "What is the approximate area of Mauritius?",
    correctAnswer: "≈ 2,040 km²",
    distractors: ["≈ 1,000 km²", "≈ 4,000 km²", "≈ 500 km²"],
  },
  {
    country: "Comoros",
    statType: "area",
    question: "What is the approximate area of the Comoros?",
    correctAnswer: "≈ 1,862 km²",
    distractors: ["≈ 900 km²", "≈ 3,500 km²", "≈ 400 km²"],
  },
  {
    country: "Singapore",
    statType: "area",
    question: "What is the approximate area of Singapore?",
    correctAnswer: "≈ 733 km²",
    distractors: ["≈ 350 km²", "≈ 1,200 km²", "≈ 150 km²"],
  },
  {
    country: "Bahrain",
    statType: "area",
    question: "What is the approximate area of Bahrain?",
    correctAnswer: "≈ 780 km²",
    distractors: ["≈ 350 km²", "≈ 1,400 km²", "≈ 150 km²"],
  },
  {
    country: "Maldives",
    statType: "area",
    question: "What is the approximate land area of the Maldives?",
    correctAnswer: "≈ 298 km²",
    distractors: ["≈ 600 km²", "≈ 150 km²", "≈ 1,200 km²"],
  },
  {
    country: "Malta",
    statType: "area",
    question: "What is the approximate area of Malta?",
    correctAnswer: "≈ 316 km²",
    distractors: ["≈ 150 km²", "≈ 600 km²", "≈ 50 km²"],
  },
  {
    country: "Liechtenstein",
    statType: "area",
    question: "What is the approximate area of Liechtenstein?",
    correctAnswer: "≈ 160 km²",
    distractors: ["≈ 80 km²", "≈ 310 km²", "≈ 25 km²"],
  },
  {
    country: "San Marino",
    statType: "area",
    question: "What is the approximate area of San Marino?",
    correctAnswer: "≈ 61 km²",
    distractors: ["≈ 30 km²", "≈ 120 km²", "≈ 10 km²"],
  },
  {
    country: "Monaco",
    statType: "area",
    question: "What is the approximate area of Monaco?",
    correctAnswer: "≈ 2.02 km²",
    distractors: ["≈ 5 km²", "≈ 0.5 km²", "≈ 10 km²"],
  },
  {
    country: "Vatican City",
    statType: "area",
    question: "What is the approximate area of Vatican City?",
    correctAnswer: "≈ 0.44 km²",
    distractors: ["≈ 2 km²", "≈ 0.1 km²", "≈ 5 km²"],
  },
  // ── Comparative & Miscellaneous Geography (261-292) ───────────────────────
  {
    country: "Greenland",
    statType: "area",
    question: "What is the approximate area of Greenland, the world's largest island?",
    correctAnswer: "≈ 2.17 million km²",
    distractors: ["≈ 1.2 million km²", "≈ 3.5 million km²", "≈ 850,000 km²"],
  },
  {
    country: "Antarctica",
    statType: "area",
    question: "What is the approximate area of Antarctica?",
    correctAnswer: "≈ 14.0 million km²",
    distractors: ["≈ 8.0 million km²", "≈ 20.0 million km²", "≈ 5.0 million km²"],
  },
  {
    country: "Papua New Guinea",
    statType: "area",
    question: "What is the approximate area of Papua New Guinea?",
    correctAnswer: "≈ 463,000 km²",
    distractors: ["≈ 280,000 km²", "≈ 650,000 km²", "≈ 180,000 km²"],
  },
  {
    country: "Norway",
    statType: "area",
    question: "What is the approximate area of Norway (mainland)?",
    correctAnswer: "≈ 324,000 km²",
    distractors: ["≈ 200,000 km²", "≈ 500,000 km²", "≈ 130,000 km²"],
  },
  {
    country: "Sweden",
    statType: "area",
    question: "What is the approximate area of Sweden?",
    correctAnswer: "≈ 450,000 km²",
    distractors: ["≈ 280,000 km²", "≈ 650,000 km²", "≈ 180,000 km²"],
  },
  {
    country: "Finland",
    statType: "area",
    question: "What is the approximate area of Finland?",
    correctAnswer: "≈ 338,000 km²",
    distractors: ["≈ 200,000 km²", "≈ 500,000 km²", "≈ 130,000 km²"],
  },
  {
    country: "Poland",
    statType: "area",
    question: "What is the approximate area of Poland?",
    correctAnswer: "≈ 313,000 km²",
    distractors: ["≈ 190,000 km²", "≈ 460,000 km²", "≈ 130,000 km²"],
  },
  {
    country: "Romania",
    statType: "area",
    question: "What is the approximate area of Romania?",
    correctAnswer: "≈ 238,000 km²",
    distractors: ["≈ 140,000 km²", "≈ 360,000 km²", "≈ 100,000 km²"],
  },
  {
    country: "Laos",
    statType: "area",
    question: "What is the approximate area of Laos?",
    correctAnswer: "≈ 237,000 km²",
    distractors: ["≈ 140,000 km²", "≈ 350,000 km²", "≈ 100,000 km²"],
  },
  {
    country: "Ghana",
    statType: "area",
    question: "What is the approximate area of Ghana?",
    correctAnswer: "≈ 239,000 km²",
    distractors: ["≈ 140,000 km²", "≈ 360,000 km²", "≈ 100,000 km²"],
  },
  {
    country: "Senegal",
    statType: "area",
    question: "What is the approximate area of Senegal?",
    correctAnswer: "≈ 197,000 km²",
    distractors: ["≈ 120,000 km²", "≈ 300,000 km²", "≈ 80,000 km²"],
  },
  {
    country: "Cambodia",
    statType: "area",
    question: "What is the approximate area of Cambodia?",
    correctAnswer: "≈ 181,000 km²",
    distractors: ["≈ 110,000 km²", "≈ 270,000 km²", "≈ 75,000 km²"],
  },
  {
    country: "Tunisia",
    statType: "area",
    question: "What is the approximate area of Tunisia?",
    correctAnswer: "≈ 164,000 km²",
    distractors: ["≈ 100,000 km²", "≈ 250,000 km²", "≈ 65,000 km²"],
  },
  {
    country: "Suriname",
    statType: "area",
    question: "What is the approximate area of Suriname?",
    correctAnswer: "≈ 164,000 km²",
    distractors: ["≈ 100,000 km²", "≈ 250,000 km²", "≈ 60,000 km²"],
  },
  {
    country: "North Korea",
    statType: "population",
    question: "What is the approximate population of North Korea?",
    correctAnswer: "≈ 26 million",
    distractors: ["≈ 15 million", "≈ 40 million", "≈ 10 million"],
  },
  {
    country: "Cuba",
    statType: "population",
    question: "What is the approximate population of Cuba?",
    correctAnswer: "≈ 11 million",
    distractors: ["≈ 6 million", "≈ 18 million", "≈ 25 million"],
  },
  {
    country: "Greece",
    statType: "population",
    question: "What is the approximate population of Greece?",
    correctAnswer: "≈ 10.4 million",
    distractors: ["≈ 7 million", "≈ 14 million", "≈ 20 million"],
  },
  {
    country: "Portugal",
    statType: "population",
    question: "What is the approximate population of Portugal?",
    correctAnswer: "≈ 10.3 million",
    distractors: ["≈ 7 million", "≈ 14 million", "≈ 20 million"],
  },
  {
    country: "Czech Republic",
    statType: "population",
    question: "What is the approximate population of the Czech Republic?",
    correctAnswer: "≈ 10.8 million",
    distractors: ["≈ 7 million", "≈ 15 million", "≈ 20 million"],
  },
  {
    country: "Sweden",
    statType: "population",
    question: "What is the approximate population of Sweden?",
    correctAnswer: "≈ 10.5 million",
    distractors: ["≈ 7 million", "≈ 14 million", "≈ 20 million"],
  },
  {
    country: "Hungary",
    statType: "population",
    question: "What is the approximate population of Hungary?",
    correctAnswer: "≈ 9.7 million",
    distractors: ["≈ 6 million", "≈ 14 million", "≈ 18 million"],
  },
  {
    country: "Jordan",
    statType: "population",
    question: "What is the approximate population of Jordan?",
    correctAnswer: "≈ 11.5 million",
    distractors: ["≈ 7 million", "≈ 16 million", "≈ 4 million"],
  },
  {
    country: "Bolivia",
    statType: "area",
    question: "What is the approximate area of Bolivia?",
    correctAnswer: "≈ 1.1 million km²",
    distractors: ["≈ 650,000 km²", "≈ 1.6 million km²", "≈ 400,000 km²"],
  },
  {
    country: "Egypt",
    statType: "area",
    question: "What is the approximate area of Egypt?",
    correctAnswer: "≈ 1.0 million km²",
    distractors: ["≈ 600,000 km²", "≈ 1.5 million km²", "≈ 350,000 km²"],
  },
  {
    country: "Ukraine",
    statType: "area",
    question: "What is the approximate area of Ukraine?",
    correctAnswer: "≈ 604,000 km²",
    distractors: ["≈ 380,000 km²", "≈ 850,000 km²", "≈ 250,000 km²"],
  },
  {
    country: "Botswana",
    statType: "area",
    question: "What is the approximate area of Botswana?",
    correctAnswer: "≈ 582,000 km²",
    distractors: ["≈ 350,000 km²", "≈ 830,000 km²", "≈ 220,000 km²"],
  },
  {
    country: "Kenya",
    statType: "area",
    question: "What is the approximate area of Kenya?",
    correctAnswer: "≈ 580,000 km²",
    distractors: ["≈ 350,000 km²", "≈ 830,000 km²", "≈ 220,000 km²"],
  },
  {
    country: "Thailand",
    statType: "area",
    question: "What is the approximate area of Thailand?",
    correctAnswer: "≈ 513,000 km²",
    distractors: ["≈ 310,000 km²", "≈ 740,000 km²", "≈ 200,000 km²"],
  },
  {
    country: "Spain",
    statType: "area",
    question: "What is the approximate area of Spain?",
    correctAnswer: "≈ 506,000 km²",
    distractors: ["≈ 310,000 km²", "≈ 730,000 km²", "≈ 200,000 km²"],
  },
  {
    country: "Nauru",
    statType: "area",
    question: "What is the approximate area of Nauru, one of the world's smallest countries?",
    correctAnswer: "≈ 21 km²",
    distractors: ["≈ 50 km²", "≈ 8 km²", "≈ 100 km²"],
  },
  {
    country: "Tuvalu",
    statType: "area",
    question: "What is the approximate land area of Tuvalu?",
    correctAnswer: "≈ 26 km²",
    distractors: ["≈ 60 km²", "≈ 10 km²", "≈ 120 km²"],
  },
  {
    country: "Marshall Islands",
    statType: "area",
    question: "What is the approximate land area of the Marshall Islands?",
    correctAnswer: "≈ 181 km²",
    distractors: ["≈ 80 km²", "≈ 400 km²", "≈ 30 km²"],
  },
  {
    country: "Andorra",
    statType: "area",
    question: "What is the approximate area of Andorra?",
    correctAnswer: "≈ 468 km²",
    distractors: ["≈ 200 km²", "≈ 800 km²", "≈ 100 km²"],
  },
  {
    country: "Palau",
    statType: "area",
    question: "What is the approximate land area of Palau?",
    correctAnswer: "≈ 459 km²",
    distractors: ["≈ 200 km²", "≈ 800 km²", "≈ 100 km²"],
  },
  {
    country: "Seychelles",
    statType: "area",
    question: "What is the approximate land area of Seychelles?",
    correctAnswer: "≈ 459 km²",
    distractors: ["≈ 200 km²", "≈ 800 km²", "≈ 50 km²"],
  },
  {
    country: "Kiribati",
    statType: "area",
    question: "What is the approximate land area of Kiribati?",
    correctAnswer: "≈ 811 km²",
    distractors: ["≈ 400 km²", "≈ 1,500 km²", "≈ 200 km²"],
  },
  {
    country: "Tonga",
    statType: "area",
    question: "What is the approximate land area of Tonga?",
    correctAnswer: "≈ 747 km²",
    distractors: ["≈ 350 km²", "≈ 1,200 km²", "≈ 150 km²"],
  },
  {
    country: "Micronesia",
    statType: "area",
    question: "What is the approximate land area of the Federated States of Micronesia?",
    correctAnswer: "≈ 702 km²",
    distractors: ["≈ 300 km²", "≈ 1,200 km²", "≈ 150 km²"],
  },
  {
    country: "Samoa",
    statType: "area",
    question: "What is the approximate area of Samoa?",
    correctAnswer: "≈ 2,842 km²",
    distractors: ["≈ 1,400 km²", "≈ 5,000 km²", "≈ 700 km²"],
  },
  {
    country: "Solomon Islands",
    statType: "area",
    question: "What is the approximate area of the Solomon Islands?",
    correctAnswer: "≈ 28,900 km²",
    distractors: ["≈ 15,000 km²", "≈ 50,000 km²", "≈ 8,000 km²"],
  },
  {
    country: "Vanuatu",
    statType: "area",
    question: "What is the approximate area of Vanuatu?",
    correctAnswer: "≈ 12,190 km²",
    distractors: ["≈ 6,000 km²", "≈ 22,000 km²", "≈ 3,000 km²"],
  },
  {
    country: "Taiwan",
    statType: "population",
    question: "What is the approximate population of Taiwan?",
    correctAnswer: "≈ 23.5 million",
    distractors: ["≈ 15 million", "≈ 35 million", "≈ 10 million"],
  },
  {
    country: "Romania",
    statType: "population",
    question: "What is the approximate population of Romania?",
    correctAnswer: "≈ 19 million",
    distractors: ["≈ 13 million", "≈ 26 million", "≈ 8 million"],
  },
  {
    country: "Chile",
    statType: "population",
    question: "What is the approximate population of Chile?",
    correctAnswer: "≈ 19.5 million",
    distractors: ["≈ 13 million", "≈ 27 million", "≈ 8 million"],
  },
  {
    country: "Kazakhstan",
    statType: "population",
    question: "What is the approximate population of Kazakhstan?",
    correctAnswer: "≈ 20 million",
    distractors: ["≈ 12 million", "≈ 30 million", "≈ 7 million"],
  },
  {
    country: "Guatemala",
    statType: "population",
    question: "What is the approximate population of Guatemala?",
    correctAnswer: "≈ 18 million",
    distractors: ["≈ 10 million", "≈ 25 million", "≈ 7 million"],
  },
  {
    country: "Ecuador",
    statType: "population",
    question: "What is the approximate population of Ecuador?",
    correctAnswer: "≈ 18 million",
    distractors: ["≈ 11 million", "≈ 26 million", "≈ 7 million"],
  },
  {
    country: "Netherlands",
    statType: "population",
    question: "What is the approximate population of the Netherlands?",
    correctAnswer: "≈ 17.7 million",
    distractors: ["≈ 12 million", "≈ 24 million", "≈ 8 million"],
  },
  {
    country: "Cambodia",
    statType: "population",
    question: "What is the approximate population of Cambodia?",
    correctAnswer: "≈ 17 million",
    distractors: ["≈ 10 million", "≈ 25 million", "≈ 6 million"],
  },
  {
    country: "Senegal",
    statType: "population",
    question: "What is the approximate population of Senegal?",
    correctAnswer: "≈ 18 million",
    distractors: ["≈ 10 million", "≈ 26 million", "≈ 6 million"],
  },
  {
    country: "Singapore",
    statType: "population",
    question: "What is the approximate population of Singapore?",
    correctAnswer: "≈ 5.9 million",
    distractors: ["≈ 3 million", "≈ 10 million", "≈ 15 million"],
  },
  {
    country: "Norway",
    statType: "population",
    question: "What is the approximate population of Norway?",
    correctAnswer: "≈ 5.5 million",
    distractors: ["≈ 3.5 million", "≈ 8 million", "≈ 12 million"],
  },
  {
    country: "Finland",
    statType: "population",
    question: "What is the approximate population of Finland?",
    correctAnswer: "≈ 5.6 million",
    distractors: ["≈ 3.5 million", "≈ 8 million", "≈ 12 million"],
  },
  {
    country: "New Zealand",
    statType: "population",
    question: "What is the approximate population of New Zealand?",
    correctAnswer: "≈ 5.2 million",
    distractors: ["≈ 3 million", "≈ 8 million", "≈ 12 million"],
  },
  {
    country: "Costa Rica",
    statType: "capital",
    question: "What is the capital of Costa Rica?",
    correctAnswer: "San José",
    distractors: ["Limón", "Alajuela", "Cartago"],
  },
  {
    country: "Haiti",
    statType: "capital",
    question: "What is the capital of Haiti?",
    correctAnswer: "Port-au-Prince",
    distractors: ["Cap-Haïtien", "Gonaïves", "Les Cayes"],
  },
  {
    country: "Andorra",
    statType: "population",
    question: "What is the approximate population of Andorra?",
    correctAnswer: "≈ 80,000",
    distractors: ["≈ 200,000", "≈ 30,000", "≈ 500,000"],
  },
];
