export interface HistoricalEvent {
  event: string;
  year: number;
}

// ─── Extended Historical Events (468 entries) ───────────────────────────────
// Spans ancient through modern eras across all world regions.

export const HISTORICAL_EVENTS_EXT: HistoricalEvent[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // ANCIENT ERA (before 500 CE)
  // ══════════════════════════════════════════════════════════════════════════

  // ── Ancient Near East & Egypt ─────────────────────────────────────────────
  { event: "Unification of Upper and Lower Egypt under Pharaoh Narmer", year: -3100 },
  { event: "Construction of the Great Pyramid of Giza begins under Pharaoh Khufu", year: -2560 },
  { event: "Code of Ur-Nammu, the oldest surviving legal code, promulgated in Sumer", year: -2100 },
  { event: "Code of Hammurabi enacted in Babylon", year: -1754 },
  { event: "Battle of Kadesh between Egypt and the Hittite Empire", year: -1274 },
  { event: "Collapse of the Bronze Age civilizations in the Eastern Mediterranean", year: -1177 },
  { event: "Phoenicians establish the city of Carthage in North Africa", year: -814 },
  { event: "Fall of Nineveh and the collapse of the Assyrian Empire", year: -612 },
  { event: "Cyrus the Great conquers Babylon, founding the Achaemenid Persian Empire", year: -539 },
  { event: "Construction of the Royal Road by the Persian Empire", year: -500 },
  { event: "Battle of Thermopylae between Greece and Persia", year: -480 },
  { event: "Battle of Salamis: Greek naval victory over Persia", year: -480 },
  { event: "Battle of Marathon: Athenian victory over the Persian Empire", year: -490 },
  { event: "Construction of the Parthenon begins in Athens", year: -447 },
  { event: "Herodotus writes the Histories, the first major Western historical work", year: -440 },
  { event: "Peloponnesian War begins between Athens and Sparta", year: -431 },
  { event: "Socrates is sentenced to death by drinking hemlock in Athens", year: -399 },
  { event: "Plato founds the Academy in Athens", year: -387 },
  { event: "Alexander the Great defeats Darius III at the Battle of Gaugamela", year: -331 },
  { event: "Alexander the Great founds the city of Alexandria in Egypt", year: -331 },
  { event: "Construction of the Library of Alexandria begins", year: -295 },
  { event: "Euclid publishes Elements, foundational text of geometry", year: -300 },
  { event: "Archimedes discovers the principle of buoyancy in Syracuse", year: -250 },
  { event: "Eratosthenes calculates the circumference of the Earth", year: -240 },
  { event: "Construction of the Colossus of Rhodes completed", year: -280 },
  { event: "First Punic War begins between Rome and Carthage", year: -264 },
  { event: "Hannibal crosses the Alps to invade Italy during the Second Punic War", year: -218 },
  { event: "Battle of Cannae: Hannibal defeats Rome in a devastating engagement", year: -216 },
  { event: "Battle of Zama: Scipio Africanus defeats Hannibal, ending the Second Punic War", year: -202 },
  { event: "Destruction of Carthage by Rome in the Third Punic War", year: -146 },
  { event: "Conquest of Corinth: Rome destroys the Greek city-state", year: -146 },

  // ── Ancient Asia ──────────────────────────────────────────────────────────
  { event: "Indus Valley Civilization reaches maturity at Mohenjo-daro", year: -2500 },
  { event: "Shang Dynasty established in China, earliest confirmed Chinese dynasty", year: -1600 },
  { event: "Zhou Dynasty overthrows the Shang Dynasty in China", year: -1046 },
  { event: "Composition of the Rigveda, oldest Hindu scripture, completed in India", year: -1200 },
  { event: "Siddhartha Gautama (the Buddha) attains enlightenment in Bodh Gaya", year: -528 },
  { event: "Mahavira, founder of Jainism, attains nirvana", year: -527 },
  { event: "Confucius begins teaching philosophy in the state of Lu, China", year: -500 },
  { event: "Sun Tzu writes The Art of War in ancient China", year: -500 },
  { event: "Chandragupta Maurya founds the Maurya Empire in India", year: -322 },
  { event: "Emperor Ashoka converts to Buddhism after the Battle of Kalinga", year: -261 },
  { event: "Qin Shi Huang unifies China and becomes the first Emperor", year: -221 },
  { event: "Construction of the Great Wall of China begins under Qin Shi Huang", year: -214 },
  { event: "Han Dynasty established in China under Liu Bang", year: -202 },
  { event: "Opening of the Silk Road trade routes connecting China to the West", year: -130 },
  { event: "Invention of paper by Cai Lun in Han Dynasty China", year: 105 },
  { event: "Zhang Heng invents the first seismoscope in China", year: 132 },
  { event: "Kushan Empire reaches its zenith under Emperor Kanishka in Central Asia", year: 127 },
  { event: "Three Kingdoms period begins in China after the fall of the Han Dynasty", year: 220 },
  { event: "Gupta Empire founded in India, beginning the Indian Golden Age", year: 320 },
  { event: "Aryabhata publishes Aryabhatiya, a seminal work of Indian mathematics", year: 499 },

  // ── Ancient Rome ──────────────────────────────────────────────────────────
  { event: "Traditional founding of Rome by Romulus", year: -753 },
  { event: "Establishment of the Roman Republic after the overthrow of the monarchy", year: -509 },
  { event: "The Twelve Tables, Rome's first written legal code, published", year: -450 },
  { event: "Julius Caesar crosses the Rubicon, triggering civil war in Rome", year: -49 },
  { event: "Assassination of Julius Caesar on the Ides of March", year: -44 },
  { event: "Battle of Actium: Octavian defeats Mark Antony and Cleopatra", year: -31 },
  { event: "Augustus becomes the first Roman Emperor, founding the Principate", year: -27 },
  { event: "Eruption of Mount Vesuvius buries Pompeii and Herculaneum", year: 79 },
  { event: "Construction of the Roman Colosseum completed under Emperor Titus", year: 80 },
  { event: "Trajan's Column erected in Rome celebrating victory in the Dacian Wars", year: 113 },
  { event: "Roman Empire reaches its maximum territorial extent under Trajan", year: 117 },
  { event: "Construction of Hadrian's Wall begins in Roman Britain", year: 122 },
  { event: "Emperor Diocletian divides the Roman Empire into East and West", year: 285 },
  { event: "Edict of Milan grants religious tolerance throughout the Roman Empire", year: 313 },
  { event: "Emperor Constantine founds Constantinople as the new Roman capital", year: 330 },
  { event: "Emperor Theodosius I makes Christianity the official religion of Rome", year: 380 },
  { event: "Sack of Rome by the Visigoths under Alaric I", year: 410 },
  { event: "Fall of the Western Roman Empire: Romulus Augustulus deposed", year: 476 },

  // ── Ancient Americas & Africa ─────────────────────────────────────────────
  { event: "Olmec civilization emerges in Mesoamerica", year: -1500 },
  { event: "Zapotec civilization develops writing at Monte Alban in Mesoamerica", year: -500 },
  { event: "Founding of the city of Teotihuacan in central Mexico", year: -100 },
  { event: "Nazca Lines created in the Peruvian desert", year: -200 },
  { event: "Kingdom of Aksum begins minting its own coinage in Ethiopia", year: 270 },
  { event: "Kingdom of Aksum converts to Christianity under King Ezana", year: 340 },
  { event: "Classic Maya civilization reaches its peak at Tikal", year: 400 },

  // ══════════════════════════════════════════════════════════════════════════
  // MEDIEVAL ERA (500–1500 CE)
  // ══════════════════════════════════════════════════════════════════════════

  // ── Early Medieval Europe ─────────────────────────────────────────────────
  { event: "Justinian I becomes Byzantine Emperor and begins reconquest of the West", year: 527 },
  { event: "Hagia Sophia completed in Constantinople under Justinian I", year: 537 },
  { event: "Plague of Justinian devastates the Byzantine Empire", year: 541 },
  { event: "Benedict of Nursia establishes the Benedictine monastic rule at Monte Cassino", year: 529 },
  { event: "Lombards invade and settle in Italy", year: 568 },
  { event: "Pope Gregory I sends Augustine of Canterbury to convert England", year: 597 },
  { event: "Battle of Tours: Charles Martel halts the Umayyad advance into Europe", year: 732 },
  { event: "Charlemagne crowned Holy Roman Emperor by Pope Leo III", year: 800 },
  { event: "Treaty of Verdun divides the Carolingian Empire into three kingdoms", year: 843 },
  { event: "Vikings under Rollo settle Normandy by treaty with the Frankish king", year: 911 },
  { event: "Otto I crowned Holy Roman Emperor, founding the medieval German empire", year: 962 },
  { event: "Erik the Red establishes the Norse settlement in Greenland", year: 985 },
  { event: "Leif Erikson reaches Vinland (North America)", year: 1000 },
  { event: "Great Schism: Christianity splits into Roman Catholic and Eastern Orthodox", year: 1054 },
  { event: "Battle of Hastings: William the Conqueror defeats Harold II of England", year: 1066 },
  { event: "Domesday Book completed, a survey of England ordered by William I", year: 1086 },

  // ── The Crusades & High Middle Ages ───────────────────────────────────────
  { event: "Pope Urban II calls the First Crusade at the Council of Clermont", year: 1095 },
  { event: "Crusaders capture Jerusalem during the First Crusade", year: 1099 },
  { event: "Knights Templar founded in Jerusalem", year: 1119 },
  { event: "Second Crusade launched after the fall of Edessa", year: 1147 },
  { event: "Saladin recaptures Jerusalem from the Crusaders", year: 1187 },
  { event: "Third Crusade: Richard the Lionheart negotiates access to Jerusalem", year: 1192 },
  { event: "Fourth Crusade sacks Constantinople instead of reaching the Holy Land", year: 1204 },
  { event: "Children's Crusade: thousands of young people attempt pilgrimage to the Holy Land", year: 1212 },
  { event: "Magna Carta signed by King John of England at Runnymede", year: 1215 },
  { event: "University of Paris receives its charter from Pope Innocent III", year: 1215 },
  { event: "Francis of Assisi founds the Franciscan Order", year: 1209 },
  { event: "Thomas Aquinas begins writing Summa Theologica", year: 1265 },
  { event: "Marco Polo arrives at the court of Kublai Khan in China", year: 1275 },
  { event: "First session of the English Model Parliament under Edward I", year: 1295 },
  { event: "Battle of Bannockburn: Scotland defeats England under Robert the Bruce", year: 1314 },

  // ── Late Medieval Europe ──────────────────────────────────────────────────
  { event: "Black Death arrives in Europe, killing roughly one-third of the population", year: 1347 },
  { event: "Hundred Years' War begins between England and France", year: 1337 },
  { event: "Battle of Crecy: English longbowmen defeat the French army", year: 1346 },
  { event: "Peasants' Revolt in England led by Wat Tyler", year: 1381 },
  { event: "Geoffrey Chaucer begins writing The Canterbury Tales", year: 1387 },
  { event: "Battle of Agincourt: Henry V of England defeats France", year: 1415 },
  { event: "Joan of Arc lifts the Siege of Orleans during the Hundred Years' War", year: 1429 },
  { event: "Joan of Arc burned at the stake in Rouen, France", year: 1431 },
  { event: "Johann Gutenberg prints the Gutenberg Bible using movable type", year: 1455 },
  { event: "Wars of the Roses begin in England between Lancaster and York", year: 1455 },
  { event: "Fall of Constantinople to the Ottoman Turks under Mehmed II", year: 1453 },
  { event: "Battle of Bosworth Field: Henry Tudor defeats Richard III", year: 1485 },
  { event: "Spanish Inquisition formally established by Ferdinand and Isabella", year: 1478 },
  { event: "Reconquista completed: Granada falls to Ferdinand and Isabella", year: 1492 },

  // ── Medieval Islamic World ────────────────────────────────────────────────
  { event: "Prophet Muhammad's Hijra from Mecca to Medina, start of the Islamic calendar", year: 622 },
  { event: "Battle of Badr: first major military victory of the Muslim community", year: 624 },
  { event: "Muslim conquest of Mecca by Prophet Muhammad", year: 630 },
  { event: "Battle of Yarmouk: Arab forces defeat the Byzantine Empire in Syria", year: 636 },
  { event: "Umayyad Caliphate established with Damascus as its capital", year: 661 },
  { event: "Umayyad forces cross the Strait of Gibraltar and conquer Iberia", year: 711 },
  { event: "Abbasid Caliphate established, replacing the Umayyads", year: 750 },
  { event: "Founding of Baghdad as the capital of the Abbasid Caliphate", year: 762 },
  { event: "Al-Khwarizmi publishes Al-Jabr, foundational text of algebra", year: 820 },
  { event: "House of Wisdom in Baghdad reaches its peak as a center of learning", year: 830 },
  { event: "Ibn Sina (Avicenna) completes The Canon of Medicine", year: 1025 },
  { event: "Al-Biruni writes Kitab al-Hind, a comprehensive study of Indian culture", year: 1030 },
  { event: "Omar Khayyam reforms the Persian calendar and writes the Rubaiyat", year: 1079 },
  { event: "Ibn Rushd (Averroes) writes commentaries on Aristotle in Cordoba", year: 1179 },
  { event: "Mongol siege and destruction of Baghdad, ending the Abbasid Caliphate", year: 1258 },
  { event: "Ibn Battuta begins his extensive travels across the Islamic world", year: 1325 },
  { event: "Ibn Khaldun writes the Muqaddimah, a pioneering work of historiography", year: 1377 },

  // ── Medieval Asia ─────────────────────────────────────────────────────────
  { event: "Sui Dynasty reunifies China after centuries of division", year: 589 },
  { event: "Tang Dynasty established in China, beginning a golden age", year: 618 },
  { event: "Battle of Talas between the Abbasid Caliphate and Tang Dynasty China", year: 751 },
  { event: "Heian period begins in Japan with the move of the capital to Kyoto", year: 794 },
  { event: "Lady Murasaki Shikibu writes The Tale of Genji in Japan", year: 1010 },
  { event: "Song Dynasty China invents movable-type printing", year: 1040 },
  { event: "First use of gunpowder weapons in China during the Song Dynasty", year: 1132 },
  { event: "Genghis Khan unites the Mongol tribes and founds the Mongol Empire", year: 1206 },
  { event: "Mongols conquer the Jin Dynasty in northern China", year: 1234 },
  { event: "Kublai Khan establishes the Yuan Dynasty in China", year: 1271 },
  { event: "Failed Mongol invasion of Japan thwarted by typhoon (kamikaze)", year: 1281 },
  { event: "Ming Dynasty founded in China by Zhu Yuanzhang after overthrowing the Yuan", year: 1368 },
  { event: "Zheng He begins his first grand maritime voyage from China", year: 1405 },
  { event: "Joseon Dynasty founded in Korea by Yi Seong-gye", year: 1392 },
  { event: "King Sejong the Great introduces Hangul, the Korean alphabet", year: 1443 },
  { event: "Khmer Empire reaches its zenith with completion of Angkor Wat", year: 1150 },
  { event: "Sukhothai Kingdom established as the first Thai state", year: 1238 },

  // ── Medieval Africa & Americas ────────────────────────────────────────────
  { event: "Ghana Empire dominates West African gold and salt trade", year: 800 },
  { event: "Great Zimbabwe settlement begins construction in southern Africa", year: 1100 },
  { event: "Sundiata Keita founds the Mali Empire in West Africa", year: 1235 },
  { event: "Mansa Musa of Mali undertakes his legendary pilgrimage to Mecca", year: 1324 },
  { event: "University of Timbuktu (Sankore) flourishes as a center of learning", year: 1327 },
  { event: "Aztec civilization founds the city of Tenochtitlan on Lake Texcoco", year: 1325 },
  { event: "Inca Empire begins rapid expansion under Pachacuti in South America", year: 1438 },
  { event: "Songhai Empire rises to prominence under Sunni Ali in West Africa", year: 1464 },

  // ══════════════════════════════════════════════════════════════════════════
  // EARLY MODERN ERA (1500–1800)
  // ══════════════════════════════════════════════════════════════════════════

  // ── Age of Exploration ────────────────────────────────────────────────────
  { event: "Christopher Columbus reaches the Caribbean islands", year: 1492 },
  { event: "Vasco da Gama reaches India by sea route around Africa", year: 1498 },
  { event: "Pedro Alvares Cabral claims Brazil for Portugal", year: 1500 },
  { event: "Amerigo Vespucci's voyages lead to the New World being named America", year: 1502 },
  { event: "Vasco Nunez de Balboa becomes the first European to see the Pacific Ocean from the Americas", year: 1513 },
  { event: "Ferdinand Magellan's expedition begins the first circumnavigation of the Earth", year: 1519 },
  { event: "Hernan Cortes conquers the Aztec Empire in Mexico", year: 1521 },
  { event: "Francisco Pizarro conquers the Inca Empire in Peru", year: 1533 },
  { event: "Jacques Cartier explores the St. Lawrence River in Canada", year: 1534 },
  { event: "Francis Drake completes the second circumnavigation of the globe", year: 1580 },
  { event: "Founding of Jamestown, the first permanent English settlement in America", year: 1607 },
  { event: "Henry Hudson explores the river later named after him in North America", year: 1609 },
  { event: "Dutch East India Company (VOC) established as the first multinational corporation", year: 1602 },
  { event: "Abel Tasman becomes the first European to reach New Zealand and Tasmania", year: 1642 },

  // ── Reformation & Religious Wars ──────────────────────────────────────────
  { event: "Martin Luther posts the Ninety-Five Theses, sparking the Protestant Reformation", year: 1517 },
  { event: "Diet of Worms: Martin Luther refuses to recant his writings", year: 1521 },
  { event: "Henry VIII breaks with Rome and establishes the Church of England", year: 1534 },
  { event: "Council of Trent begins the Catholic Counter-Reformation", year: 1545 },
  { event: "Peace of Augsburg allows rulers to choose Lutheranism or Catholicism", year: 1555 },
  { event: "St. Bartholomew's Day Massacre of Huguenots in France", year: 1572 },
  { event: "Edict of Nantes grants religious tolerance to French Protestants", year: 1598 },
  { event: "Thirty Years' War begins in the Holy Roman Empire", year: 1618 },
  { event: "Peace of Westphalia ends the Thirty Years' War and establishes state sovereignty", year: 1648 },

  // ── Early Modern Science & Culture ────────────────────────────────────────
  { event: "Nicolaus Copernicus publishes De Revolutionibus, proposing heliocentrism", year: 1543 },
  { event: "Andreas Vesalius publishes De Humani Corporis Fabrica, revolutionizing anatomy", year: 1543 },
  { event: "Galileo Galilei observes Jupiter's moons with his telescope", year: 1610 },
  { event: "Johannes Kepler publishes his laws of planetary motion", year: 1609 },
  { event: "William Harvey describes the circulation of blood in the human body", year: 1628 },
  { event: "Rene Descartes publishes Discourse on the Method", year: 1637 },
  { event: "Blaise Pascal and Pierre de Fermat develop probability theory through correspondence", year: 1654 },
  { event: "Robert Hooke publishes Micrographia, coining the term 'cell'", year: 1665 },
  { event: "Isaac Newton publishes Principia Mathematica", year: 1687 },
  { event: "Antonie van Leeuwenhoek observes bacteria under a microscope", year: 1676 },
  { event: "Gottfried Wilhelm Leibniz publishes his version of calculus", year: 1684 },
  { event: "Edmund Halley predicts the return of the comet later named after him", year: 1705 },
  { event: "Carl Linnaeus publishes Systema Naturae, founding modern taxonomy", year: 1735 },
  { event: "Benjamin Franklin conducts his famous kite experiment with lightning", year: 1752 },
  { event: "James Watt patents his improved steam engine", year: 1769 },
  { event: "Antoine Lavoisier identifies oxygen and helps establish modern chemistry", year: 1778 },
  { event: "Edward Jenner develops the first successful smallpox vaccine", year: 1796 },
  { event: "Alessandro Volta invents the voltaic pile, the first electric battery", year: 1800 },

  // ── Early Modern Europe: Politics ─────────────────────────────────────────
  { event: "Spanish Armada defeated by England, shifting European naval power", year: 1588 },
  { event: "Gunpowder Plot: failed assassination attempt on King James I of England", year: 1605 },
  { event: "Mayflower Pilgrims land at Plymouth Rock in Massachusetts", year: 1620 },
  { event: "English Civil War begins between Parliamentarians and Royalists", year: 1642 },
  { event: "Execution of King Charles I of England", year: 1649 },
  { event: "Oliver Cromwell establishes the Commonwealth of England", year: 1649 },
  { event: "Restoration of the English monarchy under Charles II", year: 1660 },
  { event: "Glorious Revolution: William of Orange becomes King of England", year: 1688 },
  { event: "English Bill of Rights enacted, limiting monarchical power", year: 1689 },
  { event: "Act of Union unites England and Scotland into Great Britain", year: 1707 },
  { event: "Peter the Great founds St. Petersburg as Russia's new capital", year: 1703 },
  { event: "War of the Spanish Succession ends with the Treaty of Utrecht", year: 1713 },
  { event: "Seven Years' War begins, the first truly global conflict", year: 1756 },
  { event: "Treaty of Paris ends the Seven Years' War", year: 1763 },
  { event: "First Partition of Poland among Russia, Prussia, and Austria", year: 1772 },

  // ── Early Modern Asia ─────────────────────────────────────────────────────
  { event: "Babur founds the Mughal Empire after the Battle of Panipat in India", year: 1526 },
  { event: "Suleiman the Magnificent besieges Vienna, marking the Ottoman Empire's European apex", year: 1529 },
  { event: "Mughal Emperor Akbar the Great introduces religious tolerance policies in India", year: 1563 },
  { event: "Battle of Lepanto: Christian coalition defeats the Ottoman navy", year: 1571 },
  { event: "Tokugawa Ieyasu wins the Battle of Sekigahara, unifying Japan", year: 1600 },
  { event: "Tokugawa Shogunate begins the policy of sakoku, isolating Japan from the West", year: 1633 },
  { event: "Taj Mahal completed in Agra, India, by Mughal Emperor Shah Jahan", year: 1653 },
  { event: "Qing Dynasty conquers China after the fall of the Ming Dynasty", year: 1644 },
  { event: "Treaty of Nerchinsk: first formal treaty between Russia and China", year: 1689 },
  { event: "Battle of Plassey: British East India Company defeats the Nawab of Bengal", year: 1757 },
  { event: "Captain James Cook charts the east coast of Australia", year: 1770 },

  // ── Revolutions ───────────────────────────────────────────────────────────
  { event: "American Declaration of Independence adopted by the Continental Congress", year: 1776 },
  { event: "Battle of Saratoga: turning point of the American Revolutionary War", year: 1777 },
  { event: "Treaty of Paris formally ends the American Revolutionary War", year: 1783 },
  { event: "United States Constitution ratified", year: 1788 },
  { event: "George Washington inaugurated as the first President of the United States", year: 1789 },
  { event: "Storming of the Bastille in Paris, beginning the French Revolution", year: 1789 },
  { event: "Declaration of the Rights of Man and of the Citizen adopted in France", year: 1789 },
  { event: "Execution of King Louis XVI of France by guillotine", year: 1793 },
  { event: "Reign of Terror begins under the Committee of Public Safety in France", year: 1793 },
  { event: "Haitian Revolution: enslaved people led by Toussaint Louverture revolt", year: 1791 },
  { event: "Haiti declares independence, becoming the first free Black republic", year: 1804 },

  // ── Early Modern Africa & Americas ────────────────────────────────────────
  { event: "Transatlantic slave trade intensifies with Portuguese ships reaching West Africa", year: 1510 },
  { event: "Kingdom of Kongo establishes diplomatic relations with Portugal", year: 1491 },
  { event: "Founding of the colony of New Amsterdam (later New York) by the Dutch", year: 1626 },
  { event: "Salem Witch Trials take place in colonial Massachusetts", year: 1692 },
  { event: "Boston Tea Party: American colonists protest British taxation", year: 1773 },

  // ══════════════════════════════════════════════════════════════════════════
  // MODERN ERA (1800–present)
  // ══════════════════════════════════════════════════════════════════════════

  // ── Napoleonic Era ────────────────────────────────────────────────────────
  { event: "Napoleon Bonaparte seizes power in the coup of 18 Brumaire", year: 1799 },
  { event: "Napoleonic Code enacted in France, reforming civil law", year: 1804 },
  { event: "Battle of Trafalgar: British Navy defeats the French and Spanish fleets", year: 1805 },
  { event: "Battle of Austerlitz: Napoleon defeats Russia and Austria", year: 1805 },
  { event: "Napoleon invades Russia and occupies Moscow", year: 1812 },
  { event: "Battle of Waterloo: Napoleon defeated by British and Prussian forces", year: 1815 },
  { event: "Congress of Vienna redraws the map of Europe after Napoleon's defeat", year: 1815 },

  // ── 19th Century Science & Technology ─────────────────────────────────────
  { event: "Michael Faraday discovers electromagnetic induction", year: 1831 },
  { event: "Charles Darwin publishes On the Origin of Species", year: 1859 },
  { event: "Gregor Mendel publishes his laws of genetic inheritance", year: 1866 },
  { event: "Dmitri Mendeleev publishes the first periodic table of elements", year: 1869 },
  { event: "Alexander Graham Bell patents the telephone", year: 1876 },
  { event: "Thomas Edison invents the practical incandescent light bulb", year: 1879 },
  { event: "Louis Pasteur develops the rabies vaccine", year: 1885 },
  { event: "Heinrich Hertz demonstrates the existence of electromagnetic waves", year: 1887 },
  { event: "Wilhelm Rontgen discovers X-rays", year: 1895 },
  { event: "Marie and Pierre Curie discover radium", year: 1898 },
  { event: "Guglielmo Marconi sends the first transatlantic radio signal", year: 1901 },
  { event: "First successful powered airplane flight by the Wright brothers", year: 1903 },
  { event: "Albert Einstein publishes the special theory of relativity", year: 1905 },
  { event: "Albert Einstein publishes the general theory of relativity", year: 1915 },
  { event: "Ernest Rutherford discovers the atomic nucleus", year: 1911 },
  { event: "Niels Bohr proposes his model of the atom", year: 1913 },
  { event: "Alexander Fleming discovers penicillin", year: 1928 },

  // ── 19th Century Political Events ─────────────────────────────────────────
  { event: "Simon Bolivar leads the liberation of Venezuela from Spanish rule", year: 1811 },
  { event: "Mexican War of Independence culminates in Mexican sovereignty", year: 1821 },
  { event: "Greek War of Independence from the Ottoman Empire begins", year: 1821 },
  { event: "Monroe Doctrine declared, opposing European colonialism in the Americas", year: 1823 },
  { event: "Abolition of slavery throughout the British Empire", year: 1833 },
  { event: "Treaty of Waitangi signed between the British Crown and Maori chiefs in New Zealand", year: 1840 },
  { event: "Irish Great Famine begins, causing mass emigration and death", year: 1845 },
  { event: "Revolutions of 1848 sweep across Europe", year: 1848 },
  { event: "Communist Manifesto published by Karl Marx and Friedrich Engels", year: 1848 },
  { event: "Commodore Matthew Perry opens Japan to Western trade", year: 1853 },
  { event: "Crimean War: Britain and France ally against Russia", year: 1853 },
  { event: "Indian Rebellion of 1857 against British East India Company rule", year: 1857 },
  { event: "American Civil War begins with the attack on Fort Sumter", year: 1861 },
  { event: "Emancipation Proclamation frees enslaved people in Confederate states", year: 1863 },
  { event: "Battle of Gettysburg: turning point of the American Civil War", year: 1863 },
  { event: "Assassination of President Abraham Lincoln", year: 1865 },
  { event: "Thirteenth Amendment abolishes slavery in the United States", year: 1865 },
  { event: "Meiji Restoration transforms Japan into a modern industrial state", year: 1868 },
  { event: "Suez Canal opens, connecting the Mediterranean and Red Seas", year: 1869 },
  { event: "Unification of Germany under Otto von Bismarck", year: 1871 },
  { event: "Unification of Italy completed with Rome as the capital", year: 1871 },
  { event: "Berlin Conference partitions Africa among European colonial powers", year: 1884 },
  { event: "Dreyfus Affair exposes antisemitism in the French military", year: 1894 },
  { event: "First modern Olympic Games held in Athens, Greece", year: 1896 },
  { event: "Spanish-American War: United States defeats Spain", year: 1898 },
  { event: "Boxer Rebellion erupts in Qing Dynasty China against foreign influence", year: 1899 },
  { event: "Boer War begins between the British Empire and Boer republics in South Africa", year: 1899 },
  { event: "Australian colonies federate to form the Commonwealth of Australia", year: 1901 },

  // ── World War I & Interwar Period ─────────────────────────────────────────
  { event: "Assassination of Archduke Franz Ferdinand in Sarajevo triggers World War I", year: 1914 },
  { event: "Battle of the Somme: one of the deadliest battles in human history", year: 1916 },
  { event: "Balfour Declaration supports a Jewish homeland in Palestine", year: 1917 },
  { event: "Russian Revolution: Bolsheviks seize power under Vladimir Lenin", year: 1917 },
  { event: "Armistice of 11 November ends World War I", year: 1918 },
  { event: "Treaty of Versailles formally ends World War I", year: 1919 },
  { event: "League of Nations established to promote world peace", year: 1920 },
  { event: "Nineteenth Amendment grants women the right to vote in the United States", year: 1920 },
  { event: "Founding of the Republic of Turkey by Mustafa Kemal Ataturk", year: 1923 },
  { event: "Wall Street Crash triggers the Great Depression worldwide", year: 1929 },
  { event: "Mahatma Gandhi leads the Salt March in India protesting British taxation", year: 1930 },
  { event: "Adolf Hitler appointed Chancellor of Germany", year: 1933 },
  { event: "Long March: Chinese Communists trek 6,000 miles to escape Nationalist forces", year: 1934 },
  { event: "Spanish Civil War begins between Republicans and Nationalists", year: 1936 },
  { event: "Kristallnacht: anti-Jewish pogrom across Nazi Germany", year: 1938 },
  { event: "Munich Agreement: Britain and France appease Hitler over Czechoslovakia", year: 1938 },

  // ── World War II ──────────────────────────────────────────────────────────
  { event: "Germany invades Poland, beginning World War II in Europe", year: 1939 },
  { event: "Fall of France: Germany occupies Paris", year: 1940 },
  { event: "Battle of Britain: RAF defends against German Luftwaffe bombing", year: 1940 },
  { event: "Operation Barbarossa: Germany invades the Soviet Union", year: 1941 },
  { event: "Attack on Pearl Harbor: Japan bombs the US naval base in Hawaii", year: 1941 },
  { event: "Battle of Midway: US Navy defeats the Japanese fleet in the Pacific", year: 1942 },
  { event: "Battle of Stalingrad: Soviet Union defeats Germany in a pivotal engagement", year: 1943 },
  { event: "D-Day: Allied forces land on the beaches of Normandy, France", year: 1944 },
  { event: "Liberation of Auschwitz concentration camp by Soviet troops", year: 1945 },
  { event: "Germany surrenders unconditionally, ending World War II in Europe (V-E Day)", year: 1945 },
  { event: "Atomic bomb dropped on Hiroshima, Japan", year: 1945 },
  { event: "Atomic bomb dropped on Nagasaki, Japan", year: 1945 },
  { event: "Japan surrenders, ending World War II (V-J Day)", year: 1945 },
  { event: "Nuremberg Trials begin, prosecuting Nazi war criminals", year: 1945 },

  // ── Cold War Era ──────────────────────────────────────────────────────────
  { event: "United Nations formally established with 51 founding member states", year: 1945 },
  { event: "Partition of India and Pakistan at independence from British rule", year: 1947 },
  { event: "State of Israel established, followed by the Arab-Israeli War", year: 1948 },
  { event: "Universal Declaration of Human Rights adopted by the UN General Assembly", year: 1948 },
  { event: "NATO established as a Western military alliance", year: 1949 },
  { event: "People's Republic of China proclaimed by Mao Zedong", year: 1949 },
  { event: "Korean War begins with North Korea's invasion of South Korea", year: 1950 },
  { event: "Structure of DNA discovered by Watson and Crick", year: 1953 },
  { event: "Brown v. Board of Education: US Supreme Court rules school segregation unconstitutional", year: 1954 },
  { event: "Bandung Conference: Asian and African nations form the Non-Aligned Movement", year: 1955 },
  { event: "Rosa Parks refuses to give up her bus seat in Montgomery, Alabama", year: 1955 },
  { event: "Hungarian Revolution against Soviet-imposed policies is crushed", year: 1956 },
  { event: "Suez Crisis: Egypt nationalizes the Suez Canal, prompting military intervention", year: 1956 },
  { event: "Sputnik 1 launched by the Soviet Union, beginning the Space Age", year: 1957 },
  { event: "European Economic Community (EEC) established by the Treaty of Rome", year: 1957 },
  { event: "Cuban Revolution: Fidel Castro overthrows the Batista government", year: 1959 },
  { event: "Construction of the Berlin Wall divides East and West Berlin", year: 1961 },
  { event: "Yuri Gagarin becomes the first human in space", year: 1961 },
  { event: "Cuban Missile Crisis brings the US and Soviet Union to the brink of nuclear war", year: 1962 },
  { event: "Martin Luther King Jr. delivers the 'I Have a Dream' speech in Washington", year: 1963 },
  { event: "Assassination of President John F. Kennedy in Dallas, Texas", year: 1963 },
  { event: "Civil Rights Act signed into law in the United States", year: 1964 },
  { event: "Gulf of Tonkin Resolution escalates US involvement in Vietnam", year: 1964 },
  { event: "Assassination of Malcolm X in New York City", year: 1965 },
  { event: "Cultural Revolution begins in China under Mao Zedong", year: 1966 },
  { event: "Six-Day War: Israel captures the Sinai, West Bank, and Golan Heights", year: 1967 },
  { event: "Assassination of Martin Luther King Jr. in Memphis, Tennessee", year: 1968 },
  { event: "Prague Spring: Soviet forces crush democratic reforms in Czechoslovakia", year: 1968 },
  { event: "Apollo 11: Neil Armstrong and Buzz Aldrin walk on the Moon", year: 1969 },
  { event: "Woodstock music festival takes place in New York State", year: 1969 },

  // ── 1970s–1980s ───────────────────────────────────────────────────────────
  { event: "Bangladesh Liberation War leads to independence from Pakistan", year: 1971 },
  { event: "Watergate scandal leads to the resignation of US President Richard Nixon", year: 1974 },
  { event: "Fall of Saigon: end of the Vietnam War", year: 1975 },
  { event: "Khmer Rouge regime begins genocide in Cambodia", year: 1975 },
  { event: "Apple Computer founded by Steve Jobs and Steve Wozniak", year: 1976 },
  { event: "Camp David Accords: Egypt and Israel sign a peace agreement", year: 1978 },
  { event: "Iranian Revolution overthrows Shah Mohammad Reza Pahlavi", year: 1979 },
  { event: "Soviet Union invades Afghanistan", year: 1979 },
  { event: "Solidarity trade union founded in Poland by Lech Walesa", year: 1980 },
  { event: "Iran-Iraq War begins, lasting eight years", year: 1980 },
  { event: "Falklands War: Britain and Argentina clash over the South Atlantic islands", year: 1982 },
  { event: "Chernobyl nuclear disaster in Ukraine, Soviet Union", year: 1986 },
  { event: "Tiananmen Square protests in Beijing suppressed by the Chinese military", year: 1989 },
  { event: "Fall of the Berlin Wall, symbolizing the end of the Cold War", year: 1989 },
  { event: "Velvet Revolution: Czechoslovakia peacefully ends communist rule", year: 1989 },

  // ── 1990s ─────────────────────────────────────────────────────────────────
  { event: "Reunification of Germany after 45 years of division", year: 1990 },
  { event: "Nelson Mandela released from prison after 27 years in South Africa", year: 1990 },
  { event: "Dissolution of the Soviet Union into 15 independent republics", year: 1991 },
  { event: "Gulf War: UN coalition forces liberate Kuwait from Iraqi occupation", year: 1991 },
  { event: "Apartheid officially ends in South Africa", year: 1991 },
  { event: "European Union established by the Maastricht Treaty", year: 1993 },
  { event: "Oslo Accords signed between Israel and the Palestine Liberation Organization", year: 1993 },
  { event: "Rwandan Genocide: approximately 800,000 Tutsi killed in 100 days", year: 1994 },
  { event: "Nelson Mandela elected as South Africa's first Black president", year: 1994 },
  { event: "World Trade Organization (WTO) established to regulate international trade", year: 1995 },
  { event: "Srebrenica massacre during the Bosnian War", year: 1995 },
  { event: "Dolly the Sheep becomes the first cloned mammal", year: 1996 },
  { event: "Handover of Hong Kong from the United Kingdom to China", year: 1997 },
  { event: "Good Friday Agreement brings peace to Northern Ireland", year: 1998 },
  { event: "Euro currency officially introduced in European Union countries", year: 1999 },

  // ── 2000s ─────────────────────────────────────────────────────────────────
  { event: "Completion of the Human Genome Project's first draft sequence", year: 2000 },
  { event: "September 11 terrorist attacks on the World Trade Center and Pentagon", year: 2001 },
  { event: "United States invades Afghanistan in response to the September 11 attacks", year: 2001 },
  { event: "United States invades Iraq and overthrows Saddam Hussein", year: 2003 },
  { event: "Indian Ocean earthquake and tsunami kills over 230,000 people", year: 2004 },
  { event: "Hurricane Katrina devastates New Orleans and the US Gulf Coast", year: 2005 },
  { event: "Large Hadron Collider at CERN begins operations", year: 2008 },
  { event: "Global financial crisis triggered by the collapse of Lehman Brothers", year: 2008 },
  { event: "Barack Obama inaugurated as the first African American US President", year: 2009 },

  // ── 2010s–2020s ───────────────────────────────────────────────────────────
  { event: "Arab Spring protests begin in Tunisia, spreading across the Middle East", year: 2010 },
  { event: "Fukushima Daiichi nuclear disaster in Japan following a massive earthquake", year: 2011 },
  { event: "Death of Osama bin Laden in a US military operation in Pakistan", year: 2011 },
  { event: "Higgs boson particle discovered at CERN's Large Hadron Collider", year: 2012 },
  { event: "Russia annexes Crimea from Ukraine", year: 2014 },
  { event: "Paris Agreement on climate change adopted by 196 nations", year: 2015 },
  { event: "LIGO detects gravitational waves for the first time, confirming Einstein's prediction", year: 2015 },
  { event: "United Kingdom votes to leave the European Union (Brexit)", year: 2016 },
  { event: "COVID-19 pandemic declared by the World Health Organization", year: 2020 },
  { event: "Russia launches a full-scale invasion of Ukraine", year: 2022 },

  // ── Additional Ancient Events ─────────────────────────────────────────────
  { event: "Trojan War (traditional date) between Greece and Troy", year: -1184 },
  { event: "First Olympic Games held at Olympia in ancient Greece", year: -776 },
  { event: "Homer composes the Iliad and the Odyssey", year: -750 },
  { event: "Solon's reforms in Athens lay foundations for democracy", year: -594 },
  { event: "Hippocrates establishes medicine as a discipline separate from religion", year: -400 },
  { event: "Aristotle founds the Lyceum in Athens", year: -335 },
  { event: "Rosetta Stone carved during the reign of Ptolemy V in Egypt", year: -196 },
  { event: "Spartacus leads a slave revolt against the Roman Republic", year: -73 },

  // ── Additional Medieval Events ────────────────────────────────────────────
  { event: "Battle of Manzikert: Seljuk Turks defeat the Byzantine Empire", year: 1071 },
  { event: "Battle of Kosovo: Ottoman Empire defeats Serbian forces", year: 1389 },
  { event: "Timur (Tamerlane) sacks Delhi during his Indian campaign", year: 1398 },
  { event: "Council of Constance ends the Western Schism in the Catholic Church", year: 1418 },
  { event: "Printing of the Diamond Sutra, the oldest known dated printed book, in China", year: 868 },
  { event: "Vikings raid the monastery at Lindisfarne, marking the start of the Viking Age", year: 793 },

  // ── Additional Early Modern Events ────────────────────────────────────────
  { event: "Michelangelo completes the ceiling of the Sistine Chapel", year: 1512 },
  { event: "Treaty of Tordesillas divides the New World between Spain and Portugal", year: 1494 },
  { event: "Great Fire of London destroys much of the city", year: 1666 },
  { event: "John Locke publishes Two Treatises of Government", year: 1689 },
  { event: "Adam Smith publishes The Wealth of Nations", year: 1776 },
  { event: "US Bill of Rights ratified as the first ten amendments to the Constitution", year: 1791 },

  // ── Additional Modern Events ──────────────────────────────────────────────
  { event: "Louisiana Purchase: United States buys territory from France", year: 1803 },
  { event: "Abolition of the slave trade in the British Empire", year: 1807 },
  { event: "Battle of the Alamo during the Texas Revolution", year: 1836 },
  { event: "First Opium War between Britain and Qing Dynasty China begins", year: 1839 },
  { event: "Treaty of Nanking cedes Hong Kong to Britain after the First Opium War", year: 1842 },
  { event: "Seneca Falls Convention: first women's rights convention in the United States", year: 1848 },
  { event: "Transcontinental railroad completed in the United States at Promontory Summit", year: 1869 },
  { event: "Statue of Liberty dedicated in New York Harbor", year: 1886 },
  { event: "Russo-Japanese War: Japan defeats Russia, the first modern Asian victory over a European power", year: 1905 },
  { event: "Chinese Revolution ends the Qing Dynasty, establishing the Republic of China", year: 1911 },
  { event: "Titanic sinks on its maiden voyage in the North Atlantic", year: 1912 },
  { event: "Panama Canal officially opens, connecting the Atlantic and Pacific Oceans", year: 1914 },
  { event: "Charles Lindbergh completes the first solo nonstop transatlantic flight", year: 1927 },
  { event: "Enrico Fermi achieves the first sustained nuclear chain reaction in Chicago", year: 1942 },
  { event: "Bretton Woods Conference establishes the World Bank and IMF", year: 1944 },
  { event: "Marshall Plan provides economic aid for European recovery after WWII", year: 1948 },
  { event: "Indonesian independence recognized by the Netherlands", year: 1949 },
  { event: "Korean War armistice signed at Panmunjom", year: 1953 },
  { event: "Algerian War of Independence from France begins", year: 1954 },
  { event: "Ghana becomes the first sub-Saharan African country to gain independence", year: 1957 },
  { event: "NASA established as the United States civilian space agency", year: 1958 },
  { event: "Congo gains independence from Belgium", year: 1960 },
  { event: "Voting Rights Act signed into law in the United States", year: 1965 },
  { event: "Treaty on the Non-Proliferation of Nuclear Weapons (NPT) signed", year: 1968 },
  { event: "ARPANET, the precursor to the Internet, sends its first message", year: 1969 },
  { event: "Yom Kippur War: Egypt and Syria launch a surprise attack on Israel", year: 1973 },
  { event: "Portuguese Carnation Revolution peacefully ends authoritarian rule", year: 1974 },
  { event: "Death of Mao Zedong and end of the Cultural Revolution in China", year: 1976 },
  { event: "First test-tube baby, Louise Brown, born in England", year: 1978 },
  { event: "Assassination of Egyptian President Anwar Sadat", year: 1981 },
  { event: "HIV/AIDS first recognized as a new disease by the CDC", year: 1981 },
  { event: "Bhopal chemical disaster in India, the world's worst industrial accident", year: 1984 },
  { event: "Mikhail Gorbachev introduces glasnost and perestroika reforms in the Soviet Union", year: 1985 },
  { event: "Space Shuttle Challenger disaster kills seven crew members", year: 1986 },
  { event: "World Wide Web invented by Tim Berners-Lee at CERN", year: 1989 },
  { event: "Dayton Agreement ends the Bosnian War", year: 1995 },
  { event: "East Timor gains independence from Indonesia", year: 2002 },
  { event: "Facebook launched by Mark Zuckerberg at Harvard University", year: 2004 },
  { event: "South Sudan becomes an independent nation, the world's newest country", year: 2011 },
  { event: "Notre-Dame Cathedral in Paris severely damaged by fire", year: 2019 },
  { event: "James Webb Space Telescope launched into orbit", year: 2021 },
];
