export interface ScienceFact {
  question: string;
  correctAnswer: string;
  distractors: [string, string, string];
}

export interface GeographyFact {
  country: string;
  statType: "population" | "area" | "capital";
  question: string;
  correctAnswer: string;
  distractors: [string, string, string];
}

export interface HistoricalEvent {
  event: string;
  year: number;
}

export interface MathConstant {
  name: string;
  symbol: string;
  value: string;
}

// ─── Science Facts ───────────────────────────────────────────────────────────

export const SCIENCE_FACTS: ScienceFact[] = [
  // ── Physics: Fundamental Constants ──────────────────────────────────────────
  {
    question: "What is the fine-structure constant α (dimensionless)?",
    correctAnswer: "≈ 1/137.036 (0.0072973525693)",
    distractors: ["≈ 1/137.000 (0.0072992701)", "≈ 1/128.036 (0.0078107)", "≈ 1/142.036 (0.0070405)"],
  },
  {
    question: "What is the Bohr radius a₀ in picometers?",
    correctAnswer: "52.9177 pm",
    distractors: ["48.5921 pm", "55.2634 pm", "50.0000 pm"],
  },
  {
    question: "What is the magnetic moment of the electron in Bohr magnetons (including anomalous moment)?",
    correctAnswer: "≈ 1.00115965218 μ_B",
    distractors: ["≈ 1.00000000000 μ_B", "≈ 1.00231930436 μ_B", "≈ 0.99884034782 μ_B"],
  },
  {
    question: "What is the Josephson constant K_J (2e/h)?",
    correctAnswer: "483,597.8484 GHz/V",
    distractors: ["483,597.9000 GHz/V", "241,798.9242 GHz/V", "967,195.6968 GHz/V"],
  },
  {
    question: "What is the von Klitzing constant R_K (h/e²)?",
    correctAnswer: "25,812.80745 Ω",
    distractors: ["25,812.80000 Ω", "12,906.40373 Ω", "51,625.61490 Ω"],
  },
  {
    question: "What is the classical electron radius (Lorentz radius) in femtometers?",
    correctAnswer: "2.81794 fm",
    distractors: ["1.53561 fm", "3.86159 fm", "2.42631 fm"],
  },
  {
    question: "What is the Compton wavelength of the proton in femtometers?",
    correctAnswer: "1.32141 fm",
    distractors: ["2.42631 fm", "0.87680 fm", "1.53561 fm"],
  },
  {
    question: "What is the nuclear magneton μ_N in J/T?",
    correctAnswer: "5.0508 × 10⁻²⁷ J/T",
    distractors: ["9.2741 × 10⁻²⁴ J/T", "5.0508 × 10⁻²⁴ J/T", "3.1525 × 10⁻²⁷ J/T"],
  },
  {
    question: "What is the Planck length in meters?",
    correctAnswer: "1.616 × 10⁻³⁵ m",
    distractors: ["1.616 × 10⁻³³ m", "5.391 × 10⁻⁴⁴ m", "1.055 × 10⁻³⁵ m"],
  },
  {
    question: "What is the Planck time in seconds?",
    correctAnswer: "5.391 × 10⁻⁴⁴ s",
    distractors: ["1.616 × 10⁻³⁵ s", "5.391 × 10⁻⁴⁰ s", "1.416 × 10⁻⁴⁴ s"],
  },
  {
    question: "What is the Planck temperature in Kelvin?",
    correctAnswer: "1.416 × 10³² K",
    distractors: ["5.391 × 10³² K", "1.416 × 10²⁸ K", "2.725 × 10³² K"],
  },
  {
    question: "What is the Planck mass in micrograms?",
    correctAnswer: "≈ 21.76 μg",
    distractors: ["≈ 2.176 μg", "≈ 217.6 μg", "≈ 6.626 μg"],
  },
  {
    question: "What is the vacuum impedance Z₀ (impedance of free space) in ohms?",
    correctAnswer: "≈ 376.730 Ω",
    distractors: ["≈ 120π Ω (exact)", "≈ 299.792 Ω", "≈ 188.365 Ω"],
  },
  {
    question: "What is the Wien displacement constant b in mm·K?",
    correctAnswer: "2.8978 mm·K",
    distractors: ["5.6704 mm·K", "1.3807 mm·K", "3.2898 mm·K"],
  },
  {
    question: "What is the first radiation constant c₁ = 2πhc² in W·m²?",
    correctAnswer: "3.7418 × 10⁻¹⁶ W·m²",
    distractors: ["3.7418 × 10⁻¹³ W·m²", "1.4388 × 10⁻² W·m²", "5.6704 × 10⁻¹⁶ W·m²"],
  },
  {
    question: "What is the Schwinger limit (critical QED electric field) in V/m?",
    correctAnswer: "≈ 1.32 × 10¹⁸ V/m",
    distractors: ["≈ 1.32 × 10¹⁵ V/m", "≈ 3.00 × 10¹⁸ V/m", "≈ 1.32 × 10²¹ V/m"],
  },
  {
    question: "What is the Chandrasekhar mass limit in solar masses?",
    correctAnswer: "≈ 1.4 M☉",
    distractors: ["≈ 3.0 M☉", "≈ 0.7 M☉", "≈ 2.2 M☉"],
  },
  {
    question: "What is the gyromagnetic ratio of the proton γ_p in MHz/T?",
    correctAnswer: "42.577 MHz/T",
    distractors: ["28.025 MHz/T", "67.262 MHz/T", "36.461 MHz/T"],
  },
  // ── Physics: Specific Values & Phenomena ────────────────────────────────────
  {
    question: "What is the Schwarzschild radius of Earth in millimeters?",
    correctAnswer: "≈ 8.87 mm",
    distractors: ["≈ 17.74 mm", "≈ 4.44 mm", "≈ 2.95 mm"],
  },
  {
    question: "What is the Tolman-Oppenheimer-Volkoff limit for neutron star mass?",
    correctAnswer: "≈ 2.01–2.16 M☉",
    distractors: ["≈ 1.4 M☉", "≈ 3.2 M☉", "≈ 0.8 M☉"],
  },
  {
    question: "What is the Lamb shift (2S₁/₂ − 2P₁/₂) in hydrogen in MHz?",
    correctAnswer: "≈ 1057.845 MHz",
    distractors: ["≈ 1420.405 MHz", "≈ 528.923 MHz", "≈ 2115.690 MHz"],
  },
  {
    question: "What is the 21-cm hydrogen line frequency?",
    correctAnswer: "1420.405 MHz",
    distractors: ["1057.845 MHz", "1667.359 MHz", "1280.000 MHz"],
  },
  {
    question: "What is the neutron mean lifetime in seconds?",
    correctAnswer: "≈ 878.4 seconds (≈14.6 minutes)",
    distractors: ["≈ 611 seconds (≈10.2 minutes)", "≈ 1,200 seconds (≈20 minutes)", "≈ 480 seconds (≈8 minutes)"],
  },
  {
    question: "What is the ratio of proton mass to electron mass (mₚ/mₑ)?",
    correctAnswer: "≈ 1836.15",
    distractors: ["≈ 1872.34", "≈ 1776.82", "≈ 1920.00"],
  },
  {
    question: "What is the W boson mass in GeV/c²?",
    correctAnswer: "≈ 80.377 GeV/c²",
    distractors: ["≈ 91.188 GeV/c²", "≈ 125.25 GeV/c²", "≈ 72.330 GeV/c²"],
  },
  {
    question: "What is the Z boson mass in GeV/c²?",
    correctAnswer: "≈ 91.188 GeV/c²",
    distractors: ["≈ 80.377 GeV/c²", "≈ 125.25 GeV/c²", "≈ 97.455 GeV/c²"],
  },
  {
    question: "What is the Higgs boson mass in GeV/c²?",
    correctAnswer: "≈ 125.25 GeV/c²",
    distractors: ["≈ 91.188 GeV/c²", "≈ 174.1 GeV/c²", "≈ 115.50 GeV/c²"],
  },
  {
    question: "What is the top quark mass in GeV/c²?",
    correctAnswer: "≈ 172.69 GeV/c²",
    distractors: ["≈ 125.25 GeV/c²", "≈ 4.18 GeV/c²", "≈ 164.50 GeV/c²"],
  },
  {
    question: "What is the muon mass in MeV/c²?",
    correctAnswer: "≈ 105.658 MeV/c²",
    distractors: ["≈ 0.511 MeV/c²", "≈ 139.570 MeV/c²", "≈ 938.272 MeV/c²"],
  },
  {
    question: "What is the muon magnetic moment anomaly (g-2)/2?",
    correctAnswer: "≈ 1.16592 × 10⁻³",
    distractors: ["≈ 1.15966 × 10⁻³", "≈ 1.16592 × 10⁻²", "≈ 2.00232 × 10⁻³"],
  },
  {
    question: "What is the speed of gravity according to general relativity and LIGO observations?",
    correctAnswer: "Equal to the speed of light c (299,792,458 m/s)",
    distractors: ["Slightly faster than c by ~0.1%", "Instantaneous (infinite)", "Approximately 0.95c"],
  },
  {
    question: "What is the Debye temperature of diamond in Kelvin?",
    correctAnswer: "≈ 2,230 K",
    distractors: ["≈ 1,040 K", "≈ 345 K", "≈ 3,500 K"],
  },
  // ── Chemistry: Obscure & Advanced ──────────────────────────────────────────
  {
    question: "What is the oxidation state of manganese in potassium permanganate (KMnO₄)?",
    correctAnswer: "+7",
    distractors: ["+4", "+6", "+5"],
  },
  {
    question: "What is the oxidation state of osmium in osmium tetroxide (OsO₄)?",
    correctAnswer: "+8",
    distractors: ["+6", "+4", "+7"],
  },
  {
    question: "What is the oxidation state of xenon in XeF₆?",
    correctAnswer: "+6",
    distractors: ["+4", "+8", "+2"],
  },
  {
    question: "What is the electron affinity of chlorine in kJ/mol?",
    correctAnswer: "−349 kJ/mol",
    distractors: ["−328 kJ/mol", "−364 kJ/mol", "−200 kJ/mol"],
  },
  {
    question: "What is the crystal field splitting energy designation for a strong-field octahedral d⁶ complex?",
    correctAnswer: "t₂g⁶ eg⁰ (low spin, 0 unpaired electrons)",
    distractors: ["t₂g⁴ eg² (high spin, 4 unpaired electrons)", "t₂g³ eg³ (3 unpaired electrons)", "t₂g⁵ eg¹ (1 unpaired electron)"],
  },
  {
    question: "What is the pKa of acetic acid at 25°C?",
    correctAnswer: "4.76",
    distractors: ["3.75", "5.25", "4.20"],
  },
  {
    question: "What is the pKa of phenol at 25°C?",
    correctAnswer: "9.95",
    distractors: ["7.40", "10.33", "8.50"],
  },
  {
    question: "What is the lattice energy of NaCl in kJ/mol?",
    correctAnswer: "786 kJ/mol",
    distractors: ["640 kJ/mol", "910 kJ/mol", "1,049 kJ/mol"],
  },
  {
    question: "What is the Madelung constant for the NaCl crystal structure?",
    correctAnswer: "1.74756",
    distractors: ["1.63806", "2.51939", "1.41421"],
  },
  {
    question: "What is the bond dissociation energy of N≡N (triple bond) in kJ/mol?",
    correctAnswer: "945 kJ/mol",
    distractors: ["498 kJ/mol", "1,072 kJ/mol", "799 kJ/mol"],
  },
  {
    question: "What is the standard reduction potential of fluorine (F₂/F⁻) in volts?",
    correctAnswer: "+2.87 V",
    distractors: ["+1.36 V", "+2.07 V", "+3.05 V"],
  },
  {
    question: "What is the standard reduction potential of lithium (Li⁺/Li) in volts?",
    correctAnswer: "−3.04 V",
    distractors: ["−2.71 V", "−3.45 V", "−2.37 V"],
  },
  {
    question: "What is the ionic radius of Na⁺ in picometers (6-coordinate)?",
    correctAnswer: "102 pm",
    distractors: ["95 pm", "116 pm", "138 pm"],
  },
  {
    question: "What is the coordination number of carbon in diamond?",
    correctAnswer: "4",
    distractors: ["6", "3", "8"],
  },
  {
    question: "What is the bond angle in a perfectly tetrahedral molecule?",
    correctAnswer: "109.47° (arccos(−1/3))",
    distractors: ["104.5°", "120°", "107.3°"],
  },
  {
    question: "What is the autoionization constant of water (Kw) at 25°C?",
    correctAnswer: "1.0 × 10⁻¹⁴",
    distractors: ["1.0 × 10⁻⁷", "1.0 × 10⁻¹⁰", "2.0 × 10⁻¹⁴"],
  },
  {
    question: "What is the density of iridium (second densest naturally occurring element) in g/cm³?",
    correctAnswer: "22.56 g/cm³",
    distractors: ["22.59 g/cm³", "21.45 g/cm³", "19.30 g/cm³"],
  },
  {
    question: "What is the half-life of Plutonium-239?",
    correctAnswer: "24,110 years",
    distractors: ["5,730 years", "87.7 years", "432 years"],
  },
  {
    question: "What is the half-life of Tritium (H-3)?",
    correctAnswer: "12.32 years",
    distractors: ["5.27 years", "28.8 years", "8.02 days"],
  },
  {
    question: "What is the critical temperature of mercury (superconductor)?",
    correctAnswer: "4.15 K",
    distractors: ["7.19 K", "1.18 K", "9.25 K"],
  },
  {
    question: "What is the critical temperature of the high-Tc superconductor YBCO (YBa₂Cu₃O₇)?",
    correctAnswer: "93 K",
    distractors: ["77 K", "138 K", "120 K"],
  },
  // ── Astrophysics ──────────────────────────────────────────────────────────
  {
    question: "What is the surface temperature of Betelgeuse in Kelvin?",
    correctAnswer: "≈ 3,600 K",
    distractors: ["≈ 5,778 K", "≈ 2,100 K", "≈ 4,500 K"],
  },
  {
    question: "What is the Jeans mass for a typical molecular cloud in solar masses?",
    correctAnswer: "≈ 1–10 M☉ (depending on conditions)",
    distractors: ["≈ 100–1,000 M☉", "≈ 0.001–0.01 M☉", "≈ 10,000 M☉"],
  },
  {
    question: "What is the Eddington luminosity limit for a solar-mass object in watts?",
    correctAnswer: "≈ 1.26 × 10³¹ W (≈ 3.3 × 10⁴ L☉)",
    distractors: ["≈ 3.83 × 10²⁶ W (1 L☉)", "≈ 1.26 × 10³⁸ W", "≈ 1.26 × 10²⁸ W"],
  },
  {
    question: "What is the orbital speed of the Sun around the Milky Way center?",
    correctAnswer: "≈ 230 km/s",
    distractors: ["≈ 30 km/s", "≈ 1,000 km/s", "≈ 500 km/s"],
  },
  {
    question: "What is the galactic rotation period of the Sun (one galactic year)?",
    correctAnswer: "≈ 225–250 million years",
    distractors: ["≈ 50 million years", "≈ 1 billion years", "≈ 500 million years"],
  },
  {
    question: "What is the Hubble tension value from CMB measurements (Planck)?",
    correctAnswer: "67.4 ± 0.5 km/s/Mpc",
    distractors: ["73.0 ± 1.0 km/s/Mpc", "70.0 ± 2.0 km/s/Mpc", "62.3 ± 1.3 km/s/Mpc"],
  },
  {
    question: "What is the Hubble tension value from local distance ladder measurements (SH0ES)?",
    correctAnswer: "73.0 ± 1.0 km/s/Mpc",
    distractors: ["67.4 ± 0.5 km/s/Mpc", "70.0 ± 2.0 km/s/Mpc", "78.2 ± 0.8 km/s/Mpc"],
  },
  {
    question: "What is the approximate baryon density parameter Ωb of the universe?",
    correctAnswer: "≈ 0.049 (about 5% of total energy density)",
    distractors: ["≈ 0.27 (about 27%)", "≈ 0.68 (about 68%)", "≈ 0.01 (about 1%)"],
  },
  {
    question: "What is the cosmic neutrino background temperature?",
    correctAnswer: "≈ 1.95 K",
    distractors: ["≈ 2.725 K", "≈ 0.97 K", "≈ 3.50 K"],
  },
  {
    question: "What is the Schwarzschild radius of the Sun in kilometers?",
    correctAnswer: "≈ 2.95 km",
    distractors: ["≈ 8.87 km", "≈ 0.89 km", "≈ 29.5 km"],
  },
  {
    question: "What is the mass of the supermassive black hole Sagittarius A* in solar masses?",
    correctAnswer: "≈ 4.0 × 10⁶ M☉",
    distractors: ["≈ 6.5 × 10⁹ M☉", "≈ 4.0 × 10⁴ M☉", "≈ 2.6 × 10⁷ M☉"],
  },
  {
    question: "What is the effective temperature of the cosmic microwave background?",
    correctAnswer: "2.7255 ± 0.0006 K",
    distractors: ["2.725 ± 0.010 K", "3.000 ± 0.001 K", "2.350 ± 0.005 K"],
  },
  {
    question: "What is the peak wavelength of the cosmic microwave background?",
    correctAnswer: "≈ 1.063 mm (microwave)",
    distractors: ["≈ 21 cm (radio)", "≈ 0.106 mm (far infrared)", "≈ 10.63 mm (microwave)"],
  },
  // ── Biology: Molecular & Cellular ──────────────────────────────────────────
  {
    question: "How many base pairs are in the human mitochondrial genome?",
    correctAnswer: "16,569 bp",
    distractors: ["13,794 bp", "18,200 bp", "22,561 bp"],
  },
  {
    question: "What is the resting membrane potential of a typical mammalian neuron?",
    correctAnswer: "≈ −70 mV",
    distractors: ["≈ −40 mV", "≈ −90 mV", "≈ −55 mV"],
  },
  {
    question: "What is the approximate diameter of a ribosome (prokaryotic 70S)?",
    correctAnswer: "≈ 20–25 nm",
    distractors: ["≈ 2–5 nm", "≈ 80–100 nm", "≈ 200 nm"],
  },
  {
    question: "How many ATP molecules are theoretically produced per glucose molecule in oxidative phosphorylation?",
    correctAnswer: "30–32 ATP (revised estimate)",
    distractors: ["36–38 ATP", "24–26 ATP", "2 ATP"],
  },
  {
    question: "What is the length of one turn of the DNA double helix (B-form)?",
    correctAnswer: "3.4 nm (10 base pairs per turn)",
    distractors: ["2.0 nm (8 base pairs per turn)", "5.1 nm (12 base pairs per turn)", "3.4 nm (12 base pairs per turn)"],
  },
  {
    question: "What is the Michaelis constant (Km) of carbonic anhydrase for CO₂?",
    correctAnswer: "≈ 12 mM",
    distractors: ["≈ 120 μM", "≈ 1.2 mM", "≈ 50 mM"],
  },
  {
    question: "What is the catalytic efficiency (kcat/Km) limit for diffusion-controlled enzymes?",
    correctAnswer: "≈ 10⁸–10⁹ M⁻¹s⁻¹",
    distractors: ["≈ 10⁶–10⁷ M⁻¹s⁻¹", "≈ 10¹⁰–10¹¹ M⁻¹s⁻¹", "≈ 10⁴–10⁵ M⁻¹s⁻¹"],
  },
  {
    question: "What is the approximate number of protein-coding genes in the human genome?",
    correctAnswer: "≈ 20,000–21,000",
    distractors: ["≈ 100,000–120,000", "≈ 5,000–8,000", "≈ 50,000–60,000"],
  },
  {
    question: "What is the approximate intracellular K⁺ concentration in mammalian cells?",
    correctAnswer: "≈ 140 mM",
    distractors: ["≈ 5 mM", "≈ 12 mM", "≈ 50 mM"],
  },
  {
    question: "What is the approximate extracellular Na⁺ concentration in mammalian cells?",
    correctAnswer: "≈ 145 mM",
    distractors: ["≈ 12 mM", "≈ 50 mM", "≈ 280 mM"],
  },
  {
    question: "What is the Nernst potential for potassium at 37°C (typical mammalian neuron)?",
    correctAnswer: "≈ −90 mV",
    distractors: ["≈ −70 mV", "≈ +60 mV", "≈ −120 mV"],
  },
  {
    question: "What is the genome size of E. coli K-12 in megabase pairs?",
    correctAnswer: "≈ 4.6 Mbp",
    distractors: ["≈ 1.8 Mbp", "≈ 12.1 Mbp", "≈ 3.2 Mbp"],
  },
  {
    question: "What is the sedimentation coefficient of the eukaryotic ribosome?",
    correctAnswer: "80S",
    distractors: ["70S", "60S", "100S"],
  },
  {
    question: "What is the error rate of DNA polymerase III (E. coli) per base pair?",
    correctAnswer: "≈ 10⁻⁷ (after proofreading, before mismatch repair)",
    distractors: ["≈ 10⁻⁴", "≈ 10⁻¹⁰", "≈ 10⁻²"],
  },
  {
    question: "How many chromosomes does a domestic dog (Canis lupus familiaris) have?",
    correctAnswer: "78 (39 pairs)",
    distractors: ["46 (23 pairs)", "64 (32 pairs)", "42 (21 pairs)"],
  },
  {
    question: "What is the approximate length of the human telomere at birth in kilobases?",
    correctAnswer: "≈ 10–15 kb",
    distractors: ["≈ 1–2 kb", "≈ 50–100 kb", "≈ 100–200 kb"],
  },
  {
    question: "What is the standard free energy change (ΔG°') for ATP hydrolysis at pH 7?",
    correctAnswer: "−30.5 kJ/mol (−7.3 kcal/mol)",
    distractors: ["−14.2 kJ/mol (−3.4 kcal/mol)", "−50.0 kJ/mol (−11.9 kcal/mol)", "−22.6 kJ/mol (−5.4 kcal/mol)"],
  },
  {
    question: "What is the number of codons in the standard genetic code?",
    correctAnswer: "64 (61 sense + 3 stop)",
    distractors: ["20 (one per amino acid)", "48 (16 × 3)", "128 (4⁷/2)"],
  },
  // ── Physics: Condensed Matter & Materials ──────────────────────────────────
  {
    question: "What is the band gap of silicon at room temperature in eV?",
    correctAnswer: "1.12 eV",
    distractors: ["0.67 eV", "1.42 eV", "0.36 eV"],
  },
  {
    question: "What is the band gap of gallium arsenide (GaAs) at room temperature in eV?",
    correctAnswer: "1.42 eV",
    distractors: ["1.12 eV", "0.67 eV", "2.26 eV"],
  },
  {
    question: "What is the Fermi energy of copper in eV?",
    correctAnswer: "≈ 7.0 eV",
    distractors: ["≈ 3.2 eV", "≈ 11.7 eV", "≈ 5.5 eV"],
  },
  {
    question: "What is the Curie temperature of iron in Kelvin?",
    correctAnswer: "1,043 K (770 °C)",
    distractors: ["631 K (358 °C)", "1,388 K (1,115 °C)", "858 K (585 °C)"],
  },
  {
    question: "What is the Curie temperature of nickel in Kelvin?",
    correctAnswer: "627 K (354 °C)",
    distractors: ["1,043 K (770 °C)", "394 K (121 °C)", "858 K (585 °C)"],
  },
  {
    question: "What is the Néel temperature of chromium?",
    correctAnswer: "311 K (38 °C)",
    distractors: ["100 K (−173 °C)", "525 K (252 °C)", "200 K (−73 °C)"],
  },
  {
    question: "What is the work function of gold in eV?",
    correctAnswer: "≈ 5.1 eV",
    distractors: ["≈ 4.3 eV", "≈ 2.3 eV", "≈ 6.4 eV"],
  },
  {
    question: "What is the Young's modulus of diamond in GPa?",
    correctAnswer: "≈ 1,050 GPa",
    distractors: ["≈ 200 GPa", "≈ 530 GPa", "≈ 1,800 GPa"],
  },
  {
    question: "What is the thermal conductivity of diamond at room temperature in W/(m·K)?",
    correctAnswer: "≈ 2,200 W/(m·K)",
    distractors: ["≈ 401 W/(m·K)", "≈ 1,000 W/(m·K)", "≈ 5,000 W/(m·K)"],
  },
  // ── Physics: Nuclear & Particle ────────────────────────────────────────────
  {
    question: "What is the binding energy per nucleon of Iron-56?",
    correctAnswer: "≈ 8.79 MeV/nucleon",
    distractors: ["≈ 7.07 MeV/nucleon", "≈ 9.52 MeV/nucleon", "≈ 8.55 MeV/nucleon"],
  },
  {
    question: "What is the most tightly bound nucleus per nucleon?",
    correctAnswer: "Nickel-62 (≈ 8.7945 MeV/nucleon)",
    distractors: ["Iron-56 (≈ 8.790 MeV/nucleon)", "Iron-58 (≈ 8.792 MeV/nucleon)", "Nickel-58 (≈ 8.732 MeV/nucleon)"],
  },
  {
    question: "What is the strong coupling constant αs at the Z boson mass scale?",
    correctAnswer: "≈ 0.1179",
    distractors: ["≈ 0.0073 (that is the fine-structure constant)", "≈ 1.0000", "≈ 0.0340"],
  },
  {
    question: "What is the Weinberg angle (weak mixing angle) sin²θ_W?",
    correctAnswer: "≈ 0.2312",
    distractors: ["≈ 0.5000", "≈ 0.1179", "≈ 0.3682"],
  },
  {
    question: "What is the mean lifetime of the charged pion (π⁺)?",
    correctAnswer: "≈ 26.0 ns (2.60 × 10⁻⁸ s)",
    distractors: ["≈ 2.20 μs (muon lifetime)", "≈ 8.52 × 10⁻¹⁷ s (neutral pion)", "≈ 1.24 × 10⁻⁸ s (charged kaon)"],
  },
  {
    question: "What is the spin of the Higgs boson?",
    correctAnswer: "0 (scalar boson)",
    distractors: ["1 (vector boson)", "2 (tensor boson)", "1/2 (fermion)"],
  },
  // ── Earth Sciences & Geophysics ────────────────────────────────────────────
  {
    question: "What is the age of the oldest known zircon crystals (Jack Hills, Australia) in billions of years?",
    correctAnswer: "≈ 4.404 billion years",
    distractors: ["≈ 3.8 billion years", "≈ 4.54 billion years", "≈ 2.7 billion years"],
  },
  {
    question: "What is the pressure at the center of the Earth in GPa?",
    correctAnswer: "≈ 360 GPa",
    distractors: ["≈ 136 GPa", "≈ 500 GPa", "≈ 50 GPa"],
  },
  {
    question: "What is the P-wave velocity at the base of the mantle in km/s?",
    correctAnswer: "≈ 13.7 km/s",
    distractors: ["≈ 8.1 km/s", "≈ 6.0 km/s", "≈ 20.0 km/s"],
  },
  {
    question: "What is the Mohorovičić discontinuity (Moho) depth under typical continental crust?",
    correctAnswer: "≈ 30–50 km",
    distractors: ["≈ 5–10 km", "≈ 100–200 km", "≈ 660 km"],
  },
  {
    question: "What is the current rate of Earth's magnetic pole drift in km/year (as of 2020s)?",
    correctAnswer: "≈ 50–60 km/year (accelerating)",
    distractors: ["≈ 5–10 km/year", "≈ 200 km/year", "≈ 1 km/year"],
  },
];

// ─── Geography Facts ─────────────────────────────────────────────────────────

export const GEOGRAPHY_FACTS: GeographyFact[] = [
  // ── Capitals: Obscure Nations ──────────────────────────────────────────────
  {
    country: "Comoros",
    statType: "capital",
    question: "What is the capital of Comoros?",
    correctAnswer: "Moroni",
    distractors: ["Mutsamudu", "Fomboni", "Domoni"],
  },
  {
    country: "São Tomé and Príncipe",
    statType: "capital",
    question: "What is the capital of São Tomé and Príncipe?",
    correctAnswer: "São Tomé",
    distractors: ["Santo Amaro", "Neves", "Guadalupe"],
  },
  {
    country: "Nauru",
    statType: "capital",
    question: "What is the de facto capital district of Nauru?",
    correctAnswer: "Yaren",
    distractors: ["Aiwo", "Buada", "Meneng"],
  },
  {
    country: "Tuvalu",
    statType: "capital",
    question: "What is the capital of Tuvalu?",
    correctAnswer: "Funafuti",
    distractors: ["Nanumea", "Vaitupu", "Nukufetau"],
  },
  {
    country: "Eswatini",
    statType: "capital",
    question: "What is the administrative capital of Eswatini?",
    correctAnswer: "Mbabane",
    distractors: ["Lobamba", "Manzini", "Siteki"],
  },
  {
    country: "Lesotho",
    statType: "capital",
    question: "What is the capital of Lesotho?",
    correctAnswer: "Maseru",
    distractors: ["Teyateyaneng", "Mafeteng", "Hlotse"],
  },
  {
    country: "Bhutan",
    statType: "capital",
    question: "What is the capital of Bhutan?",
    correctAnswer: "Thimphu",
    distractors: ["Paro", "Punakha", "Phuntsholing"],
  },
  {
    country: "Palau",
    statType: "capital",
    question: "What is the capital of Palau?",
    correctAnswer: "Ngerulmud",
    distractors: ["Koror", "Melekeok", "Airai"],
  },
  {
    country: "Kiribati",
    statType: "capital",
    question: "What is the capital of Kiribati?",
    correctAnswer: "South Tarawa",
    distractors: ["Kiritimati", "Butaritari", "Betio"],
  },
  {
    country: "Vanuatu",
    statType: "capital",
    question: "What is the capital of Vanuatu?",
    correctAnswer: "Port Vila",
    distractors: ["Luganville", "Isangel", "Lakatoro"],
  },
  {
    country: "Djibouti",
    statType: "capital",
    question: "What is the capital of Djibouti?",
    correctAnswer: "Djibouti City",
    distractors: ["Ali Sabieh", "Tadjoura", "Obock"],
  },
  {
    country: "Equatorial Guinea",
    statType: "capital",
    question: "What is the capital of Equatorial Guinea?",
    correctAnswer: "Malabo",
    distractors: ["Bata", "Ebebiyín", "Mongomo"],
  },
  {
    country: "Guinea-Bissau",
    statType: "capital",
    question: "What is the capital of Guinea-Bissau?",
    correctAnswer: "Bissau",
    distractors: ["Bafatá", "Gabú", "Cacheu"],
  },
  {
    country: "Timor-Leste",
    statType: "capital",
    question: "What is the capital of Timor-Leste (East Timor)?",
    correctAnswer: "Dili",
    distractors: ["Baucau", "Maliana", "Suai"],
  },
  {
    country: "Suriname",
    statType: "capital",
    question: "What is the capital of Suriname?",
    correctAnswer: "Paramaribo",
    distractors: ["Nieuw Nickerie", "Lelydorp", "Brokopondo"],
  },
  {
    country: "Brunei",
    statType: "capital",
    question: "What is the capital of Brunei?",
    correctAnswer: "Bandar Seri Begawan",
    distractors: ["Seria", "Tutong", "Temburong"],
  },
  {
    country: "Eswatini",
    statType: "capital",
    question: "What is the legislative and royal capital of Eswatini?",
    correctAnswer: "Lobamba",
    distractors: ["Mbabane", "Manzini", "Siteki"],
  },
  {
    country: "Micronesia",
    statType: "capital",
    question: "What is the capital of the Federated States of Micronesia?",
    correctAnswer: "Palikir",
    distractors: ["Weno", "Kolonia", "Tofol"],
  },
  {
    country: "Marshall Islands",
    statType: "capital",
    question: "What is the capital of the Marshall Islands?",
    correctAnswer: "Majuro",
    distractors: ["Ebeye", "Kwajalein", "Jabor"],
  },
  {
    country: "Solomon Islands",
    statType: "capital",
    question: "What is the capital of the Solomon Islands?",
    correctAnswer: "Honiara",
    distractors: ["Gizo", "Auki", "Tulagi"],
  },
  {
    country: "Myanmar",
    statType: "capital",
    question: "What is the capital of Myanmar?",
    correctAnswer: "Naypyidaw",
    distractors: ["Yangon", "Mandalay", "Bago"],
  },
  {
    country: "Sri Lanka",
    statType: "capital",
    question: "What is the legislative capital of Sri Lanka?",
    correctAnswer: "Sri Jayawardenepura Kotte",
    distractors: ["Colombo", "Kandy", "Galle"],
  },
  {
    country: "Ivory Coast",
    statType: "capital",
    question: "What is the official capital of Côte d'Ivoire?",
    correctAnswer: "Yamoussoukro",
    distractors: ["Abidjan", "Bouaké", "Daloa"],
  },
  {
    country: "Bolivia",
    statType: "capital",
    question: "What is the constitutional (judicial) capital of Bolivia?",
    correctAnswer: "Sucre",
    distractors: ["La Paz", "Santa Cruz de la Sierra", "Cochabamba"],
  },
  {
    country: "Tanzania",
    statType: "capital",
    question: "What is the official capital of Tanzania?",
    correctAnswer: "Dodoma",
    distractors: ["Dar es Salaam", "Arusha", "Mwanza"],
  },
  // ── Population: Obscure Nations (to nearest 100K) ──────────────────────────
  {
    country: "Comoros",
    statType: "population",
    question: "What is the approximate population of Comoros?",
    correctAnswer: "Approximately 900,000",
    distractors: ["Approximately 400,000", "Approximately 1,500,000", "Approximately 2,200,000"],
  },
  {
    country: "São Tomé and Príncipe",
    statType: "population",
    question: "What is the approximate population of São Tomé and Príncipe?",
    correctAnswer: "Approximately 230,000",
    distractors: ["Approximately 500,000", "Approximately 100,000", "Approximately 1,000,000"],
  },
  {
    country: "Nauru",
    statType: "population",
    question: "What is the approximate population of Nauru?",
    correctAnswer: "Approximately 12,500",
    distractors: ["Approximately 50,000", "Approximately 100,000", "Approximately 2,000"],
  },
  {
    country: "Tuvalu",
    statType: "population",
    question: "What is the approximate population of Tuvalu?",
    correctAnswer: "Approximately 11,200",
    distractors: ["Approximately 50,000", "Approximately 100,000", "Approximately 3,500"],
  },
  {
    country: "Palau",
    statType: "population",
    question: "What is the approximate population of Palau?",
    correctAnswer: "Approximately 18,000",
    distractors: ["Approximately 100,000", "Approximately 50,000", "Approximately 5,000"],
  },
  {
    country: "Eswatini",
    statType: "population",
    question: "What is the approximate population of Eswatini?",
    correctAnswer: "Approximately 1,200,000",
    distractors: ["Approximately 600,000", "Approximately 2,300,000", "Approximately 3,500,000"],
  },
  {
    country: "Lesotho",
    statType: "population",
    question: "What is the approximate population of Lesotho?",
    correctAnswer: "Approximately 2,300,000",
    distractors: ["Approximately 1,200,000", "Approximately 4,000,000", "Approximately 800,000"],
  },
  {
    country: "Bhutan",
    statType: "population",
    question: "What is the approximate population of Bhutan?",
    correctAnswer: "Approximately 780,000",
    distractors: ["Approximately 1,500,000", "Approximately 350,000", "Approximately 3,000,000"],
  },
  {
    country: "Djibouti",
    statType: "population",
    question: "What is the approximate population of Djibouti?",
    correctAnswer: "Approximately 1,000,000",
    distractors: ["Approximately 500,000", "Approximately 2,200,000", "Approximately 3,500,000"],
  },
  {
    country: "Equatorial Guinea",
    statType: "population",
    question: "What is the approximate population of Equatorial Guinea?",
    correctAnswer: "Approximately 1,700,000",
    distractors: ["Approximately 600,000", "Approximately 3,200,000", "Approximately 5,000,000"],
  },
  {
    country: "Guinea-Bissau",
    statType: "population",
    question: "What is the approximate population of Guinea-Bissau?",
    correctAnswer: "Approximately 2,100,000",
    distractors: ["Approximately 800,000", "Approximately 4,000,000", "Approximately 5,500,000"],
  },
  {
    country: "Kiribati",
    statType: "population",
    question: "What is the approximate population of Kiribati?",
    correctAnswer: "Approximately 130,000",
    distractors: ["Approximately 50,000", "Approximately 300,000", "Approximately 500,000"],
  },
  {
    country: "Vanuatu",
    statType: "population",
    question: "What is the approximate population of Vanuatu?",
    correctAnswer: "Approximately 330,000",
    distractors: ["Approximately 100,000", "Approximately 700,000", "Approximately 1,200,000"],
  },
  {
    country: "Suriname",
    statType: "population",
    question: "What is the approximate population of Suriname?",
    correctAnswer: "Approximately 620,000",
    distractors: ["Approximately 200,000", "Approximately 1,400,000", "Approximately 3,000,000"],
  },
  {
    country: "Brunei",
    statType: "population",
    question: "What is the approximate population of Brunei?",
    correctAnswer: "Approximately 450,000",
    distractors: ["Approximately 200,000", "Approximately 1,000,000", "Approximately 2,500,000"],
  },
  {
    country: "Timor-Leste",
    statType: "population",
    question: "What is the approximate population of Timor-Leste?",
    correctAnswer: "Approximately 1,300,000",
    distractors: ["Approximately 600,000", "Approximately 2,800,000", "Approximately 4,000,000"],
  },
  // ── Area: Obscure Nations (km²) ────────────────────────────────────────────
  {
    country: "Nauru",
    statType: "area",
    question: "What is the approximate area of Nauru?",
    correctAnswer: "21 km²",
    distractors: ["300 km²", "2.6 km²", "115 km²"],
  },
  {
    country: "Tuvalu",
    statType: "area",
    question: "What is the approximate area of Tuvalu?",
    correctAnswer: "26 km²",
    distractors: ["160 km²", "2 km²", "316 km²"],
  },
  {
    country: "San Marino",
    statType: "area",
    question: "What is the approximate area of San Marino?",
    correctAnswer: "61 km²",
    distractors: ["316 km²", "160 km²", "21 km²"],
  },
  {
    country: "Liechtenstein",
    statType: "area",
    question: "What is the approximate area of Liechtenstein?",
    correctAnswer: "160 km²",
    distractors: ["460 km²", "61 km²", "2,586 km²"],
  },
  {
    country: "Monaco",
    statType: "area",
    question: "What is the approximate area of Monaco?",
    correctAnswer: "2.02 km²",
    distractors: ["21 km²", "0.44 km²", "61 km²"],
  },
  {
    country: "Vatican City",
    statType: "area",
    question: "What is the approximate area of Vatican City?",
    correctAnswer: "0.44 km²",
    distractors: ["2.02 km²", "4.4 km²", "0.044 km²"],
  },
  {
    country: "Comoros",
    statType: "area",
    question: "What is the approximate area of Comoros?",
    correctAnswer: "1,862 km²",
    distractors: ["587 km²", "4,033 km²", "11,295 km²"],
  },
  {
    country: "São Tomé and Príncipe",
    statType: "area",
    question: "What is the approximate area of São Tomé and Príncipe?",
    correctAnswer: "964 km²",
    distractors: ["2,170 km²", "455 km²", "316 km²"],
  },
  {
    country: "Eswatini",
    statType: "area",
    question: "What is the approximate area of Eswatini?",
    correctAnswer: "17,364 km²",
    distractors: ["30,355 km²", "11,586 km²", "6,704 km²"],
  },
  {
    country: "Lesotho",
    statType: "area",
    question: "What is the approximate area of Lesotho?",
    correctAnswer: "30,355 km²",
    distractors: ["17,364 km²", "56,785 km²", "11,720 km²"],
  },
  {
    country: "Bhutan",
    statType: "area",
    question: "What is the approximate area of Bhutan?",
    correctAnswer: "38,394 km²",
    distractors: ["14,824 km²", "65,610 km²", "47,000 km²"],
  },
  {
    country: "Djibouti",
    statType: "area",
    question: "What is the approximate area of Djibouti?",
    correctAnswer: "23,200 km²",
    distractors: ["11,586 km²", "42,000 km²", "56,785 km²"],
  },
  {
    country: "Brunei",
    statType: "area",
    question: "What is the approximate area of Brunei?",
    correctAnswer: "5,765 km²",
    distractors: ["2,040 km²", "11,300 km²", "28,900 km²"],
  },
  {
    country: "Timor-Leste",
    statType: "area",
    question: "What is the approximate area of Timor-Leste?",
    correctAnswer: "14,874 km²",
    distractors: ["5,765 km²", "28,748 km²", "38,394 km²"],
  },
  // ── Highest Points: Obscure Nations ────────────────────────────────────────
  {
    country: "Luxembourg",
    statType: "area",
    question: "What is the highest point of Luxembourg and its elevation?",
    correctAnswer: "Kneiff at 560 m",
    distractors: ["Buurgplaatz at 559 m", "Huldange at 530 m", "Wemperhardt at 545 m"],
  },
  {
    country: "Lesotho",
    statType: "area",
    question: "What is the highest point of Lesotho?",
    correctAnswer: "Thabana Ntlenyana at 3,482 m",
    distractors: ["Mont aux Sources at 3,282 m", "Mafadi at 3,450 m", "Champagne Castle at 3,377 m"],
  },
  {
    country: "Bhutan",
    statType: "area",
    question: "What is the highest point of Bhutan?",
    correctAnswer: "Gangkhar Puensum at 7,570 m",
    distractors: ["Kula Kangri at 7,554 m", "Jomolhari at 7,326 m", "Jichu Drake at 6,989 m"],
  },
  {
    country: "Comoros",
    statType: "area",
    question: "What is the highest point of Comoros?",
    correctAnswer: "Mount Karthala at 2,361 m",
    distractors: ["Mount Ntingui at 1,595 m", "Mount Mlédjélé at 790 m", "Pico de São Tomé at 2,024 m"],
  },
  {
    country: "Maldives",
    statType: "area",
    question: "What is the highest point of the Maldives?",
    correctAnswer: "An unnamed point on Addu Atoll at 5.1 m",
    distractors: ["Mount Villingili at 17 m", "A point on Malé at 2.4 m", "Fuvahmulah peak at 8.0 m"],
  },
  {
    country: "Nauru",
    statType: "area",
    question: "What is the highest point of Nauru?",
    correctAnswer: "Command Ridge at 71 m",
    distractors: ["Buada Lagoon rim at 30 m", "Nauru Plateau at 95 m", "Central Plateau at 110 m"],
  },
  {
    country: "Tuvalu",
    statType: "area",
    question: "What is the highest point of Tuvalu?",
    correctAnswer: "An unnamed point on Niulakita at 4.6 m",
    distractors: ["Funafuti peak at 8 m", "A point on Nanumea at 12 m", "Vaitupu summit at 6 m"],
  },
  {
    country: "Eswatini",
    statType: "area",
    question: "What is the highest point of Eswatini?",
    correctAnswer: "Emlembe at 1,862 m",
    distractors: ["Bulembu at 1,600 m", "Ngwenya at 1,829 m", "Piggs Peak at 1,740 m"],
  },
  // ── Population: Additional Obscure Nations ─────────────────────────────────
  {
    country: "Marshall Islands",
    statType: "population",
    question: "What is the approximate population of the Marshall Islands?",
    correctAnswer: "Approximately 42,000",
    distractors: ["Approximately 100,000", "Approximately 15,000", "Approximately 200,000"],
  },
  {
    country: "Micronesia",
    statType: "population",
    question: "What is the approximate population of the Federated States of Micronesia?",
    correctAnswer: "Approximately 115,000",
    distractors: ["Approximately 50,000", "Approximately 250,000", "Approximately 500,000"],
  },
  {
    country: "Tonga",
    statType: "population",
    question: "What is the approximate population of Tonga?",
    correctAnswer: "Approximately 100,000",
    distractors: ["Approximately 300,000", "Approximately 25,000", "Approximately 500,000"],
  },
  {
    country: "Seychelles",
    statType: "population",
    question: "What is the approximate population of the Seychelles?",
    correctAnswer: "Approximately 100,000",
    distractors: ["Approximately 300,000", "Approximately 30,000", "Approximately 500,000"],
  },
  {
    country: "Samoa",
    statType: "population",
    question: "What is the approximate population of Samoa?",
    correctAnswer: "Approximately 220,000",
    distractors: ["Approximately 500,000", "Approximately 50,000", "Approximately 1,000,000"],
  },
  {
    country: "Dominica",
    statType: "population",
    question: "What is the approximate population of Dominica?",
    correctAnswer: "Approximately 72,000",
    distractors: ["Approximately 200,000", "Approximately 20,000", "Approximately 400,000"],
  },
  {
    country: "Saint Kitts and Nevis",
    statType: "population",
    question: "What is the approximate population of Saint Kitts and Nevis?",
    correctAnswer: "Approximately 54,000",
    distractors: ["Approximately 150,000", "Approximately 15,000", "Approximately 300,000"],
  },
  {
    country: "Liechtenstein",
    statType: "population",
    question: "What is the approximate population of Liechtenstein?",
    correctAnswer: "Approximately 39,000",
    distractors: ["Approximately 100,000", "Approximately 10,000", "Approximately 200,000"],
  },
  {
    country: "San Marino",
    statType: "population",
    question: "What is the approximate population of San Marino?",
    correctAnswer: "Approximately 33,000",
    distractors: ["Approximately 80,000", "Approximately 10,000", "Approximately 150,000"],
  },
  {
    country: "Monaco",
    statType: "population",
    question: "What is the approximate population of Monaco?",
    correctAnswer: "Approximately 39,000",
    distractors: ["Approximately 100,000", "Approximately 10,000", "Approximately 200,000"],
  },
];

// ─── Historical Events ───────────────────────────────────────────────────────

export const HISTORICAL_EVENTS: HistoricalEvent[] = [
  // ── Treaties & Diplomatic ──────────────────────────────────────────────────
  { event: "Treaty of Tordesillas divides New World between Spain and Portugal", year: 1494 },
  { event: "Peace of Augsburg establishes cuius regio, eius religio", year: 1555 },
  { event: "Treaty of Westphalia ends the Thirty Years' War", year: 1648 },
  { event: "Treaty of Nerchinsk (first treaty between Russia and China)", year: 1689 },
  { event: "Treaty of Küçük Kaynarca (Russia gains Crimea access)", year: 1774 },
  { event: "Treaty of Tilsit between Napoleon and Alexander I", year: 1807 },
  { event: "Treaty of Nanking ends the First Opium War", year: 1842 },
  { event: "Treaty of San Stefano (temporary end of Russo-Turkish War)", year: 1878 },
  { event: "Treaty of Portsmouth ends the Russo-Japanese War", year: 1905 },
  { event: "Treaty of Sèvres partitions the Ottoman Empire", year: 1920 },
  { event: "Treaty of Lausanne replaces Treaty of Sèvres, recognizes Turkey", year: 1923 },
  { event: "Treaty of Rapallo (Weimar Germany recognizes Soviet Russia)", year: 1922 },
  { event: "Molotov-Ribbentrop Pact (Nazi-Soviet non-aggression pact)", year: 1939 },
  { event: "Treaty of Rome establishes the European Economic Community", year: 1957 },
  { event: "Camp David Accords between Egypt and Israel", year: 1978 },
  { event: "Maastricht Treaty establishes the European Union", year: 1992 },
  // ── Scientific Discoveries & Milestones ────────────────────────────────────
  { event: "William Harvey publishes De Motu Cordis (blood circulation)", year: 1628 },
  { event: "Robert Hooke publishes Micrographia, coins the term 'cell'", year: 1665 },
  { event: "Antonie van Leeuwenhoek first observes bacteria", year: 1676 },
  { event: "Newton publishes Principia Mathematica", year: 1687 },
  { event: "Leonhard Euler publishes Introductio in analysin infinitorum", year: 1748 },
  { event: "Antoine Lavoisier identifies oxygen's role in combustion", year: 1778 },
  { event: "Edward Jenner performs the first smallpox vaccination", year: 1796 },
  { event: "Hans Christian Ørsted discovers electromagnetism", year: 1820 },
  { event: "Michael Faraday discovers electromagnetic induction", year: 1831 },
  { event: "Friedrich Wöhler synthesizes urea (organic from inorganic)", year: 1828 },
  { event: "Gregor Mendel publishes his laws of heredity", year: 1866 },
  { event: "Dmitri Mendeleev publishes the first periodic table", year: 1869 },
  { event: "James Clerk Maxwell publishes A Treatise on Electricity and Magnetism", year: 1873 },
  { event: "Robert Koch identifies the tuberculosis bacillus", year: 1882 },
  { event: "Heinrich Hertz produces and detects electromagnetic waves", year: 1887 },
  { event: "Wilhelm Röntgen discovers X-rays", year: 1895 },
  { event: "Henri Becquerel discovers radioactivity", year: 1896 },
  { event: "J.J. Thomson discovers the electron", year: 1897 },
  { event: "Max Planck introduces the quantum hypothesis", year: 1900 },
  { event: "Albert Einstein publishes the photoelectric effect paper", year: 1905 },
  { event: "Ernest Rutherford proposes the nuclear model of the atom", year: 1911 },
  { event: "Niels Bohr proposes his model of the hydrogen atom", year: 1913 },
  { event: "Arthur Eddington confirms general relativity during solar eclipse", year: 1919 },
  { event: "Werner Heisenberg formulates matrix mechanics", year: 1925 },
  { event: "Erwin Schrödinger publishes the wave equation", year: 1926 },
  { event: "Paul Dirac predicts the positron (antimatter)", year: 1928 },
  { event: "Carl Anderson experimentally discovers the positron", year: 1932 },
  { event: "James Chadwick discovers the neutron", year: 1932 },
  { event: "Enrico Fermi achieves first controlled nuclear chain reaction (Chicago Pile-1)", year: 1942 },
  { event: "Watson and Crick determine the structure of DNA", year: 1953 },
  { event: "Sputnik 1, first artificial satellite, is launched", year: 1957 },
  { event: "First laser (Theodore Maiman, ruby laser) demonstrated", year: 1960 },
  { event: "Murray Gell-Mann proposes the quark model", year: 1964 },
  { event: "Arno Penzias and Robert Wilson discover the cosmic microwave background", year: 1965 },
  { event: "First pulsar discovered by Jocelyn Bell Burnell", year: 1967 },
  { event: "Standard Model of particle physics formulated", year: 1973 },
  { event: "Dolly the sheep cloned (first mammal from adult somatic cell)", year: 1996 },
  { event: "LIGO detects gravitational waves for the first time (GW150914)", year: 2015 },
  { event: "First image of a black hole (M87*) by Event Horizon Telescope", year: 2019 },
  // ── Political Events & Conflicts ───────────────────────────────────────────
  { event: "Defenestration of Prague (triggers Thirty Years' War)", year: 1618 },
  { event: "Execution of King Charles I of England", year: 1649 },
  { event: "Glorious Revolution deposes James II of England", year: 1688 },
  { event: "War of the Spanish Succession begins", year: 1701 },
  { event: "Seven Years' War begins (global conflict)", year: 1756 },
  { event: "Haitian Revolution begins (largest successful slave revolt)", year: 1791 },
  { event: "Decembrist Revolt in Russia", year: 1825 },
  { event: "Revolutions of 1848 sweep across Europe", year: 1848 },
  { event: "Taiping Rebellion begins in China", year: 1850 },
  { event: "Meiji Restoration in Japan", year: 1868 },
  { event: "Berlin Conference begins the Scramble for Africa", year: 1884 },
  { event: "Dreyfus Affair begins in France", year: 1894 },
  { event: "Boxer Rebellion in China", year: 1900 },
  { event: "Russian Revolution (Bloody Sunday)", year: 1905 },
  { event: "Young Turk Revolution in the Ottoman Empire", year: 1908 },
  { event: "Chinese Revolution overthrows the Qing Dynasty", year: 1911 },
  { event: "Balfour Declaration supports Jewish homeland in Palestine", year: 1917 },
  { event: "Turkish War of Independence begins under Atatürk", year: 1919 },
  { event: "Kristallnacht (Night of Broken Glass)", year: 1938 },
  { event: "Indian Partition and Independence", year: 1947 },
  { event: "People's Republic of China proclaimed by Mao Zedong", year: 1949 },
  { event: "Bandung Conference (Non-Aligned Movement origins)", year: 1955 },
  { event: "Suez Crisis (Anglo-French-Israeli invasion of Egypt)", year: 1956 },
  { event: "Cuban Revolution succeeds under Castro", year: 1959 },
  { event: "Sino-Soviet split becomes public", year: 1960 },
  { event: "Prague Spring crushed by Soviet invasion", year: 1968 },
  { event: "Yom Kippur War (October War)", year: 1973 },
  { event: "Iranian Revolution (Shah overthrown)", year: 1979 },
  { event: "Solidarność (Solidarity) movement founded in Poland", year: 1980 },
  { event: "Chernobyl nuclear disaster", year: 1986 },
  { event: "Tiananmen Square massacre in Beijing", year: 1989 },
  { event: "Rwandan genocide begins", year: 1994 },
  // ── Cultural & Intellectual Milestones ─────────────────────────────────────
  { event: "Gutenberg Bible printed (first major book printed with movable type)", year: 1455 },
  { event: "Rosetta Stone discovered by French soldiers in Egypt", year: 1799 },
  { event: "Niccolò Machiavelli writes The Prince", year: 1513 },
  { event: "Copernicus publishes De revolutionibus orbium coelestium", year: 1543 },
  { event: "Galileo's Dialogue Concerning the Two Chief World Systems published", year: 1632 },
  { event: "Encyclopédie edited by Diderot and d'Alembert first published", year: 1751 },
  { event: "Adam Smith publishes The Wealth of Nations", year: 1776 },
  { event: "Mary Wollstonecraft publishes A Vindication of the Rights of Woman", year: 1792 },
  { event: "Jean-François Champollion deciphers Egyptian hieroglyphs", year: 1822 },
  { event: "Charles Darwin publishes On the Origin of Species", year: 1859 },
  { event: "Karl Marx publishes Das Kapital (Volume I)", year: 1867 },
  { event: "First Nobel Prizes awarded", year: 1901 },
  { event: "Sigmund Freud publishes The Interpretation of Dreams", year: 1900 },
  { event: "Ludwig Wittgenstein publishes Tractatus Logico-Philosophicus", year: 1921 },
  { event: "Kurt Gödel publishes incompleteness theorems", year: 1931 },
  { event: "Alan Turing publishes On Computable Numbers (Turing machine)", year: 1936 },
  { event: "Claude Shannon publishes A Mathematical Theory of Communication", year: 1948 },
  { event: "First edition of Bourbaki's Éléments de mathématique published", year: 1939 },
  // ── Ancient & Medieval (less commonly known) ──────────────────────────────
  { event: "Library of Alexandria traditionally said to have been founded", year: -283 },
  { event: "Archimedes killed during the Siege of Syracuse", year: -212 },
  { event: "Eruption of Mount Vesuvius destroys Pompeii and Herculaneum", year: 79 },
  { event: "Council of Nicaea (first ecumenical council)", year: 325 },
  { event: "Fall of the Western Roman Empire (deposition of Romulus Augustulus)", year: 476 },
  { event: "Justinian's Corpus Juris Civilis codification of Roman law", year: 529 },
  { event: "Battle of Tours (Charles Martel halts Umayyad advance into Western Europe)", year: 732 },
  { event: "Coronation of Charlemagne as Holy Roman Emperor", year: 800 },
  { event: "Great Schism between Eastern and Western Christianity", year: 1054 },
  { event: "Mongol conquest of Baghdad (end of the Abbasid Caliphate)", year: 1258 },
  { event: "Black Death reaches Europe", year: 1347 },
  { event: "Fall of Constantinople to the Ottoman Turks", year: 1453 },
];

// ─── Math Constants ──────────────────────────────────────────────────────────

export const MATH_CONSTANTS: MathConstant[] = [
  { name: "Pi", symbol: "π", value: "3.14159265358979323846264338327950288419716939937510" },
  { name: "Euler's number", symbol: "e", value: "2.71828182845904523536028747135266249775724709369995" },
  { name: "Square root of 2", symbol: "√2", value: "1.41421356237309504880168872420969807856967187537694" },
  { name: "Golden ratio", symbol: "φ", value: "1.61803398874989484820458683436563811772030917980576" },
  { name: "Natural log of 2", symbol: "ln(2)", value: "0.69314718055994530941723212145817656807550013436025" },
  { name: "Square root of 3", symbol: "√3", value: "1.73205080756887729352744634150587236694280525381038" },
  { name: "Square root of 5", symbol: "√5", value: "2.23606797749978969640917366873127623544061835961152" },
  { name: "Euler-Mascheroni constant", symbol: "γ", value: "0.57721566490153286060651209008240243104215933593992" },
  { name: "Catalan's constant", symbol: "G", value: "0.91596559417721901505460351493238411077414937428167" },
  { name: "Apéry's constant", symbol: "ζ(3)", value: "1.20205690315959428539973816151144999076498629234049" },
  { name: "Khinchin's constant", symbol: "K₀", value: "2.68545200106530644530971483548179569382038229399446" },
  { name: "Feigenbaum constant delta", symbol: "δ", value: "4.66920160910299067185320382046620161725818557747576" },
  { name: "Feigenbaum constant alpha", symbol: "α", value: "2.50290787509589282228390287321821578638127137672714" },
  { name: "Twin prime constant", symbol: "C₂", value: "0.66016181584686957392781211001455577843262336028473" },
  { name: "Conway's constant", symbol: "λ", value: "1.30357726903429639125709911215255189073070250465940" },
  { name: "Plastic number", symbol: "ρ", value: "1.32471795724474602596090885447809734073440405690173" },
  { name: "Silver ratio", symbol: "δₛ", value: "2.41421356237309504880168872420969807856967187537694" },
  { name: "Ramanujan-Soldner constant", symbol: "μ", value: "1.45136923488338105028396848589202744949303228364207" },
  { name: "Erdős-Borwein constant", symbol: "E", value: "1.60669515241529176378330152319092458048081553803296" },
  { name: "Omega constant", symbol: "Ω", value: "0.56714329040978387299996866221035554975381578718651" },
  { name: "Meissel-Mertens constant", symbol: "M", value: "0.26149721284764278375542683860869585905156664826120" },
  { name: "Universal parabolic constant", symbol: "P", value: "2.29558714939263807403429804918949038759783220363010" },
  { name: "Glaisher-Kinkelin constant", symbol: "A", value: "1.28242712910062263687534256886979172776768892732500" },
  { name: "Bernstein's constant", symbol: "β", value: "0.28016949902386913303643649123067200000000000000000" },
  { name: "Gauss's constant (1/agm(1,√2))", symbol: "G_gauss", value: "0.83462684167407318628142973279904680899399301349034" },
  { name: "Landau-Ramanujan constant", symbol: "K", value: "0.76422365358922066299069873125009232811679054139340" },
  { name: "Lévy's constant (π²/(12·ln(2)))", symbol: "β_Lévy", value: "1.18656911041562545282172297621578970811513960127968" },
  { name: "Reciprocal Fibonacci constant", symbol: "ψ", value: "3.35988566624317755317201130291892717968890513373197" },
  { name: "Sophomore's dream (∫₀¹ x⁻ˣ dx)", symbol: "I₁", value: "1.29128599706266354040728259059560054149861936827163" },
  { name: "Lemniscate constant", symbol: "ϖ", value: "2.62205755429211981046483958989111941368275495143162" },
  { name: "Natural log of 10", symbol: "ln(10)", value: "2.30258509299404568401799145468436420760110148862877" },
  { name: "Pi squared over 6 (Basel problem)", symbol: "ζ(2)", value: "1.64493406684822643647241516664602518921894990120680" },
];
