import { RARE_WORDS_EXT_1 } from "./words-ext-1";
import { RARE_WORDS_EXT_2 } from "./words-ext-2";
import { SPELLING_WORDS_EXT } from "./spelling-ext";
import { ANALOGY_PAIRS_EXT } from "./analogies-ext";

export interface RareWord {
  word: string;
  definition: string;
  distractors: [string, string, string];
}

export const RARE_WORDS: RareWord[] = [
  { word: "apophasis", definition: "A rhetorical device in which the speaker mentions something by explicitly denying that it will be mentioned", distractors: ["A formal statement of retraction issued before a tribunal", "The omission of conjunctions between clauses in a sentence", "A philosophical proof by contradiction"] },
  { word: "tmesis", definition: "The separation of parts of a compound word by an intervening word or words", distractors: ["A surgical incision into the thymus gland", "The process of binary fission in prokaryotic cells", "A rhetorical pause inserted for dramatic effect"] },
  { word: "paraprosdokian", definition: "A figure of speech in which the latter part of a sentence or phrase is surprising in a way that causes the reader to reframe the first part", distractors: ["A logical fallacy in which two premises are assumed to share a middle term", "A verse form in which alternating lines contradict each other", "A medical attendant who assists during surgical procedures"] },
  { word: "apagoge", definition: "Indirect proof by showing absurdity of the opposite", distractors: ["A type of formal syllogism", "Removal of a logical proposition", "An argument from lesser to greater"] },
  { word: "bathypelagic", definition: "Relating to or living in the ocean at depths between 1000 and 4000 meters", distractors: ["Pertaining to the study of deep emotional states in psychoanalysis", "Relating to extremely low-frequency sound waves in geology", "Describing organisms that thrive in high-pressure volcanic vents"] },
  { word: "defervescence", definition: "The abatement or subsidence of a fever", distractors: ["The gradual loss of effervescence in a carbonated solution", "The decline of religious fervor within a population", "The process by which enthusiasm diminishes after an initial surge"] },
  { word: "idiopathic", definition: "Relating to or denoting any disease or condition that arises spontaneously or for which the cause is unknown", distractors: ["Pertaining to a pathological obsession with one's own identity", "Describing a sympathetic nervous system response unique to an individual", "Relating to diseases that affect only a single organ system"] },
  { word: "apodeictic", definition: "Clearly established or beyond dispute; necessarily true", distractors: ["Pertaining to the art of formal public speaking", "Derived from empirical observation rather than logical proof", "Expressing a conditional or hypothetical proposition"] },
  { word: "sesquipedalianism", definition: "The practice or habit of using long, sometimes obscure words in speech or writing", distractors: ["A measurement system based on intervals of one and one-half units", "The study of bipedal locomotion in paleontological contexts", "A philosophical doctrine emphasizing sequential reasoning"] },
  { word: "borborygmus", definition: "A rumbling or gurgling noise produced by the movement of fluid and gas in the intestines", distractors: ["A form of Gregorian chant characterized by deep sustained tones", "A geological phenomenon involving subterranean gas venting", "A speech impediment marked by involuntary repetition of guttural sounds"] },
  { word: "proprioception", definition: "The unconscious perception of movement and spatial orientation arising from stimuli within the body itself", distractors: ["The cognitive bias of perceiving oneself as the owner of observed actions", "The philosophical concept of exclusive self-knowledge prior to experience", "The ability to detect chemical changes in one's own bloodstream"] },
  { word: "eschar", definition: "A dry, dark scab or slough formed on the skin as a result of a burn or by the action of a corrosive substance", distractors: ["A calcified deposit found in the renal pelvis", "The fibrous tissue that forms between severed nerve endings", "A layer of necrotic cartilage resulting from septic arthritis"] },
  { word: "fasciculation", definition: "A brief, spontaneous involuntary contraction affecting a small number of muscle fibers, often visible as a flicker under the skin", distractors: ["The process by which nerve fibers are bundled into fascicles during embryogenesis", "A surgical technique for reattaching severed ligaments in bundles", "The rhythmic oscillation of smooth muscle in the gastrointestinal tract"] },
  { word: "erythropoiesis", definition: "The production of red blood cells in the bone marrow", distractors: ["The breakdown of red blood cells by the spleen and liver", "The formation of erythematous lesions in autoimmune disorders", "The process by which hemoglobin molecules bind to oxygen"] },
  { word: "pretermission", definition: "The rhetorical act of mentioning something by saying you won't mention it", distractors: ["Formal suspension of parliamentary rules", "Voluntary relinquishment of a legal right", "The expiration of a statutory deadline"] },
  { word: "deosculation", definition: "The act of kissing", distractors: ["Formal removal of a sacred designation", "The process of bone resorption", "Astronomical calculation of orbital decay"] },
  { word: "apozemical", definition: "Relating to a decoction or medicinal boiling", distractors: ["Pertaining to an astronomical zenith", "Relating to enzymatic breakdown", "Describing a zero-gravity state"] },
  { word: "infucation", definition: "The act of applying cosmetics to a corpse", distractors: ["The process of inserting a feeding tube", "Gradual infiltration of foreign material", "Systematic corruption of data integrity"] },
  { word: "velleity", definition: "A wish or inclination not strong enough to lead to action", distractors: ["The quality of being swift or nimble in movement", "A philosophical term for the free exercise of the will", "The sensation of soft texture perceived through touch"] },
  { word: "sternutation", definition: "The act or process of sneezing", distractors: ["The reinforcement of ship hulls", "Involuntary vocal cord spasms", "The process of stellar nucleosynthesis"] },
  { word: "witzelsucht", definition: "A neurological condition causing compulsive joking", distractors: ["Obsessive pursuit of linguistic purity", "Pathological fear of humor", "German philosophical movement of anti-rationalism"] },
  { word: "deasil", definition: "Clockwise movement, especially in ritual", distractors: ["A type of medieval fuel oil", "Counter-rotation in astronomical observation", "The dissolution of a formal assembly"] },
  { word: "prolepsis", definition: "The anticipation and answering of possible objections in rhetorical speech; also the representation of a future event as if it has already happened", distractors: ["The involuntary loss of consciousness preceding an epileptic seizure", "A grammatical error in which a pronoun precedes its antecedent without clarity", "The surgical removal of a prolapsed organ to prevent further descent"] },
  { word: "gambrinous", definition: "Being full of beer", distractors: ["Resembling a chess opening strategy", "Having a bold or reckless character", "Relating to maritime gambling customs"] },
  { word: "recrudescence", definition: "The revival or renewed outbreak of something", distractors: ["The healing of a surgical wound", "Gradual hardening of soft tissue", "Restoration of depleted mineral deposits"] },
  { word: "formication", definition: "The sensation of insects crawling on the skin", distractors: ["The industrial process of shaping ant colonies", "Systematic construction of logical proofs", "Architectural technique for creating curved surfaces"] },
  { word: "catachresis", definition: "The incorrect use of a word or the use of a forced or paradoxical figure of speech", distractors: ["A sudden catastrophic failure in a logical argument's structure", "The rhetorical repetition of a word at the end of successive clauses", "A liturgical ceremony of purification through immersion in water"] },
  { word: "enantiodromia", definition: "The tendency of things to change into their opposites, especially as a supposed governing principle of natural cycles and psychological development", distractors: ["A rare metabolic disorder in which enzyme functions are reversed", "The optical property of certain crystals that rotate polarized light", "A neurological condition causing mirror-image reversal in writing"] },
  { word: "apotropaic", definition: "Supposedly having the power to avert evil influences or bad luck", distractors: ["Relating to the atrophy of organs through evolutionary disuse", "Pertaining to the geographic distribution of tropical plant species", "Describing a philosophical argument that proceeds from universal to particular"] },
  { word: "thaumaturgy", definition: "The working of wonders or miracles; magic", distractors: ["The surgical treatment of traumatic injuries to the thorax", "The study of heat transfer in thermodynamic systems", "The branch of metallurgy concerned with gold extraction processes"] },
  { word: "propitiate", definition: "To win or regain the favor of a god, spirit, or person by doing something that pleases them", distractors: ["To formally propose a motion before a legislative assembly", "To accelerate or hasten the progress of an undertaking", "To establish ownership of intellectual property through registration"] },
  { word: "aposiopesis", definition: "A rhetorical device in which the speaker breaks off abruptly and leaves a statement unfinished", distractors: ["The gradual cessation of all metabolic activity preceding clinical death", "A condition in which the body fails to produce sufficient antibodies", "The deliberate omission of logical steps in a mathematical proof"] },
  { word: "emacity", definition: "A fondness for buying things", distractors: ["The state of extreme thinness", "Quality of producing nausea", "Tendency toward verbal aggression"] },
  { word: "deflagration", definition: "Rapid combustion producing a subsonic flame front", distractors: ["The ceremonial lowering of a flag", "Chemical process of removing impurities", "Gradual erosion of legal rights"] },
  { word: "pretermit", definition: "To disregard intentionally or to leave undone; to omit or neglect", distractors: ["To send a transmission before the scheduled time", "To terminate a pregnancy before the fetus reaches viability", "To allow passage through a restricted boundary or membrane"] },
  { word: "defalcation", definition: "The misappropriation of funds by a person entrusted with their management", distractors: ["The surgical removal of the falciform ligament of the liver", "A formal legal declaration that a claim is false and void", "The erosion of limestone formations by carbonic acid"] },
  { word: "tergiversation", definition: "The making of evasive or ambiguous statements; equivocation; also the abandonment of a cause or belief", distractors: ["The tripartite division of a classical verse into stanzas", "The rotation of a celestial body around its own longitudinal axis", "The agricultural process of turning soil in preparation for planting"] },
  { word: "antinomy", definition: "A contradiction between two beliefs or conclusions that are in themselves reasonable; a paradox", distractors: ["A chemical substance that counteracts the toxic effects of antimony", "The legal principle of opposing one statute with another of equal authority", "A medical condition in which the body produces antibodies against its own tissues"] },
  { word: "autochthonous", definition: "Indigenous rather than descended from migrants or colonists; originating where found", distractors: ["Capable of sustaining metabolic processes without external energy sources", "Relating to self-governing territories within a larger political entity", "Describing organisms that reproduce without the involvement of another individual"] },
  { word: "palimpsest", definition: "A manuscript or piece of writing material on which the original writing has been effaced to make room for later writing but of which traces remain", distractors: ["An ancient form of divination by reading the lines of the palm", "A decorative architectural element consisting of layered palm-leaf motifs", "A psychological condition in which new memories overwrite older ones completely"] },
  { word: "casuistry", definition: "The use of clever but unsound reasoning, especially in relation to moral questions; sophistry", distractors: ["The branch of statistics concerned with the analysis of individual case studies", "The medical practice of determining treatment based on case-by-case evaluation", "The systematic classification of grammatical cases in inflected languages"] },
  { word: "synderesis", definition: "The innate ability of the mind to know the basic principles of morality", distractors: ["The medical condition of multiple organ systems failing simultaneously", "A rhetorical device combining two contrasting ideas in a single expression", "The cognitive process of synthesizing disparate sensory inputs into a unified percept"] },
  { word: "paraenesis", definition: "Advice, counsel, or exhortation, especially in a religious or moral context", distractors: ["The insertion of a parenthetical clause that disrupts syntactic flow", "A medical condition involving abnormal nerve sensitivity adjacent to an injury", "The philosophical study of parallel logical systems and their equivalences"] },
  { word: "odalwoman", definition: "A Scandinavian freehold landowner by allodial right", distractors: ["A medieval Norse shieldmaiden", "A woman holding ecclesiastical office in Viking society", "A female member of a Scandinavian trade guild"] },
  { word: "hypostasis", definition: "The underlying state or substance of something; in theology, the person of Christ as distinct from human and divine natures", distractors: ["The cessation of normal physiological function in a dormant organism", "The accumulation of blood in the lowest parts of the body after death", "A stable state of equilibrium maintained by opposing metabolic forces"] },
  { word: "propaedeutic", definition: "Serving as a preliminary instruction or as an introduction to further study", distractors: ["Relating to the prophylactic treatment of disease before symptom onset", "Describing a pediatric approach that emphasizes early developmental intervention", "Pertaining to the propagation of sound waves through dense media"] },
  { word: "supervene", definition: "To occur as an additional or unexpected development; to follow closely upon another event", distractors: ["To override or take precedence over a lower authority's decision", "To exercise administrative oversight over a subordinate organization", "To intervene surgically through a vein rather than an artery"] },
  { word: "desuetude", definition: "A state of disuse or discontinuance", distractors: ["The process by which excessive sweetness is removed from a fermented liquid", "A deep-seated feeling of gratitude that persists beyond its initial cause", "The gradual depletion of moisture from soil through capillary action"] },
  { word: "clerisy", definition: "The educated and intellectual class; the intelligentsia", distractors: ["The collective body of ordained clergy within a religious denomination", "A hierarchical system of administrative officials in a bureaucracy", "The quality of clarity and precision in formal legal writing"] },
  { word: "numinous", definition: "Having a strong religious or spiritual quality; indicating or suggesting the presence of a divinity", distractors: ["Relating to or expressed as a mathematical number or quantity", "Producing a soft, luminous glow visible in low-light conditions", "Pertaining to ancient Roman coinage and monetary systems"] },
  { word: "parataxis", definition: "The placing of clauses or phrases one after another without coordinating or subordinating connectives", distractors: ["The involuntary repetition of words or phrases in aphasic speech", "The arrangement of military units in parallel formation for tactical advantage", "A taxonomic method of classifying organisms by superficial structural similarity"] },
  { word: "infundibular", definition: "Shaped like a funnel", distractors: ["Located beneath the base of the skull", "Relating to foundational legal principles", "Describing a type of inverted arch in architecture"] },
  { word: "lethologica", definition: "The inability to recall a specific word", distractors: ["A medical condition causing excessive drowsiness", "Pathological indifference to consequences", "The study of ancient death rituals"] },
  { word: "eigengrau", definition: "The dark grey color perceived in total darkness", distractors: ["A mathematical transformation of complex matrices", "The philosophical concept of self-determined fate", "Acoustic resonance frequency of enclosed spaces"] },
  { word: "tmema", definition: "A segment cut off; a section or part of a whole", distractors: ["A type of ancient Greek memorial", "A mathematical boundary condition", "A biological membrane between tissue layers"] },
  { word: "dactylonomy", definition: "Counting on one's fingers", distractors: ["The scientific classification of fingerprints", "Study of prehistoric finger bones", "Measurement of digital nerve conductivity"] },
  { word: "anacoluthon", definition: "A syntactic break in which the expected grammatical sequence of a sentence is abruptly altered", distractors: ["A rhetorical figure in which the speaker addresses an absent person or abstraction", "A monastic vow of silence maintained throughout a designated liturgical period", "The pathological inability to complete voluntary movements despite intact motor function"] },
  { word: "epexegesis", definition: "The addition of a word or words to clarify a preceding expression", distractors: ["The critical interpretation of biblical texts through historical-grammatical methods", "The process of removing extraneous genetic material from a chromosome", "A secondary exegetical commentary appended to an existing theological work"] },
  { word: "eucatastrophe", definition: "A sudden turn of events at the end of a story ensuring the protagonist doesn't meet a terrible fate, coined by Tolkien", distractors: ["A natural disaster of unprecedented ecological benefit", "The mathematical optimum of catastrophe theory", "A theological doctrine of universal salvation"] },
  { word: "cryptomnesia", definition: "When a forgotten memory returns and is mistaken for something new", distractors: ["Deliberate encoding of secret messages in text", "The study of encrypted historical documents", "Pathological amnesia affecting only traumatic events"] },
  { word: "witenagemot", definition: "The Anglo-Saxon council of wise men", distractors: ["A medieval German court of arbitration", "An Old Norse term for blood oath", "A Celtic ceremony marking the winter solstice"] },
  { word: "xenoglossy", definition: "The alleged ability to speak a language never learned", distractors: ["A pathological fear of foreign languages", "The study of extinct linguistic systems", "Cross-contamination between adjacent language families"] },
  { word: "usufruct", definition: "The right to enjoy the use and advantages of another's property short of the destruction or waste of its substance", distractors: ["The yield produced by agricultural land over the course of a single season", "A legal claim to the fruits and profits generated by a commercial enterprise", "The natural process by which soil nutrients are consumed by growing vegetation"] },
  { word: "deipnosophist", definition: "A person skilled in the art of dining and dinner-table conversation", distractors: ["A philosopher who argues for the non-existence of deities through rational proof", "An expert in the preparation and presentation of ancient Greek sacrificial feasts", "A theologian who specializes in the study of divine omniscience"] },
  { word: "haruspex", definition: "A Roman religious official who interpreted the will of the gods by inspecting the entrails of sacrificial animals", distractors: ["An ancient Greek astronomer who predicted eclipses using geometric models", "A Celtic druidic practitioner who divined the future from the flight of birds", "A Mesopotamian priest responsible for maintaining temple granary records"] },
  { word: "pervicacious", definition: "Extremely willful; obstinately persistent to the point of being unreasonable", distractors: ["Having a tendency toward predatory or exploitative behavior", "Displaying an unusually sharp or penetrating quality of perception", "Spreading with remarkable rapidity through a vulnerable population"] },
  { word: "pelagian", definition: "Relating to the theology of Pelagius, who denied the doctrines of original sin and predestination; also: of or relating to the open sea", distractors: ["Pertaining to a nomadic pastoral existence on vast open plains", "Describing organisms that dwell exclusively in the deepest ocean trenches", "Relating to the geological epoch marked by extensive continental glaciation"] },
  { word: "eristic", definition: "Of or characterized by argument or controversy; aimed at winning an argument rather than finding truth", distractors: ["Relating to the aesthetic appreciation of sensory pleasure", "Pertaining to the mathematical study of prime number distribution", "Describing a philosophical method that proceeds through systematic doubt"] },
  { word: "misprision", definition: "The deliberate concealment of one's knowledge of a treasonable act or a felony; also: a misunderstanding or misreading", distractors: ["A prison sentence imposed for a minor or summary offense", "The judicial review of a lower court's decision for procedural error", "An unauthorized assumption of authority by a government official"] },
  { word: "preterition", definition: "The rhetorical device of passing over something while actually calling attention to it; in theology, the passing over of the non-elect by God", distractors: ["The grammatical tense used to describe actions completed in the past", "A legal term for the expiration of the statutory limitation period", "The biological process by which excess proteins are degraded and recycled"] },
  { word: "cunctation", definition: "The action or habit of delaying; procrastination", distractors: ["The formal process of joining two grammatical clauses with a conjunction", "The rhythmic contraction of smooth muscle in the digestive tract", "A diplomatic protocol requiring unanimous consent before treaty ratification"] },
  { word: "ergodic", definition: "Relating to or denoting systems that, given sufficient time, evolve through all accessible microstates with equal probability", distractors: ["Pertaining to the study of work efficiency and human factors in design", "Describing chemical reactions that release energy spontaneously", "Relating to the mathematical analysis of error propagation in computations"] },
  { word: "orgulous", definition: "Proud; haughty; swollen with pride", distractors: ["Producing a deep resonant sound like a church organ", "Characterized by an abundance of sensory or aesthetic pleasure", "Relating to the systematic organization of biological specimens"] },
  { word: "aphanisis", definition: "In psychoanalysis, the disappearance of sexual desire", distractors: ["The complete loss of language comprehension following cortical damage", "A botanical condition in which flowers fail to develop visible petals", "The gradual dissolution of self-identity in states of deep meditation"] },
  { word: "obnubilate", definition: "To darken, dim, or obscure; to cloud over", distractors: ["To render a legal contract null and void through formal declaration", "To create a nebulous or gaseous formation through chemical reaction", "To announce publicly and with great ceremony before an assembly"] },
  { word: "dehiscence", definition: "The splitting open of a pod or wound; the release of material by splitting open", distractors: ["The gradual warming process that follows a period of hypothermic exposure", "A literary technique of revealing concealed information through implication", "The progressive loss of structural cohesion in aging connective tissue"] },
  { word: "oculogyric", definition: "Relating to the involuntary rotation of the eyeballs", distractors: ["Pertaining to visual perception of circular motion", "Describing the optical properties of gyroscopes", "Relating to ancient methods of divination by eye movement"] },
  { word: "paralogism", definition: "A piece of illogical or fallacious reasoning, especially one that appears superficially logical or that the reasoner believes to be logical", distractors: ["A mathematical expression involving two parallel logarithmic functions", "A linguistic phenomenon in which two unrelated words converge in meaning", "A medical condition characterized by abnormal paralysis of the vocal cords"] },
  { word: "energumen", definition: "A person believed to be possessed by an evil spirit; an enthusiast or fanatic", distractors: ["A chemical compound that catalyzes the release of stored energy in cells", "A mathematical constant representing the ratio of energy to mass", "A philosophical term for the principle of active force in natural systems"] },
  { word: "deosculate", definition: "To kiss, especially in an affectionate or ritualistic manner", distractors: ["To remove from a circular or orbital path through applied force", "To separate two bonded surfaces through thermal or chemical means", "To oscillate between two fixed points at decreasing amplitude"] },
  { word: "quodlibet", definition: "A philosophical or theological point proposed for disputation; also a light-hearted medley of well-known tunes", distractors: ["A quotation used as an epigraph at the beginning of a scholarly work", "A standardized unit of measurement used in medieval scholastic logic", "A formal declaration of personal belief required for academic licensure"] },
  { word: "iatrogenic", definition: "Relating to illness or harm caused by medical examination or treatment", distractors: ["Pertaining to the self-generating properties of autocatalytic chemical systems", "Describing diseases transmitted between different animal species", "Relating to the study of primitive healing practices in pre-literate cultures"] },
  { word: "nosism", definition: "The use of 'we' to refer to oneself; the royal or editorial 'we'", distractors: ["The philosophical doctrine that knowledge derives from mental constructs rather than reality", "A psychological condition involving excessive preoccupation with disease", "The linguistic phenomenon of nasal consonant assimilation in rapid speech"] },
  { word: "amphigory", definition: "A nonsensical piece of writing, especially one intended as a parody", distractors: ["A formal speech delivered to audiences seated in a semicircular amphitheater", "A biological organism capable of thriving in both aquatic and terrestrial environments", "A rhetorical structure in which arguments are presented from two opposing perspectives"] },
  { word: "mythopoeia", definition: "The making of myths; the tendency to create or interpret myths", distractors: ["The pathological inability to distinguish between fantasy and reality", "A literary genre characterized by the retelling of classical narratives", "The psychological projection of archetypal symbols onto everyday experience"] },
  { word: "ergative", definition: "Relating to a grammatical case that identifies the agent of a transitive verb in certain languages, while the patient takes the same form as the subject of an intransitive verb", distractors: ["Describing a verb form that expresses obligation or necessity", "Pertaining to the passive voice construction in agglutinative languages", "Relating to a syntactic rule that governs the deletion of redundant arguments"] },
  { word: "chthonic", definition: "Relating to or inhabiting the underworld; subterranean", distractors: ["Pertaining to the rhythmic patterns of ancient Greek choral poetry", "Describing the erosive action of ice on exposed geological formations", "Relating to chronic conditions that persist over extended periods"] },
  { word: "alexithymia", definition: "Inability to identify and describe one's own emotions", distractors: ["A condition of being unable to read musical notation", "Pathological inability to process written language", "Neurological disorder affecting taste perception"] },
  { word: "clerihew", definition: "A short comic or nonsensical verse, typically in two rhyming couplets with lines of unequal length, about a famous person", distractors: ["A type of medieval English clerical vestment with embroidered edges", "A satirical song performed by traveling minstrels at market fairs", "A cryptographic cipher developed by Anglican monks for private correspondence"] },
  { word: "parapraxis", definition: "A slip of the tongue or pen, misreading, or other error thought to reveal unconscious wishes or attitudes; a Freudian slip", distractors: ["A repetitive physical action performed as a coping mechanism for anxiety", "The practical application of theoretical principles in a professional context", "A neurological condition in which voluntary movements are initiated but incomplete"] },
  { word: "acheiropoieta", definition: "Images believed to have come into existence without being made by human hands, especially in Eastern Orthodox Christian tradition", distractors: ["Archaeological artifacts of unknown origin found without accompanying contextual evidence", "Philosophical propositions that are accepted as true without requiring empirical demonstration", "Musical compositions generated through aleatoric or chance-based procedural methods"] },
  { word: "pleonasm", definition: "The use of more words than necessary to convey meaning, either as a fault of style or as a rhetorical figure used for emphasis", distractors: ["A malignant growth characterized by uncontrolled cellular proliferation", "The philosophical doctrine that the universe is populated by an excess of souls", "A linguistic phenomenon in which vowel sounds are prolonged beyond normal duration"] },
  { word: "hysteresis", definition: "The dependence of the state of a system on its history; the phenomenon in which the value of a physical property lags behind changes in the effect causing it", distractors: ["A psychological condition of exaggerated emotional response to minor stimuli", "The surgical removal of the uterus for therapeutic purposes", "The tendency of historical narratives to repeat cyclical patterns across civilizations"] },
  { word: "kakistocracy", definition: "Government by the least suitable or competent citizens of a state", distractors: ["A political system in which power is distributed among regional hereditary rulers", "A form of governance based on rigid adherence to canonical religious texts", "A bureaucratic structure in which authority is derived from accumulated seniority"] },
  { word: "incunabulum", definition: "An early printed book, especially one printed before 1501", distractors: ["The innermost chamber of an ancient Egyptian tomb complex", "A rudimentary protective structure built around a developing embryo", "The foundational document establishing the charter of a medieval guild"] },
  { word: "phenakism", definition: "Cheating or deception; imposture", distractors: ["The philosophical study of how things appear to consciousness", "A medical condition involving the abnormal perception of phantom sensations", "The artistic technique of creating optical illusions through sequential images"] },
  { word: "sphragistics", definition: "The study of engraved seals and signet rings, especially as evidence of authentication in documents", distractors: ["The branch of acoustics concerned with the analysis of speech sound production", "The medical specialty dealing with diseases of the esophageal sphincter", "The systematic classification of aromatic compounds by their molecular structure"] },
  { word: "epopee", definition: "An epic poem, or epic poetry as a literary genre", distractors: ["A brief lyrical composition meant to be sung at aristocratic gatherings", "The theatrical convention of aside speeches directed at the audience", "A decorative architectural frieze depicting scenes from mythological narratives"] },
  { word: "emmetropia", definition: "The normal condition of the eye, in which parallel rays are focused exactly on the retina without effort of accommodation", distractors: ["The pathological condition of having differently colored irises in each eye", "A state of perfect metabolic equilibrium maintained by the endocrine system", "The theoretical ideal of proportional representation in electoral systems"] },
  { word: "pareidolia", definition: "The tendency to perceive a specific, often meaningful, image in a random or ambiguous visual pattern", distractors: ["A neurological condition in which bilateral sensory stimuli are perceived as occurring on only one side", "The philosophical doctrine that all perceptions are equally valid representations of reality", "A form of visual agnosia in which familiar objects appear distorted or alien"] },
];

export interface SpellingWord {
  correct: string;
  misspellings: [string, string, string];
}

export const SPELLING_WORDS: SpellingWord[] = [
  { correct: "Glucuronolactonedehydrogenase", misspellings: ["Glucuranolactonedehydrogenase", "Glucuronolactondehydrogenase", "Glucuronolactonedehydrogynase"] },
  { correct: "otorhinolaryngology", misspellings: ["otorhinolaringology", "otorhinolarnygology", "otorhinolaryngolgy"] },
  { correct: "sphygmomanometer", misspellings: ["sphygmomanomter", "sphygmomananometer", "sphygomanometer"] },
  { correct: "dichlorodiphenyltrichloroethane", misspellings: ["dichlorodiphenylthrichloroethane", "dichlorodiphenyltrichloroethene", "dichlorodipheniltrichloroethane"] },
  { correct: "hydroxychloroquine", misspellings: ["hydroxychloroquene", "hydrochloroquine", "hydroxycloroquine"] },
  { correct: "acetylsalicylic", misspellings: ["acetylsalicyclic", "acetylesalicylic", "acetylsalicyllic"] },
  { correct: "Worcestershire", misspellings: ["Worchestershire", "Worcetershire", "Worsestershire"] },
  { correct: "synecdoche", misspellings: ["synechdoche", "synecdoce", "synedoche"] },
  { correct: "charcuterie", misspellings: ["charcutarie", "charcutierie", "charceuterie"] },
  { correct: "Dichlorodifluoromethane", misspellings: ["Dichlorodiflouromethane", "Dichlorodifluoromethan", "Dichlorodifluromethane"] },
  { correct: "minuscule", misspellings: ["miniscule", "minuscle", "minescule"] },
  { correct: "inoculate", misspellings: ["innoculate", "inocullate", "innocculate"] },
  { correct: "desiccate", misspellings: ["dessicate", "desicate", "dessiccate"] },
  { correct: "sacrilegious", misspellings: ["sacreligious", "sacriligious", "sacreligeous"] },
  { correct: "mischievous", misspellings: ["mischievious", "mischevious", "mischevous"] },
  { correct: "ophthalmology", misspellings: ["opthalmology", "ophthamology", "opthamalogy"] },
  { correct: "floccinaucinihilipilification", misspellings: ["floccinaucinihilipilificaton", "flocinaucinihilipilification", "floccinaucinhilipilification"] },
  { correct: "antidisestablishmentarianism", misspellings: ["antidisestablishmentarionism", "antidisestablismentarianism", "antidisestablishmentarainism"] },
  { correct: "triskaidekaphobia", misspellings: ["triskadekaphobia", "triskaidekaphobea", "triskaidecaphobia"] },
  { correct: "pharyngotympanic", misspellings: ["pharyngotimpanic", "pharyngotympannic", "pharyngotympainc"] },
  { correct: "psychophysicist", misspellings: ["psychophysisist", "psychophysicest", "psycophysicist"] },
  { correct: "apothegm", misspellings: ["apothegem", "apothem", "appothegm"] },
  { correct: "Nietzschean", misspellings: ["Nietzchean", "Neitzschean", "Nietzschien"] },
  { correct: "onychophagia", misspellings: ["onychofagia", "onichophagia", "onycophagia"] },
  { correct: "prestidigitation", misspellings: ["prestidigiation", "prestidigitaton", "prestidigatation"] },
  { correct: "chiaroscuro", misspellings: ["chiarascuro", "chiroscuro", "chiaroscurro"] },
  { correct: "daguerreotype", misspellings: ["daguerrotype", "dagerreotype", "daguerotype"] },
  { correct: "eleemosynary", misspellings: ["eleemosinary", "elemosynary", "eleemosynery"] },
  { correct: "hemorrhagic", misspellings: ["hemorhagic", "hemmorhagic", "hemorrhagick"] },
  { correct: "bourgeoisie", misspellings: ["bourgeosie", "bourgoisie", "bourgeoisee"] },
  { correct: "acquiesce", misspellings: ["aquiesce", "acquiese", "acquiessce"] },
  { correct: "chrysanthemum", misspellings: ["chrysantemum", "crysanthemum", "chrysanthymum"] },
  { correct: "idiosyncrasy", misspellings: ["idiosyncracy", "ideosyncracy", "idiosyncrassy"] },
  { correct: "questionnaire", misspellings: ["questionaire", "questionairre", "questionnare"] },
  { correct: "surveillance", misspellings: ["surveilance", "survelliance", "survaillance"] },
  { correct: "reconnaissance", misspellings: ["reconaissance", "reconnaisance", "reconaissence"] },
  { correct: "connoisseur", misspellings: ["connoiseur", "connossieur", "connosieur"] },
  { correct: "dilapidated", misspellings: ["delapidated", "dilapitated", "dilapedated"] },
  { correct: "gubernatorial", misspellings: ["govenatorial", "gubenatorial", "gubernitorial"] },
  { correct: "Mediterranean", misspellings: ["Mediteranean", "Mediterannean", "Meditteranean"] },
  { correct: "liaison", misspellings: ["liason", "liasion", "liasson"] },
  { correct: "surreptitious", misspellings: ["sureptitious", "surreptious", "sureptious"] },
  { correct: "kaleidoscope", misspellings: ["kaleidascope", "kaliedoscope", "kalidoscope"] },
  { correct: "paraphernalia", misspellings: ["paraphenalia", "paraphanalia", "parafernalia"] },
  { correct: "bougainvillea", misspellings: ["bouganvillea", "bougainvilea", "bougainvilla"] },
  { correct: "verisimilitude", misspellings: ["verisimilatude", "verisimiletude", "verissimilitude"] },
  { correct: "schizophrenia", misspellings: ["schitzophrenia", "schizophernia", "skizophrenia"] },
  { correct: "loquacious", misspellings: ["loquatious", "loquacous", "loquashous"] },
  { correct: "onomatopoeia", misspellings: ["onomatapoeia", "onomatopeia", "onomatopoea"] },
  { correct: "ratatouille", misspellings: ["ratatoille", "ratatoullie", "ratatuille"] },
  { correct: "sarsaparilla", misspellings: ["sasparilla", "sarsparilla", "sarsaparila"] },
  { correct: "Phthalylsulfathiazole", misspellings: ["Pthalylsulfathiazole", "Phthalylsulphathiazole", "Phthalylsulfathiozole"] },
  { correct: "Arachibutyrophobia", misspellings: ["Arachibutteryophobia", "Arachybutyrophobia", "Arachibutyraphobia"] },
  { correct: "Phosphatidylethanolamine", misspellings: ["Phosphotidylethanolamine", "Phosphatidylethanalamine", "Phosphatidylethenolaime"] },
  { correct: "Otorhinolaryngological", misspellings: ["Otorhinolarnygological", "Otorhinolaryngalogical", "Otorhinolyryngological"] },
  { correct: "silhouette", misspellings: ["silouette", "silhoette", "silhouete"] },
  { correct: "Llanfairpwllgwyngyll", misspellings: ["Llanfairpwllgwingyll", "Llanfairpwlgwyngyll", "Llanfairpwllgwyngyl"] },
  { correct: "Eyjafjallajokull", misspellings: ["Eyjafjallajokul", "Eyafjallajokull", "Eyjafjallajoekull"] },
  { correct: "Psychophysicotherapeutics", misspellings: ["Psychophysicotheraputics", "Psychophisicotherapeutics", "Psychophysicaotherapeutics"] },
  { correct: "conscientious", misspellings: ["conscentious", "conscientous", "conciencious"] },
  { correct: "fluorescent", misspellings: ["flourescent", "florescent", "fluoresent"] },
  { correct: "epiphenomenon", misspellings: ["epiphenomanon", "epiphenomeneon", "epifenomenon"] },
  { correct: "aphthous", misspellings: ["afthous", "aphtheous", "apthouus"] },
  { correct: "phlegmon", misspellings: ["flegmon", "phlegmone", "phlegmen"] },
  { correct: "sphygmic", misspellings: ["sfygmic", "sphygmick", "sphigmic"] },
  { correct: "diphthong", misspellings: ["dipthong", "diphthonge", "dipthonge"] },
  { correct: "mnemonically", misspellings: ["nemonically", "mnemonickally", "mneumonically"] },
  { correct: "pharaoh", misspellings: ["pharoah", "pharoeh", "pharao"] },
  { correct: "resuscitate", misspellings: ["resusitate", "resussitate", "resucitate"] },
  { correct: "miscellaneous", misspellings: ["miscelaneous", "miscellanious", "miscellanous"] },
  { correct: "entrepreneur", misspellings: ["entrepeneur", "entreprenur", "entreprenueur"] },
  { correct: "embarrassment", misspellings: ["embarassment", "embarrasment", "embarrasement"] },
  { correct: "psyllium", misspellings: ["psylium", "syllium", "psillium"] },
  { correct: "irascible", misspellings: ["irascable", "irrasible", "irascibel"] },
  { correct: "camaraderie", misspellings: ["comraderie", "camaradarie", "cameraderie"] },
  { correct: "aneurysm", misspellings: ["aneurism", "aneurysym", "anueurysm"] },
  { correct: "asphyxiate", misspellings: ["asphixiate", "asphyxeate", "aspyxiate"] },
  { correct: "labyrinthine", misspellings: ["labrynthine", "labyrinthene", "laberinthine"] },
  { correct: "rendezvous", misspellings: ["rendezvouz", "rendevous", "rendayvoo"] },
  { correct: "zucchini", misspellings: ["zuchini", "zuccini", "zuchinni"] },
];

export interface AnalogyPair {
  a: string;
  b: string;
  c: string;
  answer: string;
  relationship: string;
  distractors: [string, string, string];
}

export const ANALOGY_PAIRS: AnalogyPair[] = [
  { a: "benevolent", b: "malevolent", c: "eulogy", answer: "diatribe", relationship: "Latin roots: positive counterpart to negative counterpart (bene/male, eu/dia)", distractors: ["elegy", "soliloquy", "panegyric"] },
  { a: "entropy", b: "disorder", c: "syntropy", answer: "order", relationship: "Thermodynamic concept to its defining characteristic", distractors: ["negentropy", "harmony", "convergence"] },
  { a: "tort", b: "civil", c: "felony", answer: "criminal", relationship: "Legal wrong to its branch of law", distractors: ["penal", "statutory", "federal"] },
  { a: "hypothesis", b: "theory", c: "theory", answer: "law", relationship: "Scientific method progression: less established to more established", distractors: ["principle", "axiom", "theorem"] },
  { a: "tmesis", b: "word-splitting insertion", c: "parenthesis", answer: "clause-embedding insertion", relationship: "Both describe a linguistic phenomenon where material is inserted into the middle of another grammatical unit", distractors: ["phonological assimilation", "morphological derivation", "syntactic extraposition"] },
  { a: "apogee", b: "perigee", c: "aphelion", answer: "perihelion", relationship: "Greek apo-/peri- prefix opposition: farthest to nearest point in orbital mechanics", distractors: ["solstice", "zenith", "nadir"] },
  { a: "ameliorate", b: "improve", c: "exacerbate", answer: "worsen", relationship: "Latinate formal verb to its Anglo-Saxon plain equivalent (opposites)", distractors: ["aggravate", "deteriorate", "intensify"] },
  { a: "pulmonary", b: "lungs", c: "renal", answer: "kidneys", relationship: "Medical Latin adjective to the organ it describes", distractors: ["liver", "bladder", "adrenals"] },
  { a: "pedagogy", b: "children", c: "andragogy", answer: "adults", relationship: "Greek-rooted teaching methodology by age group (paidos/andros)", distractors: ["students", "professionals", "elderly"] },
  { a: "morpheme", b: "meaning", c: "phoneme", answer: "sound", relationship: "Minimal linguistic unit to what it minimally distinguishes", distractors: ["speech", "pronunciation", "articulation"] },
  { a: "hapax", b: "once-occurring", c: "dis", answer: "twice-occurring", relationship: "Both describe frequency of attestation in a corpus, using Greek numerical prefixes", distractors: ["rarely attested", "frequently cited", "multiply derived"] },
  { a: "oligarchy", b: "few", c: "monarchy", answer: "one", relationship: "Greek -archy compound: how many rule", distractors: ["king", "sovereign", "royal"] },
  { a: "borborygmus", b: "stomach", c: "stertor", answer: "nose", relationship: "Both are medical terms for sounds produced by specific body regions during normal physiological processes", distractors: ["throat", "lungs", "chest"] },
  { a: "cognoscenti", b: "knowing", c: "literati", answer: "letters", relationship: "Italian collective noun: people of X (Latin root meaning)", distractors: ["reading", "literature", "writing"] },
  { a: "docile", b: "teachable", c: "ductile", answer: "leadable", relationship: "Latin -ilis adjective: capable of being X (docere/ducere)", distractors: ["stretchable", "malleable", "flexible"] },
  { a: "magnanimous", b: "great soul", c: "pusillanimous", answer: "small soul", relationship: "Latin animus compound: size of spirit (magnus/pusillus)", distractors: ["weak spirit", "cowardly nature", "timid heart"] },
  { a: "sanguine", b: "blood", c: "phlegmatic", answer: "phlegm", relationship: "Humoral temperament to its associated bodily fluid", distractors: ["mucus", "calm", "sluggishness"] },
  { a: "euphemism", b: "pleasant speech", c: "dysphemism", answer: "harsh speech", relationship: "Greek eu-/dys- prefix opposition in rhetorical substitution", distractors: ["profanity", "vulgarity", "obscenity"] },
  { a: "prognosis", b: "forward knowing", c: "diagnosis", answer: "through knowing", relationship: "Greek prefix + gnosis: directional prefix meaning in medical epistemology", distractors: ["identifying disease", "complete knowledge", "deep analysis"] },
  { a: "necropolis", b: "dead", c: "metropolis", answer: "mother", relationship: "Greek compound polis: X-city (nekros/meter)", distractors: ["large", "capital", "central"] },
  { a: "centripetal", b: "toward center", c: "centrifugal", answer: "away from center", relationship: "Latin center-force compounds: directional opposition (petere/fugere)", distractors: ["spinning outward", "escaping orbit", "radial force"] },
  { a: "exoskeleton", b: "outside", c: "endoskeleton", answer: "inside", relationship: "Greek exo-/endo- prefix: skeletal location", distractors: ["internal", "soft", "vertebrate"] },
  { a: "vivid", b: "life", c: "lucid", answer: "light", relationship: "Latin root meaning of English adjective (vivere/lucere)", distractors: ["clarity", "reason", "brightness"] },
  { a: "somnambulism", b: "sleep walking", c: "somniloquy", answer: "sleep talking", relationship: "Latin somn- compound: specific unconscious activity during sleep", distractors: ["dream narration", "sleep speaking", "night mumbling"] },
  { a: "isotherm", b: "equal temperature", c: "isobar", answer: "equal pressure", relationship: "Greek iso- prefix: equal X in cartographic/scientific measurement", distractors: ["same weight", "constant altitude", "uniform density"] },
  { a: "retrospect", b: "backward", c: "prospect", answer: "forward", relationship: "Latin directional prefix + spectare: direction of looking", distractors: ["ahead", "future", "outward"] },
  { a: "benediction", b: "blessing", c: "malediction", answer: "curse", relationship: "Latin bene-/male- opposition + dicere: speech act of good/ill will", distractors: ["insult", "prophecy", "denunciation"] },
  { a: "pyromaniac", b: "fire", c: "kleptomaniac", answer: "stealing", relationship: "Greek -mania compound: object of compulsive urge", distractors: ["collecting", "taking", "hoarding"] },
  { a: "patricide", b: "father", c: "matricide", answer: "mother", relationship: "Latin -cide: killing of specific parent", distractors: ["wife", "queen", "woman"] },
  { a: "aquifer", b: "water", c: "lucifer", answer: "light", relationship: "Latin -fer compound: bearer/carrier of X", distractors: ["fire", "evil", "morning"] },
  { a: "cosmonaut", b: "universe sailor", c: "astronaut", answer: "star sailor", relationship: "Greek etymological compound: what the space traveler sails (kosmos/astron + nautes)", distractors: ["sky pilot", "space explorer", "heaven voyager"] },
  { a: "epidermis", b: "upon the skin", c: "epitaph", answer: "upon the tomb", relationship: "Greek epi- prefix compound: what the surface layer is upon", distractors: ["death inscription", "grave writing", "burial words"] },
  { a: "herbarium", b: "plants", c: "aquarium", answer: "water creatures", relationship: "Latin -arium: contained collection of X", distractors: ["fish", "marine life", "sea animals"] },
  { a: "geocentric", b: "earth", c: "heliocentric", answer: "sun", relationship: "Astronomical model: what occupies the center (geo/helios)", distractors: ["solar", "star", "light"] },
  { a: "hyperthermia", b: "excess", c: "hypothermia", answer: "deficiency", relationship: "Greek hyper-/hypo- prefix: directional deviation from thermal norm", distractors: ["cold", "below normal", "low temperature"] },
  { a: "apiculture", b: "bees", c: "viticulture", answer: "grapevines", relationship: "Latin cultura compound: organism under cultivation", distractors: ["wine", "fruit", "vineyards"] },
  { a: "symphony", b: "together", c: "cacophony", answer: "bad", relationship: "Greek prefix + phone: quality of combined sound (syn/kakos)", distractors: ["loud", "harsh", "discordant"] },
  { a: "philology", b: "words", c: "philosophy", answer: "wisdom", relationship: "Greek philo- compound: what is loved (logos/sophia)", distractors: ["truth", "knowledge", "thinking"] },
  { a: "perihelion", b: "near the sun", c: "aphelion", answer: "far from the sun", relationship: "Greek orbital prefix opposition (peri-/apo-) + helios", distractors: ["away from sun", "opposite sun", "beyond orbit"] },
  { a: "autonomous", b: "self-governing", c: "heteronomous", answer: "other-governing", relationship: "Greek auto-/hetero- prefix + nomos: source of governing law", distractors: ["externally ruled", "collectively governed", "subject to others"] },
  { a: "synchronous", b: "same time", c: "asynchronous", answer: "not same time", relationship: "Greek syn-/a- prefix opposition + chronos: temporal coordination", distractors: ["different time", "delayed", "sequential"] },
  { a: "vivisection", b: "living", c: "dissection", answer: "apart", relationship: "Latin prefix + secare: what kind of cutting (vivus/dis-)", distractors: ["dead", "open", "through"] },
  { a: "lithosphere", b: "rock", c: "hydrosphere", answer: "water", relationship: "Greek Earth-layer compound: constituent material (lithos/hydor)", distractors: ["ocean", "liquid", "moisture"] },
  { a: "rupture", b: "break", c: "suture", answer: "sew", relationship: "Latin medical term: fundamental surgical action", distractors: ["stitch", "close", "repair"] },
  { a: "tachycardia", b: "fast", c: "bradycardia", answer: "slow", relationship: "Greek prefix opposition in cardiac rate condition (tachys/bradys)", distractors: ["weak", "irregular", "low"] },
  { a: "exogamy", b: "outside marriage", c: "endogamy", answer: "inside marriage", relationship: "Greek exo-/endo- + gamos: direction of marriage partner selection", distractors: ["same group", "clan marriage", "arranged marriage"] },
  { a: "hyperopia", b: "far vision", c: "myopia", answer: "near vision", relationship: "Greek-rooted optometric condition: what distance is seen clearly", distractors: ["short sight", "blurred distance", "close focus"] },
  { a: "anabolic", b: "building up", c: "catabolic", answer: "breaking down", relationship: "Greek metabolic prefix opposition (ana-/kata-): direction of biochemical change", distractors: ["destroying", "decomposing", "releasing energy"] },
  { a: "theocracy", b: "god", c: "technocracy", answer: "skill", relationship: "Greek -kratia compound: what quality entitles rule (theos/techne)", distractors: ["technology", "expertise", "science"] },
  { a: "polytheism", b: "many gods", c: "monotheism", answer: "one god", relationship: "Greek number prefix + theos: quantity of divine beings", distractors: ["single deity", "supreme being", "unified god"] },
  { a: "pantheism", b: "all is god", c: "atheism", answer: "no god", relationship: "Greek scope prefix + theos: extent of divinity (pan/a-)", distractors: ["without god", "anti-religion", "secular"] },
  { a: "pachyderm", b: "thick skin", c: "echinoderm", answer: "spiny skin", relationship: "Greek derma compound: quality of the skin (pachys/echinos)", distractors: ["hard shell", "armored body", "rough surface"] },
  { a: "photograph", b: "light writing", c: "telegraph", answer: "distant writing", relationship: "Greek prefix + graphein: means of inscription (photos/tele)", distractors: ["wire message", "electric signal", "coded transmission"] },
  { a: "misogyny", b: "women", c: "misanthropy", answer: "humanity", relationship: "Greek miso- compound: object of hatred (gyne/anthropos)", distractors: ["mankind", "society", "civilization"] },
  { a: "bibliophile", b: "books", c: "oenophile", answer: "wine", relationship: "Greek -philos compound: object of refined love", distractors: ["grapes", "drinking", "fermentation"] },
  { a: "carnivore", b: "flesh", c: "frugivore", answer: "fruit", relationship: "Latin -vorus compound: what is consumed (caro/fructus)", distractors: ["berries", "plants", "seeds"] },
  { a: "circumnavigate", b: "around", c: "transnavigate", answer: "across", relationship: "Latin directional prefix + navigare: path of the journey", distractors: ["through", "over", "beyond"] },
  { a: "inscription", b: "write on", c: "transcription", answer: "write across", relationship: "Latin prefix + scribere: directional metaphor of writing act", distractors: ["copy down", "record", "convert"] },
  { a: "soliloquy", b: "alone speaking", c: "colloquy", answer: "together speaking", relationship: "Latin prefix + loqui: social context of speech (solus/cum)", distractors: ["group discussion", "formal debate", "many voices"] },
  { a: "lexicon", b: "words", c: "pharmacopoeia", answer: "drugs", relationship: "Greek-rooted authoritative reference: what is catalogued", distractors: ["medicines", "prescriptions", "remedies"] },
  { a: "astrolabe", b: "stars", c: "horologe", answer: "time", relationship: "Ancient Greek instrument: what is measured or taken (astron/hora)", distractors: ["hours", "seasons", "sundial"] },
  { a: "neophyte", b: "new plant", c: "epiphyte", answer: "upon plant", relationship: "Greek -phyte compound: prefix meaning applied to plant (neos/epi)", distractors: ["air plant", "parasitic plant", "surface plant"] },
  { a: "fratricide", b: "brother", c: "sororicide", answer: "sister", relationship: "Latin -cide: killing of specific sibling (frater/soror)", distractors: ["twin", "female relative", "daughter"] },
  { a: "aqueduct", b: "water", c: "viaduct", answer: "road", relationship: "Latin -ductus: what is conducted or channeled (aqua/via)", distractors: ["bridge", "path", "passage"] },
  { a: "hemisphere", b: "half", c: "atmosphere", answer: "vapor", relationship: "Greek prefix + sphaira: modifier of the sphere (hemi/atmos)", distractors: ["air", "gas", "breath"] },
  { a: "perennial", b: "through the year", c: "biennial", answer: "two years", relationship: "Latin prefix + annus: temporal span of life cycle", distractors: ["every other year", "twice yearly", "half year"] },
  { a: "unicorn", b: "one horn", c: "trident", answer: "three teeth", relationship: "Latin number prefix + body part (unus+cornu / tres+dens)", distractors: ["three prongs", "triple point", "three spears"] },
  { a: "pyrography", b: "fire writing", c: "calligraphy", answer: "beautiful writing", relationship: "Greek prefix + graphia: quality of the inscription (pyr/kallos)", distractors: ["fancy letters", "ink art", "ornamental script"] },
  { a: "pantomime", b: "all imitation", c: "monochrome", answer: "one color", relationship: "Greek prefix + root: scope applied to the art form (pantos/monos)", distractors: ["single shade", "grayscale", "uniform tone"] },
  { a: "ontology", b: "being", c: "deontology", answer: "duty", relationship: "Greek -logos compound: philosophical study of X (on/deon)", distractors: ["obligation", "ethics", "morality"] },
  { a: "audiometer", b: "hearing", c: "spirometer", answer: "breathing", relationship: "Medical -meter compound: physiological function measured", distractors: ["lung capacity", "air flow", "respiration rate"] },
  { a: "morphology", b: "form", c: "etymology", answer: "true meaning", relationship: "Linguistic -logy: what aspect of language is studied (morphe/etymon)", distractors: ["word origin", "language history", "root words"] },
  { a: "sedentary", b: "sitting", c: "ambulatory", answer: "walking", relationship: "Latin-rooted lifestyle adjective: primary physical posture (sedere/ambulare)", distractors: ["moving", "standing", "mobile"] },
  { a: "photovoltaic", b: "light to electricity", c: "thermoelectric", answer: "heat to electricity", relationship: "Greek prefix: energy source converted to electrical current", distractors: ["temperature difference", "thermal power", "radiation"] },
  { a: "translucent", b: "light passes through partially", c: "transparent", answer: "light passes through fully", relationship: "Latin trans- compound: degree of light transmission (lucere/parere)", distractors: ["completely clear", "see-through", "invisible"] },
  { a: "genocide", b: "race", c: "regicide", answer: "king", relationship: "Latin -cide: what category of entity is killed (genos/rex)", distractors: ["ruler", "monarch", "sovereign"] },
  { a: "antebellum", b: "before war", c: "postbellum", answer: "after war", relationship: "Latin temporal prefix + bellum: when relative to conflict", distractors: ["during war", "between wars", "end of hostilities"] },
  { a: "philanthropy", b: "love of people", c: "misanthropy", answer: "hatred of people", relationship: "Greek phil-/mis- prefix opposition + anthropos: disposition toward humanity", distractors: ["fear of people", "avoidance of people", "distrust of society"] },
  { a: "stethoscope", b: "chest", c: "periscope", answer: "around", relationship: "Greek prefix + skopein: what the viewing instrument observes (stethos/peri)", distractors: ["above", "through", "beneath"] },
  { a: "matrilineal", b: "mother", c: "patrilineal", answer: "father", relationship: "Latin parent root + lineal: through which parent lineage is traced (mater/pater)", distractors: ["family", "ancestors", "male line"] },
];

// ─── Merge extensions (with dedup) ────────────────────────────────────────────
{
  const seen = new Set(RARE_WORDS.map((w) => w.word.toLowerCase()));
  for (const ext of [...RARE_WORDS_EXT_1, ...RARE_WORDS_EXT_2]) {
    const k = ext.word.toLowerCase();
    if (!seen.has(k)) { seen.add(k); RARE_WORDS.push(ext); }
  }
}
{
  const seen = new Set(SPELLING_WORDS.map((w) => w.correct.toLowerCase()));
  for (const ext of SPELLING_WORDS_EXT) {
    const k = ext.correct.toLowerCase();
    if (!seen.has(k)) { seen.add(k); SPELLING_WORDS.push(ext); }
  }
}
{
  const seen = new Set(ANALOGY_PAIRS.map((a) => `${a.a}:${a.b}:${a.c}`.toLowerCase()));
  for (const ext of ANALOGY_PAIRS_EXT) {
    const k = `${ext.a}:${ext.b}:${ext.c}`.toLowerCase();
    if (!seen.has(k)) { seen.add(k); ANALOGY_PAIRS.push(ext); }
  }
}
